In [1]:
import pandas as pd
import numpy as np

In [2]:
# x is input
# y is output
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x

array([[2., 9.],
       [1., 5.],
       [3., 6.]])

In [3]:
y

array([[92.],
       [86.],
       [89.]])

In [4]:
# normalize value means value should be between o and 1
c=np.max(x,axis=0)# to check maximum value column wise
c

array([3., 9.])

In [5]:
x=x/c
x

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [6]:
y=y/100 # normalize the output value by 100 beacuse maximum marks is 100
y

array([[0.92],
       [0.86],
       [0.89]])

In [7]:
def sigmoid(x): # finding activation function
    return 1/1+np.exp(-x)
def sigmoid_grad(x):# think it has diffrenciation during back propagation
    return x*(1-x)

In [8]:
epoch=7000 # number of iteration 
eta=0.1# learning rate
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

In [9]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))# wight at hidden is the size between input and hidden
wh

array([[0.34852661, 0.25602086, 0.39896186],
       [0.43454904, 0.93089664, 0.5409146 ]])

In [10]:
wh.shape

(2, 3)

In [11]:
bh=np.random.uniform(size=(1,hidden_neurons))# bias at hidden
bh

array([[0.52333449, 0.64706194, 0.13879972]])

In [12]:
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
print("Weights from hidden to Output Layer:\n",wout)

Weights from hidden to Output Layer:
 [[0.91104978]
 [0.76627587]
 [0.07152481]]


In [13]:
bout = np.random.uniform(size = (1, output_neurons))
print("Output Bias:\n",bout)

Output Bias:
 [[0.66524956]]


In [14]:
for i in range(epoch):
    #forward pass
    print("\n\t( EPOCH {} of {} )".format(i+1, epoch))
    h_ip = np.dot(x, wh) + bh # to find hidden input value=dot product of input * weight at hidden + bais at hidden
    print("h_ip:\n", h_ip)
    h_act = sigmoid(h_ip)# activation for hidden value
    o_ip = np.dot(h_act, wout) + bout 
    output = sigmoid(o_ip)
    ###########################################
    eo = y - output # finding error at output layer where y is actual output 
    out_grad = sigmoid_grad(output) # diffrenctiating the output 
    d_output = eo * out_grad# getting delta out put = error * gradient output 
    print("Output:\n", d_output)
    eh = d_output.dot(wout.T) # finding error at hidden layer 
    hidden_grad = sigmoid_grad(h_act)
    d_hidden = eh * hidden_grad # same as above 
    wout += h_act.T.dot(d_output) * eta #
    wh += x.T.dot(d_hidden) * eta


	( EPOCH 1 of 7000 )
h_ip:
 [[1.19023461 1.74863916 0.9456889 ]
 [0.88092617 1.24956703 0.57229512]
 [1.16156046 1.52368057 0.89837132]]
Output:
 [[0.00840598]
 [0.00927368]
 [0.00964152]]

	( EPOCH 2 of 7000 )
h_ip:
 [[1.18892935 1.74798383 0.94554384]
 [0.88022801 1.2492167  0.57221752]
 [1.16028553 1.52303748 0.89822981]]
Output:
 [[0.00822607]
 [0.00908253]
 [0.00944358]]

	( EPOCH 3 of 7000 )
h_ip:
 [[1.18764437 1.7473389  0.94539389]
 [0.8795407  1.24887194 0.5721373 ]
 [1.15903036 1.52240459 0.89808352]]
Output:
 [[0.00805403]
 [0.00889959]
 [0.00925412]]

	( EPOCH 4 of 7000 )
h_ip:
 [[1.18637888 1.74670398 0.94523939]
 [0.87886381 1.24853253 0.57205465]
 [1.1577942  1.5217815  0.8979328 ]]
Output:
 [[0.00788934]
 [0.00872436]
 [0.0090726 ]]

	( EPOCH 5 of 7000 )
h_ip:
 [[1.18513216 1.74607869 0.94508067]
 [0.87819697 1.24819826 0.57196974]
 [1.15657632 1.52116786 0.89777795]]
Output:
 [[0.00773153]
 [0.00855632]
 [0.00889852]]

	( EPOCH 6 of 7000 )
h_ip:
 [[1.18390351 1.745462

 [0.00287354]]

	( EPOCH 124 of 7000 )
h_ip:
 [[1.09446477 1.7013605  0.92095564]
 [0.82970718 1.2242953  0.55906489]
 [1.06791672 1.47724858 0.87422549]]
Output:
 [[0.00237782]
 [0.00273606]
 [0.00285779]]

	( EPOCH 125 of 7000 )
h_ip:
 [[1.09393665 1.70110512 0.92076186]
 [0.82942476 1.2241588  0.55896123]
 [1.06739982 1.47699759 0.87403621]]
Output:
 [[0.00236447]
 [0.00272107]
 [0.00284221]]

	( EPOCH 126 of 7000 )
h_ip:
 [[1.09341063 1.70085082 0.92056839]
 [0.82914348 1.22402289 0.55885775]
 [1.06688497 1.47674766 0.87384724]]
Output:
 [[0.00235127]
 [0.00270624]
 [0.00282681]]

	( EPOCH 127 of 7000 )
h_ip:
 [[1.0928867  1.70059759 0.92037524]
 [0.82886331 1.22388754 0.55875444]
 [1.06637217 1.47649879 0.87365859]]
Output:
 [[0.00233823]
 [0.00269158]
 [0.00281158]]

	( EPOCH 128 of 7000 )
h_ip:
 [[1.09236484 1.70034543 0.92018242]
 [0.82858424 1.22375276 0.5586513 ]
 [1.06586138 1.47625096 0.87347025]]
Output:
 [[0.00232533]
 [0.00267709]
 [0.00279652]]

	( EPOCH 129 of 7000 )
h

 [0.00149865]]

	( EPOCH 293 of 7000 )
h_ip:
 [[1.02502233 1.66836918 0.892216  ]
 [0.79257551 1.20666296 0.54369318]
 [0.9999097  1.44481185 0.8461444 ]]
Output:
 [[0.00122458]
 [0.00142535]
 [0.00149444]]

	( EPOCH 294 of 7000 )
h_ip:
 [[1.02469198 1.66821519 0.89206624]
 [0.79239889 1.20658066 0.54361308]
 [0.999586   1.4446604  0.84599802]]
Output:
 [[0.0012211 ]
 [0.00142134]
 [0.00149027]]

	( EPOCH 295 of 7000 )
h_ip:
 [[1.0243623  1.66806154 0.89191668]
 [0.79222262 1.20649855 0.54353309]
 [0.99926295 1.44450927 0.84585184]]
Output:
 [[0.00121764]
 [0.00141736]
 [0.00148611]]

	( EPOCH 296 of 7000 )
h_ip:
 [[1.02403328 1.66790823 0.89176731]
 [0.7920467  1.20641661 0.5434532 ]
 [0.99894055 1.44435847 0.84570584]]
Output:
 [[0.00121419]
 [0.00141339]
 [0.00148198]]

	( EPOCH 297 of 7000 )
h_ip:
 [[1.02370491 1.66775524 0.89161815]
 [0.79187113 1.20633485 0.54337342]
 [0.99861878 1.44420801 0.84556004]]
Output:
 [[0.00121077]
 [0.00140945]
 [0.00147787]]

	( EPOCH 298 of 7000 )
h

 [[0.00084077]
 [0.00098174]
 [0.00103101]]

	( EPOCH 454 of 7000 )
h_ip:
 [[0.97865967 1.64704491 0.87030474]
 [0.76778758 1.19526693 0.53197445]
 [0.9544648  1.4238339  0.82472385]]
Output:
 [[0.00083912]
 [0.00097983]
 [0.001029  ]]

	( EPOCH 455 of 7000 )
h_ip:
 [[0.97840629 1.64692999 0.87018058]
 [0.76765212 1.19520551 0.53190806]
 [0.95421636 1.42372082 0.82460246]]
Output:
 [[0.00083748]
 [0.00097793]
 [0.00102701]]

	( EPOCH 456 of 7000 )
h_ip:
 [[0.97815326 1.64681524 0.87005656]
 [0.76751684 1.19514419 0.53184173]
 [0.95396826 1.42360791 0.82448119]]
Output:
 [[0.00083585]
 [0.00097603]
 [0.00102502]]

	( EPOCH 457 of 7000 )
h_ip:
 [[0.97790057 1.64670067 0.86993267]
 [0.76738174 1.19508296 0.53177547]
 [0.95372049 1.42349518 0.82436004]]
Output:
 [[0.00083422]
 [0.00097414]
 [0.00102304]]

	( EPOCH 458 of 7000 )
h_ip:
 [[0.97764823 1.64658627 0.8698089 ]
 [0.76724683 1.19502182 0.53170927]
 [0.95347306 1.42338261 0.82423902]]
Output:
 [[0.0008326 ]
 [0.00097226]
 [0.0010210

Output:
 [[0.00077106]
 [0.00090083]
 [0.0009462 ]]

	( EPOCH 500 of 7000 )
h_ip:
 [[0.96734659 1.6419311  0.86472125]
 [0.7617393  1.1925341  0.52898834]
 [0.94337131 1.41880195 0.81926416]]
Output:
 [[0.00076967]
 [0.00089921]
 [0.00094451]]

	( EPOCH 501 of 7000 )
h_ip:
 [[0.96710806 1.64182366 0.86460266]
 [0.76161177 1.19247668 0.52892492]
 [0.94313739 1.41869623 0.81914819]]
Output:
 [[0.00076829]
 [0.00089761]
 [0.00094283]]

	( EPOCH 502 of 7000 )
h_ip:
 [[0.96686982 1.64171637 0.86448419]
 [0.76148441 1.19241935 0.52886156]
 [0.94290376 1.41859066 0.81903234]]
Output:
 [[0.00076691]
 [0.00089601]
 [0.00094115]]

	( EPOCH 503 of 7000 )
h_ip:
 [[0.96663189 1.64160923 0.86436583]
 [0.7613572  1.1923621  0.52879826]
 [0.94267043 1.41848523 0.8189166 ]]
Output:
 [[0.00076553]
 [0.00089441]
 [0.00093947]]

	( EPOCH 504 of 7000 )
h_ip:
 [[0.96639425 1.64150224 0.86424758]
 [0.76123016 1.19230492 0.52873502]
 [0.94243738 1.41837995 0.81880097]]
Output:
 [[0.00076416]
 [0.00089282]
 [0

	( EPOCH 655 of 7000 )
h_ip:
 [[0.9334819  1.62683848 0.84756573]
 [0.74363493 1.18446874 0.51981355]
 [0.91015465 1.40394871 0.80248629]]
Output:
 [[0.00060105]
 [0.00070319]
 [0.00073854]]

	( EPOCH 656 of 7000 )
h_ip:
 [[0.93328111 1.62674996 0.84746225]
 [0.74352759 1.18442144 0.51975821]
 [0.90995766 1.40386159 0.80238507]]
Output:
 [[0.0006002 ]
 [0.0007022 ]
 [0.00073749]]

	( EPOCH 657 of 7000 )
h_ip:
 [[0.93308052 1.62666154 0.84735885]
 [0.74342035 1.18437419 0.51970291]
 [0.90976087 1.40377457 0.80228394]]
Output:
 [[0.00059935]
 [0.00070121]
 [0.00073645]]

	( EPOCH 658 of 7000 )
h_ip:
 [[0.93288012 1.62657322 0.84725553]
 [0.74331322 1.184327   0.51964766]
 [0.90956427 1.40368764 0.80218288]]
Output:
 [[0.0005985 ]
 [0.00070022]
 [0.00073541]]

	( EPOCH 659 of 7000 )
h_ip:
 [[0.93267992 1.626485   0.84715229]
 [0.74320619 1.18427985 0.51959245]
 [0.90936786 1.40360081 0.80208191]]
Output:
 [[0.00059765]
 [0.00069924]
 [0.00073437]]

	( EPOCH 660 of 7000 )
h_ip:
 [[0.932479

 [[0.00055888]
 [0.00065413]
 [0.00068684]]

	( EPOCH 709 of 7000 )
h_ip:
 [[0.92291137 1.62219427 0.84209271]
 [0.73798401 1.18198696 0.51688663]
 [0.89978371 1.39937756 0.79713298]]
Output:
 [[0.00055814]
 [0.00065327]
 [0.00068593]]

	( EPOCH 710 of 7000 )
h_ip:
 [[0.92272065 1.62211077 0.8419935 ]
 [0.73788205 1.18194234 0.51683357]
 [0.89959657 1.39929537 0.79703593]]
Output:
 [[0.0005574 ]
 [0.00065241]
 [0.00068503]]

	( EPOCH 711 of 7000 )
h_ip:
 [[0.92253009 1.62202735 0.84189436]
 [0.73778018 1.18189776 0.51678055]
 [0.89940961 1.39921326 0.79693896]]
Output:
 [[0.00055666]
 [0.00065155]
 [0.00068412]]

	( EPOCH 712 of 7000 )
h_ip:
 [[0.92233971 1.62194402 0.8417953 ]
 [0.7376784  1.18185323 0.51672758]
 [0.89922281 1.39913124 0.79684206]]
Output:
 [[0.00055593]
 [0.0006507 ]
 [0.00068322]]

	( EPOCH 713 of 7000 )
h_ip:
 [[0.92214951 1.62186078 0.84169631]
 [0.73757672 1.18180875 0.51667464]
 [0.89903618 1.39904931 0.79674523]]
Output:
 [[0.0005552 ]
 [0.00064985]
 [0.0006823

Output:
 [[0.00046987]
 [0.00055059]
 [0.0005775 ]]

	( EPOCH 851 of 7000 )
h_ip:
 [[0.89742008 1.61112687 0.82870075]
 [0.72435689 1.17607281 0.50972481]
 [0.87476887 1.38848329 0.78403257]]
Output:
 [[0.00046935]
 [0.00054998]
 [0.00057685]]

	( EPOCH 852 of 7000 )
h_ip:
 [[0.8972509  1.61105405 0.82861104]
 [0.72426645 1.1760339  0.50967684]
 [0.87460283 1.3884116  0.78394481]]
Output:
 [[0.00046882]
 [0.00054936]
 [0.0005762 ]]

	( EPOCH 853 of 7000 )
h_ip:
 [[0.89708186 1.61098129 0.82852138]
 [0.72417608 1.17599502 0.50962889]
 [0.87443693 1.38833998 0.7838571 ]]
Output:
 [[0.00046829]
 [0.00054875]
 [0.00057555]]

	( EPOCH 854 of 7000 )
h_ip:
 [[0.89691294 1.6109086  0.82843179]
 [0.72408579 1.17595617 0.50958098]
 [0.87427114 1.38826842 0.78376945]]
Output:
 [[0.00046776]
 [0.00054814]
 [0.0005749 ]]

	( EPOCH 855 of 7000 )
h_ip:
 [[0.89674416 1.61083597 0.82834226]
 [0.72399556 1.17591736 0.5095331 ]
 [0.87410549 1.38819692 0.78368186]]
Output:
 [[0.00046724]
 [0.00054753]
 [0

 [[0.88960708 1.60777243 0.82454725]
 [0.72018031 1.17428029 0.50750361]
 [0.8671006  1.38518109 0.77996914]]
Output:
 [[0.00044569]
 [0.00052247]
 [0.00054774]]

	( EPOCH 899 of 7000 )
h_ip:
 [[0.88944383 1.60770253 0.82446024]
 [0.72009304 1.17424294 0.50745708]
 [0.86694037 1.38511227 0.77988402]]
Output:
 [[0.00044522]
 [0.00052192]
 [0.00054715]]

	( EPOCH 900 of 7000 )
h_ip:
 [[0.88928071 1.60763269 0.82437329]
 [0.72000584 1.17420562 0.50741058]
 [0.86678025 1.38504352 0.77979895]]
Output:
 [[0.00044474]
 [0.00052136]
 [0.00054656]]

	( EPOCH 901 of 7000 )
h_ip:
 [[0.8891177  1.60756291 0.82428639]
 [0.7199187  1.17416833 0.50736411]
 [0.86662026 1.38497482 0.77971393]]
Output:
 [[0.00044426]
 [0.00052081]
 [0.00054598]]

	( EPOCH 902 of 7000 )
h_ip:
 [[0.88895481 1.60749319 0.82419954]
 [0.71983163 1.17413107 0.50731766]
 [0.86646038 1.38490619 0.77962897]]
Output:
 [[0.00044379]
 [0.00052026]
 [0.00054539]]

	( EPOCH 903 of 7000 )
h_ip:
 [[0.88879205 1.60742353 0.82411276]
 [0

 [[0.87007537 1.59946449 0.81407671]
 [0.70973944 1.16984079 0.50190423]
 [0.84792816 1.37700212 0.76972499]]
Output:
 [[0.00039268]
 [0.00046086]
 [0.00048242]]

	( EPOCH 1024 of 7000 )
h_ip:
 [[0.86992575 1.59940128 0.81399605]
 [0.70965946 1.16980702 0.5018611 ]
 [0.84778128 1.37693988 0.76964608]]
Output:
 [[0.00039231]
 [0.00046042]
 [0.00048196]]

	( EPOCH 1025 of 7000 )
h_ip:
 [[0.86977623 1.59933812 0.81391545]
 [0.70957953 1.16977326 0.50181799]
 [0.84763449 1.3768777  0.76956721]]
Output:
 [[0.00039193]
 [0.00045999]
 [0.0004815 ]]

	( EPOCH 1026 of 7000 )
h_ip:
 [[0.8696268  1.599275   0.81383489]
 [0.70949966 1.16973954 0.50177491]
 [0.8474878  1.37681556 0.76948839]]
Output:
 [[0.00039156]
 [0.00045955]
 [0.00048104]]

	( EPOCH 1027 of 7000 )
h_ip:
 [[0.86947748 1.59921194 0.81375437]
 [0.70941984 1.16970584 0.50173185]
 [0.84734121 1.37675347 0.76940961]]
Output:
 [[0.00039118]
 [0.00045912]
 [0.00048058]]

	( EPOCH 1028 of 7000 )
h_ip:
 [[0.86932825 1.59914892 0.8136739 


	( EPOCH 1066 of 7000 )
h_ip:
 [[0.86372864 1.59678889 0.81064991]
 [0.70634679 1.16841104 0.50007167]
 [0.84169743 1.37436794 0.7663721 ]]
Output:
 [[0.00037714]
 [0.00044281]
 [0.00046326]]

	( EPOCH 1067 of 7000 )
h_ip:
 [[0.86358311 1.59672768 0.8105712 ]
 [0.706269   1.16837833 0.50002958]
 [0.84155456 1.37430767 0.76629509]]
Output:
 [[0.00037679]
 [0.0004424 ]
 [0.00046283]]

	( EPOCH 1068 of 7000 )
h_ip:
 [[0.86343768 1.59666651 0.81049254]
 [0.70619125 1.16834565 0.49998752]
 [0.84141178 1.37424745 0.76621812]]
Output:
 [[0.00037644]
 [0.000442  ]
 [0.0004624 ]]

	( EPOCH 1069 of 7000 )
h_ip:
 [[0.86329234 1.59660539 0.81041392]
 [0.70611356 1.16831299 0.49994548]
 [0.84126909 1.37418728 0.7661412 ]]
Output:
 [[0.0003761 ]
 [0.0004416 ]
 [0.00046197]]

	( EPOCH 1070 of 7000 )
h_ip:
 [[0.86314709 1.59654431 0.81033535]
 [0.70603592 1.16828035 0.49990346]
 [0.84112649 1.37412715 0.76606432]]
Output:
 [[0.00037575]
 [0.0004412 ]
 [0.00046155]]

	( EPOCH 1071 of 7000 )
h_ip:
 [[0

h_ip:
 [[0.8459406  1.58935293 0.80098908]
 [0.69683828 1.16443754 0.49490537]
 [0.82423268 1.3670469  0.75691919]]
Output:
 [[0.0003374 ]
 [0.00039669]
 [0.00041422]]

	( EPOCH 1194 of 7000 )
h_ip:
 [[0.84580576 1.58929692 0.80091556]
 [0.6967662  1.16440761 0.49486605]
 [0.82410028 1.36699175 0.75684724]]
Output:
 [[0.00033712]
 [0.00039636]
 [0.00041387]]

	( EPOCH 1195 of 7000 )
h_ip:
 [[0.845671   1.58924095 0.80084207]
 [0.69669417 1.1643777  0.49482675]
 [0.82396796 1.36693665 0.75677533]]
Output:
 [[0.00033684]
 [0.00039603]
 [0.00041353]]

	( EPOCH 1196 of 7000 )
h_ip:
 [[0.84553632 1.58918501 0.80076862]
 [0.69662217 1.16434781 0.49478747]
 [0.82383571 1.36688157 0.75670346]]
Output:
 [[0.00033656]
 [0.00039571]
 [0.00041318]]

	( EPOCH 1197 of 7000 )
h_ip:
 [[0.84540171 1.58912911 0.8006952 ]
 [0.69655022 1.16431794 0.49474822]
 [0.82370354 1.36682654 0.75663162]]
Output:
 [[0.00033628]
 [0.00039538]
 [0.00041284]]

	( EPOCH 1198 of 7000 )
h_ip:
 [[0.84526718 1.58907325 0.80

 [[0.84021083 1.58697753 0.79786096]
 [0.6937755  1.16316821 0.49323256]
 [0.81860649 1.36470815 0.75385826]]
Output:
 [[0.0003257 ]
 [0.00038311]
 [0.00039977]]

	( EPOCH 1237 of 7000 )
h_ip:
 [[0.84007921 1.58692308 0.79778902]
 [0.69370514 1.16313912 0.49319409]
 [0.81847725 1.36465454 0.75378786]]
Output:
 [[0.00032543]
 [0.0003828 ]
 [0.00039944]]

	( EPOCH 1238 of 7000 )
h_ip:
 [[0.83994766 1.58686866 0.79771711]
 [0.69363482 1.16311004 0.49315564]
 [0.81834808 1.36460096 0.7537175 ]]
Output:
 [[0.00032517]
 [0.0003825 ]
 [0.00039912]]

	( EPOCH 1239 of 7000 )
h_ip:
 [[0.83981619 1.58681428 0.79764524]
 [0.69356455 1.16308098 0.4931172 ]
 [0.81821897 1.36454742 0.75364717]]
Output:
 [[0.00032491]
 [0.0003822 ]
 [0.0003988 ]]

	( EPOCH 1240 of 7000 )
h_ip:
 [[0.83968479 1.58675993 0.7975734 ]
 [0.69349431 1.16305194 0.49307879]
 [0.81808994 1.36449391 0.75357687]]
Output:
 [[0.00032465]
 [0.00038189]
 [0.00039847]]

	( EPOCH 1241 of 7000 )
h_ip:
 [[0.83955346 1.58670562 0.7975016 

 [[0.00029742]
 [0.00035034]
 [0.00036485]]

	( EPOCH 1354 of 7000 )
h_ip:
 [[0.8251575  1.58078294 0.7896092 ]
 [0.68572899 1.15985807 0.48881982]
 [0.80382407 1.35860905 0.74578349]]
Output:
 [[0.0002972 ]
 [0.00035009]
 [0.00036457]]

	( EPOCH 1355 of 7000 )
h_ip:
 [[0.82503385 1.58073234 0.78954123]
 [0.6856629  1.15983103 0.48878348]
 [0.80370264 1.35855922 0.74571697]]
Output:
 [[0.00029698]
 [0.00034983]
 [0.0003643 ]]

	( EPOCH 1356 of 7000 )
h_ip:
 [[0.82491026 1.58068176 0.7894733 ]
 [0.68559684 1.159804   0.48874715]
 [0.80358127 1.35850942 0.74565049]]
Output:
 [[0.00029676]
 [0.00034957]
 [0.00036403]]

	( EPOCH 1357 of 7000 )
h_ip:
 [[0.82478674 1.58063122 0.78940539]
 [0.68553081 1.15977699 0.48871083]
 [0.80345996 1.35845966 0.74558404]]
Output:
 [[0.00029654]
 [0.00034932]
 [0.00036376]]

	( EPOCH 1358 of 7000 )
h_ip:
 [[0.82466328 1.5805807  0.78933752]
 [0.68546482 1.15975    0.48867454]
 [0.80333872 1.35840992 0.74551762]]
Output:
 [[0.00029632]
 [0.00034906]
 [0.00

Output:
 [[0.00028754]
 [0.0003389 ]
 [0.00035264]]

	( EPOCH 1400 of 7000 )
h_ip:
 [[0.81953351 1.57848578 0.78651486]
 [0.68272281 1.15863056 0.48716509]
 [0.79830086 1.35634727 0.74275543]]
Output:
 [[0.00028733]
 [0.00033866]
 [0.00035238]]

	( EPOCH 1401 of 7000 )
h_ip:
 [[0.81941267 1.57843653 0.78644831]
 [0.68265822 1.15860424 0.4871295 ]
 [0.79818219 1.35629877 0.7426903 ]]
Output:
 [[0.00028712]
 [0.00033842]
 [0.00035212]]

	( EPOCH 1402 of 7000 )
h_ip:
 [[0.81929189 1.5783873  0.78638179]
 [0.68259366 1.15857793 0.48709393]
 [0.79806357 1.3562503  0.74262521]]
Output:
 [[0.00028692]
 [0.00033818]
 [0.00035187]]

	( EPOCH 1403 of 7000 )
h_ip:
 [[0.81917117 1.57833811 0.7863153 ]
 [0.68252913 1.15855164 0.48705837]
 [0.79794501 1.35620186 0.74256014]]
Output:
 [[0.00028671]
 [0.00033794]
 [0.00035161]]

	( EPOCH 1404 of 7000 )
h_ip:
 [[0.81905051 1.57828894 0.78624884]
 [0.68246464 1.15852537 0.48702284]
 [0.79782651 1.35615345 0.74249511]]
Output:
 [[0.0002865 ]
 [0.0003377 


	( EPOCH 1546 of 7000 )
h_ip:
 [[0.80248808 1.57158057 0.77710288]
 [0.67361165 1.15494069 0.48213194]
 [0.78155951 1.34954835 0.7335448 ]]
Output:
 [[0.00025973]
 [0.00030672]
 [0.00031827]]

	( EPOCH 1547 of 7000 )
h_ip:
 [[0.80237526 1.57153515 0.77704043]
 [0.67355134 1.15491642 0.48209855]
 [0.7814487  1.34950363 0.73348368]]
Output:
 [[0.00025956]
 [0.00030652]
 [0.00031806]]

	( EPOCH 1548 of 7000 )
h_ip:
 [[0.80226249 1.57148975 0.776978  ]
 [0.67349106 1.15489216 0.48206516]
 [0.78133793 1.34945893 0.73342259]]
Output:
 [[0.00025938]
 [0.00030632]
 [0.00031784]]

	( EPOCH 1549 of 7000 )
h_ip:
 [[0.80214977 1.57144438 0.7769156 ]
 [0.67343081 1.15486792 0.48203179]
 [0.78122722 1.34941426 0.73336152]]
Output:
 [[0.00025921]
 [0.00030612]
 [0.00031763]]

	( EPOCH 1550 of 7000 )
h_ip:
 [[0.8020371  1.57139904 0.77685323]
 [0.67337059 1.15484369 0.48199844]
 [0.78111655 1.34936961 0.73330048]]
Output:
 [[0.00025904]
 [0.00030593]
 [0.00031742]]

	( EPOCH 1551 of 7000 )
h_ip:
 [[0


	( EPOCH 1601 of 7000 )
h_ip:
 [[0.79635677 1.56911775 0.77370622]
 [0.67033435 1.15362466 0.48031555]
 [0.7755371  1.34712344 0.73022072]]
Output:
 [[0.00025058]
 [0.00029614]
 [0.00030696]]

	( EPOCH 1602 of 7000 )
h_ip:
 [[0.79624666 1.56907363 0.77364517]
 [0.6702755  1.15360108 0.48028291]
 [0.77542894 1.34707999 0.73016098]]
Output:
 [[0.00025042]
 [0.00029596]
 [0.00030676]]

	( EPOCH 1603 of 7000 )
h_ip:
 [[0.79613659 1.56902952 0.77358414]
 [0.67021667 1.15357751 0.48025027]
 [0.77532083 1.34703656 0.73010126]]
Output:
 [[0.00025026]
 [0.00029577]
 [0.00030657]]

	( EPOCH 1604 of 7000 )
h_ip:
 [[0.79602658 1.56898544 0.77352314]
 [0.67015786 1.15355396 0.48021765]
 [0.77521276 1.34699316 0.73004156]]
Output:
 [[0.0002501 ]
 [0.00029559]
 [0.00030637]]

	( EPOCH 1605 of 7000 )
h_ip:
 [[0.79591661 1.56894138 0.77346217]
 [0.67009908 1.15353041 0.48018504]
 [0.77510474 1.34694978 0.72998189]]
Output:
 [[0.00024994]
 [0.0002954 ]
 [0.00030617]]

	( EPOCH 1606 of 7000 )
h_ip:
 [[0


	( EPOCH 1726 of 7000 )
h_ip:
 [[0.78294906 1.56377096 0.76626069]
 [0.66316776 1.15076755 0.47633401]
 [0.76236668 1.34185894 0.72293418]]
Output:
 [[0.00023188]
 [0.00027454]
 [0.00028385]]

	( EPOCH 1727 of 7000 )
h_ip:
 [[0.78284458 1.5637295  0.76620258]
 [0.66311191 1.1507454  0.47630293]
 [0.76226404 1.34181812 0.72287731]]
Output:
 [[0.00023174]
 [0.00027438]
 [0.00028367]]

	( EPOCH 1728 of 7000 )
h_ip:
 [[0.78274014 1.56368806 0.7661445 ]
 [0.66305609 1.15072325 0.47627187]
 [0.76216145 1.34177733 0.72282047]]
Output:
 [[0.0002316 ]
 [0.00027422]
 [0.0002835 ]]

	( EPOCH 1729 of 7000 )
h_ip:
 [[0.78263574 1.56364665 0.76608643]
 [0.66300028 1.15070112 0.47624082]
 [0.7620589  1.34173655 0.72276364]]
Output:
 [[0.00023146]
 [0.00027406]
 [0.00028333]]

	( EPOCH 1730 of 7000 )
h_ip:
 [[0.78253139 1.56360525 0.76602839]
 [0.66294451 1.150679   0.47620978]
 [0.76195638 1.34169579 0.72270684]]
Output:
 [[0.00023132]
 [0.0002739 ]
 [0.00028316]]

	( EPOCH 1731 of 7000 )
h_ip:
 [[0

h_ip:
 [[0.77787858 1.5617628  0.7634392 ]
 [0.66045754 1.14969447 0.47482519]
 [0.75738565 1.33988171 0.7201729 ]]
Output:
 [[0.00022524]
 [0.00026688]
 [0.00027564]]

	( EPOCH 1776 of 7000 )
h_ip:
 [[0.77777613 1.5617223  0.76338216]
 [0.66040278 1.14967283 0.47479469]
 [0.75728501 1.33984183 0.72011707]]
Output:
 [[0.00022511]
 [0.00026673]
 [0.00027548]]

	( EPOCH 1777 of 7000 )
h_ip:
 [[0.77767372 1.56168182 0.76332514]
 [0.66034804 1.1496512  0.4747642 ]
 [0.7571844  1.33980198 0.72006127]]
Output:
 [[0.00022497]
 [0.00026657]
 [0.00027531]]

	( EPOCH 1778 of 7000 )
h_ip:
 [[0.77757135 1.56164137 0.76326814]
 [0.66029332 1.14962958 0.47473372]
 [0.75708384 1.33976214 0.72000549]]
Output:
 [[0.00022484]
 [0.00026642]
 [0.00027515]]

	( EPOCH 1779 of 7000 )
h_ip:
 [[0.77746902 1.56160093 0.76321117]
 [0.66023862 1.14960797 0.47470325]
 [0.75698331 1.33972233 0.71994973]]
Output:
 [[0.00022471]
 [0.00026627]
 [0.00027499]]

	( EPOCH 1780 of 7000 )
h_ip:
 [[0.77736673 1.56156051 0.76

	( EPOCH 1925 of 7000 )
h_ip:
 [[0.76294381 1.55589215 0.75511276]
 [0.65247482 1.14655743 0.47037259]
 [0.74271348 1.33410151 0.71202406]]
Output:
 [[0.00020695]
 [0.00024578]
 [0.00025303]]

	( EPOCH 1926 of 7000 )
h_ip:
 [[0.76284704 1.55585433 0.75505874]
 [0.65242309 1.14653722 0.4703437 ]
 [0.74261841 1.33406427 0.71197119]]
Output:
 [[0.00020683]
 [0.00024565]
 [0.0002529 ]]

	( EPOCH 1927 of 7000 )
h_ip:
 [[0.76275031 1.55581653 0.75500474]
 [0.65237139 1.14651702 0.47031482]
 [0.74252338 1.33402705 0.71191834]]
Output:
 [[0.00020672]
 [0.00024552]
 [0.00025276]]

	( EPOCH 1928 of 7000 )
h_ip:
 [[0.76265361 1.55577874 0.75495076]
 [0.65231971 1.14649683 0.47028595]
 [0.74242838 1.33398984 0.71186551]]
Output:
 [[0.00020661]
 [0.00024539]
 [0.00025262]]

	( EPOCH 1929 of 7000 )
h_ip:
 [[0.76255695 1.55574097 0.75489679]
 [0.65226804 1.14647664 0.4702571 ]
 [0.74233341 1.33395265 0.7118127 ]]
Output:
 [[0.0002065 ]
 [0.00024526]
 [0.00025248]]

	( EPOCH 1930 of 7000 )
h_ip:
 [[0.

 [0.73809547 1.3322958  0.70945509]]
Output:
 [[0.00020156]
 [0.00023957]
 [0.00024637]]

	( EPOCH 1975 of 7000 )
h_ip:
 [[0.75814833 1.55402114 0.75243472]
 [0.64991163 1.14555763 0.46894049]
 [0.73800207 1.33225934 0.70940312]]
Output:
 [[0.00020145]
 [0.00023945]
 [0.00024624]]

	( EPOCH 1976 of 7000 )
h_ip:
 [[0.7580533  1.55398413 0.75238163]
 [0.64986083 1.14553786 0.4689121 ]
 [0.7379087  1.33222291 0.70935116]]
Output:
 [[0.00020134]
 [0.00023932]
 [0.00024611]]

	( EPOCH 1977 of 7000 )
h_ip:
 [[0.75795831 1.55394714 0.75232856]
 [0.64981006 1.14551809 0.46888372]
 [0.73781537 1.33218649 0.70929922]]
Output:
 [[0.00020123]
 [0.0002392 ]
 [0.00024598]]

	( EPOCH 1978 of 7000 )
h_ip:
 [[0.75786335 1.55391016 0.7522755 ]
 [0.6497593  1.14549833 0.46885535]
 [0.73772207 1.33215008 0.7092473 ]]
Output:
 [[0.00020113]
 [0.00023908]
 [0.00024584]]

	( EPOCH 1979 of 7000 )
h_ip:
 [[0.75776842 1.5538732  0.75222247]
 [0.64970856 1.14547858 0.46882699]
 [0.73762881 1.33211369 0.7091954 ]

 [0.00022865]]

	( EPOCH 2118 of 7000 )
h_ip:
 [[0.74489151 1.54888425 0.74502194]
 [0.64282587 1.14281267 0.46497647]
 [0.724977   1.32720174 0.70214837]]
Output:
 [[0.00018712]
 [0.00022294]
 [0.00022853]]

	( EPOCH 2119 of 7000 )
h_ip:
 [[0.74480108 1.54884938 0.74497132]
 [0.64277753 1.14279404 0.46494941]
 [0.72488814 1.32716742 0.70209883]]
Output:
 [[0.00018702]
 [0.00022283]
 [0.00022842]]

	( EPOCH 2120 of 7000 )
h_ip:
 [[0.74471067 1.54881453 0.74492073]
 [0.64272921 1.14277542 0.46492235]
 [0.72479931 1.32713311 0.70204932]]
Output:
 [[0.00018693]
 [0.00022273]
 [0.0002283 ]]

	( EPOCH 2121 of 7000 )
h_ip:
 [[0.7446203  1.5487797  0.74487015]
 [0.64268091 1.1427568  0.4648953 ]
 [0.72471051 1.32709881 0.70199982]]
Output:
 [[0.00018684]
 [0.00022262]
 [0.00022819]]

	( EPOCH 2122 of 7000 )
h_ip:
 [[0.74452995 1.54874487 0.74481959]
 [0.64263262 1.14273819 0.46486827]
 [0.72462175 1.32706452 0.70195033]]
Output:
 [[0.00018674]
 [0.00022251]
 [0.00022807]]

	( EPOCH 2123 of 70

 [0.72091999 1.32563698 0.69988634]]
Output:
 [[0.0001829 ]
 [0.00021809]
 [0.00022332]]

	( EPOCH 2165 of 7000 )
h_ip:
 [[0.74067344 1.54726069 0.74266077]
 [0.64057133 1.1419451  0.46371383]
 [0.72083248 1.32560328 0.69983753]]
Output:
 [[0.00018281]
 [0.00021798]
 [0.00022321]]

	( EPOCH 2166 of 7000 )
h_ip:
 [[0.7405844  1.54722648 0.74261092]
 [0.64052374 1.14192682 0.46368717]
 [0.72074499 1.3255696  0.69978874]]
Output:
 [[0.00018272]
 [0.00021788]
 [0.0002231 ]]

	( EPOCH 2167 of 7000 )
h_ip:
 [[0.74049539 1.54719228 0.74256108]
 [0.64047616 1.14190855 0.46366052]
 [0.72065754 1.32553592 0.69973997]]
Output:
 [[0.00018263]
 [0.00021778]
 [0.00022299]]

	( EPOCH 2168 of 7000 )
h_ip:
 [[0.74040642 1.54715809 0.74251126]
 [0.64042861 1.14189028 0.46363388]
 [0.72057011 1.32550227 0.69969121]]
Output:
 [[0.00018254]
 [0.00021768]
 [0.00022288]]

	( EPOCH 2169 of 7000 )
h_ip:
 [[0.74031747 1.54712392 0.74246146]
 [0.64038107 1.14187202 0.46360725]
 [0.72048272 1.32546862 0.69964247]

 [0.0002105 ]]

	( EPOCH 2287 of 7000 )
h_ip:
 [[0.73002076 1.54318387 0.73669314]
 [0.63487754 1.13976659 0.46052261]
 [0.7103652  1.32158953 0.69399712]]
Output:
 [[0.00017244]
 [0.00020605]
 [0.0002104 ]]

	( EPOCH 2288 of 7000 )
h_ip:
 [[0.72993514 1.54315124 0.73664515]
 [0.63483178 1.13974916 0.46049695]
 [0.71028106 1.32155741 0.69395015]]
Output:
 [[0.00017236]
 [0.00020596]
 [0.0002103 ]]

	( EPOCH 2289 of 7000 )
h_ip:
 [[0.72984955 1.54311862 0.73659717]
 [0.63478603 1.13973173 0.46047129]
 [0.71019696 1.32152529 0.6939032 ]]
Output:
 [[0.00017228]
 [0.00020587]
 [0.0002102 ]]

	( EPOCH 2290 of 7000 )
h_ip:
 [[0.72976398 1.54308602 0.73654921]
 [0.63474029 1.1397143  0.46044565]
 [0.71011287 1.32149319 0.69385626]]
Output:
 [[0.0001722 ]
 [0.00020577]
 [0.0002101 ]]

	( EPOCH 2291 of 7000 )
h_ip:
 [[0.72967844 1.54305342 0.73650127]
 [0.63469457 1.13969688 0.46042001]
 [0.71002882 1.3214611  0.69380934]]
Output:
 [[0.00017212]
 [0.00020568]
 [0.00021   ]]

	( EPOCH 2292 of 70

 [0.00019292]]

	( EPOCH 2478 of 7000 )
h_ip:
 [[0.71413135 1.53716527 0.72778241]
 [0.62638482 1.13655045 0.45575756]
 [0.69475138 1.31566426 0.6852764 ]]
Output:
 [[0.00015821]
 [0.0001897 ]
 [0.00019283]]

	( EPOCH 2479 of 7000 )
h_ip:
 [[0.71405051 1.53713484 0.72773706]
 [0.62634161 1.13653419 0.4557333 ]
 [0.69467194 1.3156343  0.68523201]]
Output:
 [[0.00015814]
 [0.00018962]
 [0.00019275]]

	( EPOCH 2480 of 7000 )
h_ip:
 [[0.7139697  1.53710442 0.72769171]
 [0.62629841 1.13651793 0.45570905]
 [0.69459253 1.31560436 0.68518764]]
Output:
 [[0.00015807]
 [0.00018954]
 [0.00019266]]

	( EPOCH 2481 of 7000 )
h_ip:
 [[0.7138889  1.53707401 0.72764638]
 [0.62625523 1.13650168 0.45568481]
 [0.69451313 1.31557442 0.68514327]]
Output:
 [[0.000158  ]
 [0.00018946]
 [0.00019258]]

	( EPOCH 2482 of 7000 )
h_ip:
 [[0.71380813 1.53704361 0.72760106]
 [0.62621206 1.13648544 0.45566058]
 [0.69443376 1.3155445  0.68509892]]
Output:
 [[0.00015793]
 [0.00018938]
 [0.00019249]]

	( EPOCH 2483 of 70

	( EPOCH 2527 of 7000 )
h_ip:
 [[0.71019749 1.53568671 0.72557503]
 [0.62428222 1.13576035 0.45457715]
 [0.6908856  1.31420868 0.68311611]]
Output:
 [[0.0001549 ]
 [0.0001859 ]
 [0.00018875]]

	( EPOCH 2528 of 7000 )
h_ip:
 [[0.71011778 1.5356568  0.7255303 ]
 [0.62423962 1.13574437 0.45455323]
 [0.69080726 1.31417923 0.68307233]]
Output:
 [[0.00015483]
 [0.00018582]
 [0.00018866]]

	( EPOCH 2529 of 7000 )
h_ip:
 [[0.7100381  1.53562689 0.72548558]
 [0.62419702 1.13572839 0.45452931]
 [0.69072896 1.3141498  0.68302857]]
Output:
 [[0.00015477]
 [0.00018574]
 [0.00018858]]

	( EPOCH 2530 of 7000 )
h_ip:
 [[0.70995843 1.535597   0.72544088]
 [0.62415445 1.13571242 0.45450541]
 [0.69065067 1.31412037 0.68298481]]
Output:
 [[0.0001547 ]
 [0.00018567]
 [0.0001885 ]]

	( EPOCH 2531 of 7000 )
h_ip:
 [[0.70987879 1.53556712 0.72539618]
 [0.62411188 1.13569645 0.45448151]
 [0.69057241 1.31409095 0.68294107]]
Output:
 [[0.00015463]
 [0.00018559]
 [0.00018842]]

	( EPOCH 2532 of 7000 )
h_ip:
 [[0.

 [0.00017789]]

	( EPOCH 2668 of 7000 )
h_ip:
 [[0.69917591 1.53156851 0.7193888 ]
 [0.61839135 1.1335597  0.45126902]
 [0.68005442 1.31015459 0.67706189]]
Output:
 [[0.00014604]
 [0.00017573]
 [0.00017782]]

	( EPOCH 2669 of 7000 )
h_ip:
 [[0.69909927 1.53153999 0.71934577]
 [0.61835038 1.13354447 0.45124601]
 [0.6799791  1.31012652 0.67701978]]
Output:
 [[0.00014598]
 [0.00017566]
 [0.00017774]]

	( EPOCH 2670 of 7000 )
h_ip:
 [[0.69902264 1.53151149 0.71930275]
 [0.61830943 1.13352923 0.45122301]
 [0.67990379 1.31009845 0.67697768]]
Output:
 [[0.00014592]
 [0.00017559]
 [0.00017767]]

	( EPOCH 2671 of 7000 )
h_ip:
 [[0.69894603 1.53148299 0.71925975]
 [0.61826848 1.13351401 0.45120001]
 [0.6798285  1.3100704  0.67693559]]
Output:
 [[0.00014586]
 [0.00017552]
 [0.0001776 ]]

	( EPOCH 2672 of 7000 )
h_ip:
 [[0.69886944 1.53145451 0.71921675]
 [0.61822755 1.13349878 0.45117702]
 [0.67975324 1.31004236 0.67689352]]
Output:
 [[0.0001458 ]
 [0.00017546]
 [0.00017752]]

	( EPOCH 2673 of 70

 [0.00017457]]

	( EPOCH 2714 of 7000 )
h_ip:
 [[0.69567133 1.53026652 0.71742136]
 [0.61651821 1.13286396 0.45021692]
 [0.67661029 1.30887291 0.67513645]]
Output:
 [[0.00014335]
 [0.00017264]
 [0.0001745 ]]

	( EPOCH 2715 of 7000 )
h_ip:
 [[0.69559563 1.53023844 0.71737886]
 [0.61647775 1.13284895 0.45019419]
 [0.67653589 1.30884526 0.67509486]]
Output:
 [[0.00014329]
 [0.00017257]
 [0.00017443]]

	( EPOCH 2716 of 7000 )
h_ip:
 [[0.69551994 1.53021036 0.71733636]
 [0.61643729 1.13283395 0.45017147]
 [0.67646151 1.30881762 0.67505327]]
Output:
 [[0.00014323]
 [0.00017251]
 [0.00017435]]

	( EPOCH 2717 of 7000 )
h_ip:
 [[0.69544427 1.53018229 0.71729388]
 [0.61639685 1.13281895 0.45014875]
 [0.67638715 1.30878999 0.6750117 ]]
Output:
 [[0.00014318]
 [0.00017244]
 [0.00017428]]

	( EPOCH 2718 of 7000 )
h_ip:
 [[0.69536862 1.53015423 0.71725141]
 [0.61635642 1.13280395 0.45012604]
 [0.6763128  1.30876237 0.67497014]]
Output:
 [[0.00014312]
 [0.00017237]
 [0.00017421]]

	( EPOCH 2719 of 70

h_ip:
 [[0.6862871  1.526798   0.71215275]
 [0.61150251 1.13101047 0.44739949]
 [0.66738772 1.30545856 0.66998037]]
Output:
 [[0.00013641]
 [0.00016468]
 [0.00016594]]

	( EPOCH 2841 of 7000 )
h_ip:
 [[0.68621384 1.52677102 0.71211162]
 [0.61146335 1.13099605 0.4473775 ]
 [0.66731573 1.30543201 0.66994012]]
Output:
 [[0.00013636]
 [0.00016462]
 [0.00016588]]

	( EPOCH 2842 of 7000 )
h_ip:
 [[0.6861406  1.52674405 0.7120705 ]
 [0.61142421 1.13098164 0.44735551]
 [0.66724375 1.30540546 0.66989988]]
Output:
 [[0.00013631]
 [0.00016456]
 [0.00016581]]

	( EPOCH 2843 of 7000 )
h_ip:
 [[0.68606738 1.5267171  0.71202939]
 [0.61138507 1.13096723 0.44733352]
 [0.66717178 1.30537893 0.66985965]]
Output:
 [[0.00013626]
 [0.0001645 ]
 [0.00016575]]

	( EPOCH 2844 of 7000 )
h_ip:
 [[0.68599417 1.52669015 0.71198829]
 [0.61134595 1.13095283 0.44731155]
 [0.66709984 1.3053524  0.66981943]]
Output:
 [[0.0001362 ]
 [0.00016444]
 [0.00016569]]

	( EPOCH 2845 of 7000 )
h_ip:
 [[0.68592099 1.5266632  0.71

 [[0.00013418]
 [0.00016212]
 [0.0001632 ]]

	( EPOCH 2884 of 7000 )
h_ip:
 [[0.68308124 1.52561901 0.71035286]
 [0.60978904 1.13038044 0.44643699]
 [0.66423703 1.30429803 0.66821895]]
Output:
 [[0.00013413]
 [0.00016207]
 [0.00016313]]

	( EPOCH 2885 of 7000 )
h_ip:
 [[0.6830088  1.5255924  0.71031218]
 [0.60975032 1.13036622 0.44641524]
 [0.66416583 1.30427183 0.66817915]]
Output:
 [[0.00013408]
 [0.00016201]
 [0.00016307]]

	( EPOCH 2886 of 7000 )
h_ip:
 [[0.68293637 1.5255658  0.71027152]
 [0.60971161 1.13035201 0.44639349]
 [0.66409465 1.30424565 0.66813935]]
Output:
 [[0.00013403]
 [0.00016195]
 [0.00016301]]

	( EPOCH 2887 of 7000 )
h_ip:
 [[0.68286396 1.52553921 0.71023087]
 [0.60967291 1.1303378  0.44637175]
 [0.66402349 1.30421948 0.66809957]]
Output:
 [[0.00013398]
 [0.00016189]
 [0.00016294]]

	( EPOCH 2888 of 7000 )
h_ip:
 [[0.68279157 1.52551263 0.71019022]
 [0.60963422 1.13032359 0.44635002]
 [0.66395234 1.30419331 0.66805979]]
Output:
 [[0.00013393]
 [0.00016183]
 [0.00


	( EPOCH 3035 of 7000 )
h_ip:
 [[0.67234276 1.5216918  0.70432438]
 [0.60404955 1.12828182 0.4432132 ]
 [0.6536831  1.3004324  0.66231939]]
Output:
 [[0.00012681]
 [0.00015367]
 [0.0001541 ]]

	( EPOCH 3036 of 7000 )
h_ip:
 [[0.67227296 1.52166638 0.70428519]
 [0.60401224 1.12826824 0.44319225]
 [0.65361449 1.30040738 0.66228104]]
Output:
 [[0.00012676]
 [0.00015361]
 [0.00015405]]

	( EPOCH 3037 of 7000 )
h_ip:
 [[0.67220317 1.52164097 0.70424602]
 [0.60397494 1.12825466 0.4431713 ]
 [0.6535459  1.30038237 0.6622427 ]]
Output:
 [[0.00012671]
 [0.00015356]
 [0.00015399]]

	( EPOCH 3038 of 7000 )
h_ip:
 [[0.6721334  1.52161557 0.70420685]
 [0.60393765 1.12824109 0.44315036]
 [0.65347733 1.30035737 0.66220438]]
Output:
 [[0.00012667]
 [0.00015351]
 [0.00015393]]

	( EPOCH 3039 of 7000 )
h_ip:
 [[0.67206364 1.52159017 0.7041677 ]
 [0.60390036 1.12822752 0.44312942]
 [0.65340877 1.30033237 0.66216606]]
Output:
 [[0.00012662]
 [0.00015345]
 [0.00015388]]

	( EPOCH 3040 of 7000 )
h_ip:
 [[0

	( EPOCH 3086 of 7000 )
h_ip:
 [[0.66880389 1.520405   0.702338  ]
 [0.6021581  1.12759418 0.44215097]
 [0.65020497 1.29916582 0.66037552]]
Output:
 [[0.00012449]
 [0.00015101]
 [0.00015125]]

	( EPOCH 3087 of 7000 )
h_ip:
 [[0.66873493 1.52037996 0.7022993 ]
 [0.60212124 1.1275808  0.44213027]
 [0.65013719 1.29914118 0.66033764]]
Output:
 [[0.00012445]
 [0.00015096]
 [0.0001512 ]]

	( EPOCH 3088 of 7000 )
h_ip:
 [[0.66866598 1.52035492 0.7022606 ]
 [0.60208439 1.12756742 0.44210958]
 [0.65006943 1.29911654 0.66029978]]
Output:
 [[0.0001244 ]
 [0.00015091]
 [0.00015114]]

	( EPOCH 3089 of 7000 )
h_ip:
 [[0.66859705 1.5203299  0.70222191]
 [0.60204755 1.12755405 0.44208889]
 [0.65000169 1.29909191 0.66026192]]
Output:
 [[0.00012436]
 [0.00015086]
 [0.00015109]]

	( EPOCH 3090 of 7000 )
h_ip:
 [[0.66852814 1.52030488 0.70218324]
 [0.60201072 1.12754068 0.44206821]
 [0.64993396 1.29906728 0.66022407]]
Output:
 [[0.00012432]
 [0.00015081]
 [0.00015103]]

	( EPOCH 3091 of 7000 )
h_ip:
 [[0.

 [0.6415251  1.2960209  0.6555257 ]]
Output:
 [[0.00011893]
 [0.00014463]
 [0.00014439]]

	( EPOCH 3217 of 7000 )
h_ip:
 [[0.65990566 1.51718563 0.69734451]
 [0.5974022  1.12587381 0.43948064]
 [0.64145934 1.29599716 0.65548897]]
Output:
 [[0.00011889]
 [0.00014459]
 [0.00014434]]

	( EPOCH 3218 of 7000 )
h_ip:
 [[0.65983876 1.51716152 0.69730698]
 [0.59736645 1.12586092 0.43946057]
 [0.64139359 1.29597342 0.65545224]]
Output:
 [[0.00011884]
 [0.00014454]
 [0.00014429]]

	( EPOCH 3219 of 7000 )
h_ip:
 [[0.65977188 1.51713741 0.69726945]
 [0.5973307  1.12584804 0.43944051]
 [0.64132785 1.29594969 0.65541552]]
Output:
 [[0.0001188 ]
 [0.00014449]
 [0.00014424]]

	( EPOCH 3220 of 7000 )
h_ip:
 [[0.65970501 1.5171133  0.69723193]
 [0.59729496 1.12583516 0.43942044]
 [0.64126213 1.29592597 0.6553788 ]]
Output:
 [[0.00011876]
 [0.00014445]
 [0.00014419]]

	( EPOCH 3221 of 7000 )
h_ip:
 [[0.65963816 1.51708921 0.69719443]
 [0.59725923 1.12582228 0.43940038]
 [0.64119642 1.29590226 0.6553421 ]

 [0.63851524 1.29493565 0.65384446]]
Output:
 [[0.00011706]
 [0.0001425 ]
 [0.0001421 ]]

	( EPOCH 3263 of 7000 )
h_ip:
 [[0.65684402 1.51608329 0.69562684]
 [0.59576583 1.12528473 0.4385621 ]
 [0.63845016 1.29491222 0.6538081 ]]
Output:
 [[0.00011702]
 [0.00014245]
 [0.00014205]]

	( EPOCH 3264 of 7000 )
h_ip:
 [[0.65677782 1.51605948 0.6955897 ]
 [0.59573045 1.12527201 0.43854224]
 [0.63838509 1.29488878 0.65377176]]
Output:
 [[0.00011698]
 [0.00014241]
 [0.000142  ]]

	( EPOCH 3265 of 7000 )
h_ip:
 [[0.65671163 1.51603568 0.69555256]
 [0.59569507 1.12525929 0.43852238]
 [0.63832003 1.29486536 0.65373542]]
Output:
 [[0.00011694]
 [0.00014236]
 [0.00014195]]

	( EPOCH 3266 of 7000 )
h_ip:
 [[0.65664545 1.51601189 0.69551544]
 [0.5956597  1.12524658 0.43850253]
 [0.63825499 1.29484194 0.6536991 ]]
Output:
 [[0.0001169 ]
 [0.00014232]
 [0.0001419 ]]

	( EPOCH 3267 of 7000 )
h_ip:
 [[0.65657929 1.5159881  0.69547833]
 [0.59562434 1.12523387 0.43848268]
 [0.63818996 1.29481853 0.65366278]

Output:
 [[0.0001121 ]
 [0.00013682]
 [0.000136  ]]

	( EPOCH 3392 of 7000 )
h_ip:
 [[0.64842372 1.51306569 0.69090426]
 [0.5912654  1.12367216 0.43603664]
 [0.63017401 1.29194234 0.64918681]]
Output:
 [[0.00011207]
 [0.00013678]
 [0.00013595]]

	( EPOCH 3393 of 7000 )
h_ip:
 [[0.64835937 1.51304271 0.69086818]
 [0.591231   1.12365988 0.43601734]
 [0.63011077 1.29191972 0.64915151]]
Output:
 [[0.00011203]
 [0.00013673]
 [0.00013591]]

	( EPOCH 3394 of 7000 )
h_ip:
 [[0.64829504 1.51301974 0.69083211]
 [0.59119662 1.12364761 0.43599805]
 [0.63004754 1.29189711 0.64911621]]
Output:
 [[0.00011199]
 [0.00013669]
 [0.00013586]]

	( EPOCH 3395 of 7000 )
h_ip:
 [[0.64823072 1.51299677 0.69079604]
 [0.59116224 1.12363533 0.43597877]
 [0.62998432 1.29187451 0.64908092]]
Output:
 [[0.00011196]
 [0.00013665]
 [0.00013581]]

	( EPOCH 3396 of 7000 )
h_ip:
 [[0.64816641 1.51297381 0.69075999]
 [0.59112787 1.12362306 0.43595948]
 [0.62992111 1.29185191 0.64904564]]
Output:
 [[0.00011192]
 [0.00013661

	( EPOCH 3552 of 7000 )
h_ip:
 [[0.63830094 1.50946534 0.6852303 ]
 [0.58585504 1.12174817 0.4330024 ]
 [0.62022434 1.28839912 0.64363471]]
Output:
 [[0.00010642]
 [0.00013031]
 [0.000129  ]]

	( EPOCH 3553 of 7000 )
h_ip:
 [[0.63823874 1.50944331 0.68519545]
 [0.58582179 1.1217364  0.43298377]
 [0.6201632  1.28837744 0.64360061]]
Output:
 [[0.00010639]
 [0.00013027]
 [0.00012896]]

	( EPOCH 3554 of 7000 )
h_ip:
 [[0.63817655 1.50942129 0.68516061]
 [0.58578856 1.12172463 0.43296513]
 [0.62010208 1.28835577 0.64356651]]
Output:
 [[0.00010635]
 [0.00013023]
 [0.00012892]]

	( EPOCH 3555 of 7000 )
h_ip:
 [[0.63811437 1.50939927 0.68512577]
 [0.58575532 1.12171286 0.4329465 ]
 [0.62004097 1.2883341  0.64353243]]
Output:
 [[0.00010632]
 [0.00013019]
 [0.00012888]]

	( EPOCH 3556 of 7000 )
h_ip:
 [[0.63805221 1.50937726 0.68509094]
 [0.5857221  1.1217011  0.43292788]
 [0.61997987 1.28831244 0.64349835]]
Output:
 [[0.00010629]
 [0.00013016]
 [0.00012884]]

	( EPOCH 3557 of 7000 )
h_ip:
 [[0.


	( EPOCH 3598 of 7000 )
h_ip:
 [[0.63545296 1.50845779 0.68363477]
 [0.58433287 1.12120974 0.43214916]
 [0.61742503 1.2874076  0.64207347]]
Output:
 [[0.00010489]
 [0.00012856]
 [0.00012712]]

	( EPOCH 3599 of 7000 )
h_ip:
 [[0.63539135 1.50843602 0.68360025]
 [0.58429994 1.1211981  0.43213071]
 [0.61736447 1.28738617 0.6420397 ]]
Output:
 [[0.00010486]
 [0.00012852]
 [0.00012708]]

	( EPOCH 3600 of 7000 )
h_ip:
 [[0.63532975 1.50841425 0.68356575]
 [0.58426702 1.12118647 0.43211225]
 [0.61730392 1.28736475 0.64200594]]
Output:
 [[0.00010483]
 [0.00012848]
 [0.00012704]]

	( EPOCH 3601 of 7000 )
h_ip:
 [[0.63526816 1.50839249 0.68353125]
 [0.5842341  1.12117484 0.43209381]
 [0.61724339 1.28734334 0.64197218]]
Output:
 [[0.00010479]
 [0.00012844]
 [0.000127  ]]

	( EPOCH 3602 of 7000 )
h_ip:
 [[0.63520658 1.50837074 0.68349676]
 [0.58420119 1.12116322 0.43207536]
 [0.61718287 1.28732193 0.64193843]]
Output:
 [[0.00010476]
 [0.00012841]
 [0.00012696]]

	( EPOCH 3603 of 7000 )
h_ip:
 [[0

 [0.00012228]]

	( EPOCH 3723 of 7000 )
h_ip:
 [[0.62784741 1.50577865 0.67937581]
 [0.58026792 1.11977802 0.42987161]
 [0.60994938 1.28477118 0.63790615]]
Output:
 [[0.00010093]
 [0.00012402]
 [0.00012225]]

	( EPOCH 3724 of 7000 )
h_ip:
 [[0.62778733 1.50575755 0.67934218]
 [0.58023581 1.11976674 0.42985362]
 [0.60989033 1.28475042 0.63787324]]
Output:
 [[0.0001009 ]
 [0.00012398]
 [0.00012221]]

	( EPOCH 3725 of 7000 )
h_ip:
 [[0.62772726 1.50573646 0.67930855]
 [0.5802037  1.11975547 0.42983564]
 [0.60983129 1.28472966 0.63784034]]
Output:
 [[0.00010086]
 [0.00012395]
 [0.00012217]]

	( EPOCH 3726 of 7000 )
h_ip:
 [[0.62766721 1.50571538 0.67927494]
 [0.58017161 1.1197442  0.42981767]
 [0.60977226 1.28470891 0.63780745]]
Output:
 [[0.00010083]
 [0.00012391]
 [0.00012213]]

	( EPOCH 3727 of 7000 )
h_ip:
 [[0.62760717 1.5056943  0.67924133]
 [0.58013952 1.11973294 0.42979969]
 [0.60971324 1.28468817 0.63777456]]
Output:
 [[0.0001008 ]
 [0.00012388]
 [0.0001221 ]]

	( EPOCH 3728 of 70


	( EPOCH 3769 of 7000 )
h_ip:
 [[0.62509611 1.50481361 0.67783587]
 [0.57879742 1.1192623  0.4290481 ]
 [0.60724504 1.28382156 0.63639938]]
Output:
 [[9.95332917e-05]
 [1.22421017e-04]
 [1.20534606e-04]]

	( EPOCH 3770 of 7000 )
h_ip:
 [[0.62503657 1.50479275 0.67780256]
 [0.57876561 1.11925115 0.42903028]
 [0.60718653 1.28380103 0.63636678]]
Output:
 [[9.95033914e-05]
 [1.22386779e-04]
 [1.20497856e-04]]

	( EPOCH 3771 of 7000 )
h_ip:
 [[0.62497705 1.5047719  0.67776925]
 [0.57873379 1.11924001 0.42901247]
 [0.60712802 1.28378051 0.63633419]]
Output:
 [[9.94735071e-05]
 [1.22352558e-04]
 [1.20461126e-04]]

	( EPOCH 3772 of 7000 )
h_ip:
 [[0.62491754 1.50475105 0.67773594]
 [0.57870199 1.11922887 0.42899466]
 [0.60706952 1.28376    0.6363016 ]]
Output:
 [[9.94436388e-05]
 [1.22318356e-04]
 [1.20424415e-04]]

	( EPOCH 3773 of 7000 )
h_ip:
 [[0.62485804 1.50473021 0.67770265]
 [0.57867019 1.11921773 0.42897685]
 [0.60701104 1.28373949 0.63626902]]
Output:
 [[9.94137864e-05]
 [1.22284173

h_ip:
 [[0.617511   1.50216444 0.67359265]
 [0.5747434  1.11784658 0.42677895]
 [0.59978936 1.28121481 0.63224761]]
Output:
 [[9.58036678e-05]
 [1.18150310e-04]
 [1.15951614e-04]]

	( EPOCH 3899 of 7000 )
h_ip:
 [[0.61745293 1.50214422 0.67356018]
 [0.57471237 1.11783578 0.42676158]
 [0.59973229 1.28119492 0.63221584]]
Output:
 [[9.57757271e-05]
 [1.18118316e-04]
 [1.15917289e-04]]

	( EPOCH 3900 of 7000 )
h_ip:
 [[0.61739487 1.50212401 0.67352771]
 [0.57468134 1.11782498 0.42674422]
 [0.59967522 1.28117503 0.63218408]]
Output:
 [[9.57478008e-05]
 [1.18086338e-04]
 [1.15882981e-04]]

	( EPOCH 3901 of 7000 )
h_ip:
 [[0.61733683 1.5021038  0.67349525]
 [0.57465032 1.11781418 0.42672687]
 [0.59961817 1.28115515 0.63215232]]
Output:
 [[9.57198890e-05]
 [1.18054377e-04]
 [1.15848691e-04]]

	( EPOCH 3902 of 7000 )
h_ip:
 [[0.6172788  1.5020836  0.6734628 ]
 [0.5746193  1.11780338 0.42670951]
 [0.59956112 1.28113527 0.63212057]]
Output:
 [[9.56919917e-05]
 [1.18022433e-04]
 [1.15814418e-04]]


 [0.59734484 1.28036373 0.63088713]]
Output:
 [[9.46151288e-05]
 [1.16789349e-04]
 [1.14491575e-04]]

	( EPOCH 3942 of 7000 )
h_ip:
 [[0.61496645 1.50127946 0.67216997]
 [0.57338342 1.11737365 0.42601814]
 [0.59728822 1.28034404 0.63085563]]
Output:
 [[9.45877995e-05]
 [1.16758055e-04]
 [1.14458006e-04]]

	( EPOCH 3943 of 7000 )
h_ip:
 [[0.61490887 1.50125945 0.67213778]
 [0.57335264 1.11736295 0.42600093]
 [0.59723162 1.28032435 0.63082413]]
Output:
 [[9.45604842e-05]
 [1.16726777e-04]
 [1.14424453e-04]]

	( EPOCH 3944 of 7000 )
h_ip:
 [[0.6148513  1.50123945 0.67210559]
 [0.57332187 1.11735227 0.42598371]
 [0.59717503 1.28030467 0.63079264]]
Output:
 [[9.45331829e-05]
 [1.16695515e-04]
 [1.14390918e-04]]

	( EPOCH 3945 of 7000 )
h_ip:
 [[0.61479373 1.50121946 0.67207341]
 [0.57329111 1.11734158 0.42596651]
 [0.59711845 1.280285   0.63076116]]
Output:
 [[9.45058955e-05]
 [1.16664269e-04]
 [1.14357401e-04]]

	( EPOCH 3946 of 7000 )
h_ip:
 [[0.61473618 1.50119947 0.67204124]
 [0.5732603


	( EPOCH 4067 of 7000 )
h_ip:
 [[0.60785104 1.4988147  0.66819389]
 [0.56958045 1.11605646 0.42389184]
 [0.59029413 1.27791892 0.62696542]]
Output:
 [[9.12784514e-05]
 [1.12968556e-04]
 [1.10393908e-04]]

	( EPOCH 4068 of 7000 )
h_ip:
 [[0.60779478 1.49879526 0.66816247]
 [0.56955037 1.11604608 0.42387504]
 [0.59023883 1.2778998  0.62693467]]
Output:
 [[9.12528047e-05]
 [1.12939188e-04]
 [1.10362420e-04]]

	( EPOCH 4069 of 7000 )
h_ip:
 [[0.60773852 1.49877584 0.66813105]
 [0.56952031 1.1160357  0.42385823]
 [0.59018354 1.27788069 0.62690393]]
Output:
 [[9.12271708e-05]
 [1.12909834e-04]
 [1.10330947e-04]]

	( EPOCH 4070 of 7000 )
h_ip:
 [[0.60768228 1.49875642 0.66809963]
 [0.56949025 1.11602532 0.42384143]
 [0.59012825 1.27786158 0.62687319]]
Output:
 [[9.12015497e-05]
 [1.12880495e-04]
 [1.10299490e-04]]

	( EPOCH 4071 of 7000 )
h_ip:
 [[0.60762605 1.498737   0.66806822]
 [0.5694602  1.11601494 0.42382464]
 [0.59007298 1.27784248 0.62684246]]
Output:
 [[9.11759413e-05]
 [1.12851170

	( EPOCH 4117 of 7000 )
h_ip:
 [[0.60505043 1.49784858 0.66662986]
 [0.56808361 1.11554016 0.42305544]
 [0.58754127 1.27696838 0.6254352 ]]
Output:
 [[9.00115472e-05]
 [1.11517789e-04]
 [1.08838550e-04]]

	( EPOCH 4118 of 7000 )
h_ip:
 [[0.60499468 1.49782937 0.66659873]
 [0.56805381 1.1155299  0.42303879]
 [0.58748647 1.27694948 0.62540474]]
Output:
 [[8.99865264e-05]
 [1.11489137e-04]
 [1.08807835e-04]]

	( EPOCH 4119 of 7000 )
h_ip:
 [[0.60493894 1.49781016 0.66656761]
 [0.56802402 1.11551963 0.42302215]
 [0.58743167 1.27693059 0.62537429]]
Output:
 [[8.99615179e-05]
 [1.11460498e-04]
 [1.08777135e-04]]

	( EPOCH 4120 of 7000 )
h_ip:
 [[0.60488321 1.49779096 0.66653649]
 [0.56799423 1.11550937 0.42300551]
 [0.58737689 1.27691169 0.62534384]]
Output:
 [[8.99365216e-05]
 [1.11431874e-04]
 [1.08746451e-04]]

	( EPOCH 4121 of 7000 )
h_ip:
 [[0.60482748 1.49777177 0.66650538]
 [0.56796445 1.11549911 0.42298887]
 [0.58732212 1.27689281 0.6253134 ]]
Output:
 [[8.99115377e-05]
 [1.11403264e

 [0.58055224 1.27456523 0.62155284]]
Output:
 [[8.68823079e-05]
 [1.07934209e-04]
 [1.04998034e-04]]

	( EPOCH 4247 of 7000 )
h_ip:
 [[0.59788575 1.49538729 0.66263124]
 [0.5642543  1.11422482 0.42091707]
 [0.58049868 1.27454687 0.6215231 ]]
Output:
 [[8.68588020e-05]
 [1.07907289e-04]
 [1.04969192e-04]]

	( EPOCH 4248 of 7000 )
h_ip:
 [[0.59783128 1.49536863 0.66260085]
 [0.56422519 1.11421485 0.42090082]
 [0.58044514 1.27452851 0.62149337]]
Output:
 [[8.68353073e-05]
 [1.07880381e-04]
 [1.04940364e-04]]

	( EPOCH 4249 of 7000 )
h_ip:
 [[0.59777681 1.49534998 0.66257047]
 [0.56419608 1.11420488 0.42088457]
 [0.5803916  1.27451016 0.62146365]]
Output:
 [[8.68118239e-05]
 [1.07853487e-04]
 [1.04911549e-04]]

	( EPOCH 4250 of 7000 )
h_ip:
 [[0.59772236 1.49533133 0.66254009]
 [0.56416697 1.11419491 0.42086833]
 [0.58033807 1.27449182 0.62143393]]
Output:
 [[8.67883516e-05]
 [1.07826605e-04]
 [1.04882749e-04]]

	( EPOCH 4251 of 7000 )
h_ip:
 [[0.59766791 1.49531268 0.66250972]
 [0.5641378

 [[0.59560604 1.49460723 0.66135973]
 [0.56303587 1.11380795 0.4202371 ]
 [0.57825781 1.27377945 0.62027914]]
Output:
 [[8.58815842e-05]
 [1.06788107e-04]
 [1.03770219e-04]]

	( EPOCH 4290 of 7000 )
h_ip:
 [[0.59555197 1.49458875 0.66132958]
 [0.56300697 1.11379807 0.42022097]
 [0.57820466 1.27376126 0.62024964]]
Output:
 [[8.58585535e-05]
 [1.06761730e-04]
 [1.03741965e-04]]

	( EPOCH 4291 of 7000 )
h_ip:
 [[0.5954979  1.49457027 0.66129943]
 [0.56297807 1.11378819 0.42020485]
 [0.57815151 1.27374308 0.62022014]]
Output:
 [[8.58355337e-05]
 [1.06735366e-04]
 [1.03713723e-04]]

	( EPOCH 4292 of 7000 )
h_ip:
 [[0.59544384 1.49455179 0.66126928]
 [0.56294918 1.11377832 0.42018873]
 [0.57809838 1.27372491 0.62019065]]
Output:
 [[8.58125247e-05]
 [1.06709013e-04]
 [1.03685495e-04]]

	( EPOCH 4293 of 7000 )
h_ip:
 [[0.5953898  1.49453332 0.66123915]
 [0.56292029 1.11376845 0.42017261]
 [0.57804525 1.27370673 0.62016117]]
Output:
 [[8.57895266e-05]
 [1.06682674e-04]
 [1.03657281e-04]]

	( EP

Output:
 [[8.31717660e-05]
 [1.03684363e-04]
 [1.00446420e-04]]

	( EPOCH 4411 of 7000 )
h_ip:
 [[0.5890774  1.49238157 0.65772066]
 [0.55954651 1.11261852 0.418291  ]
 [0.57184038 1.27158992 0.61671897]]
Output:
 [[8.31499994e-05]
 [1.03659430e-04]
 [1.00419727e-04]]

	( EPOCH 4412 of 7000 )
h_ip:
 [[0.58902444 1.49236357 0.65769116]
 [0.55951821 1.1126089  0.41827522]
 [0.57178833 1.27157221 0.61669011]]
Output:
 [[8.31282428e-05]
 [1.03634509e-04]
 [1.00393047e-04]]

	( EPOCH 4413 of 7000 )
h_ip:
 [[0.5889715  1.49234557 0.65766166]
 [0.55948991 1.11259928 0.41825945]
 [0.57173629 1.27155451 0.61666126]]
Output:
 [[8.31064962e-05]
 [1.03609599e-04]
 [1.00366379e-04]]

	( EPOCH 4414 of 7000 )
h_ip:
 [[0.58891857 1.49232758 0.65763217]
 [0.55946162 1.11258967 0.41824368]
 [0.57168426 1.2715368  0.61663241]]
Output:
 [[8.30847596e-05]
 [1.03584701e-04]
 [1.00339723e-04]]

	( EPOCH 4415 of 7000 )
h_ip:
 [[0.58886564 1.49230959 0.65760269]
 [0.55943334 1.11258005 0.41822791]
 [0.57163224

 [[0.58628328 1.49143277 0.65616428]
 [0.55805314 1.11211146 0.41745868]
 [0.56909385 1.27065656 0.61519637]]
Output:
 [[8.20105410e-05]
 [1.02354190e-04]
 [9.90225258e-05]]

	( EPOCH 4465 of 7000 )
h_ip:
 [[0.5862308  1.49141497 0.65613505]
 [0.55802509 1.11210195 0.41744305]
 [0.56904227 1.27063905 0.61516778]]
Output:
 [[8.19893059e-05]
 [1.02329864e-04]
 [9.89964898e-05]]

	( EPOCH 4466 of 7000 )
h_ip:
 [[0.58617833 1.49139718 0.65610583]
 [0.55799705 1.11209244 0.41742742]
 [0.56899069 1.27062155 0.6151392 ]]
Output:
 [[8.19680805e-05]
 [1.02305550e-04]
 [9.89704659e-05]]

	( EPOCH 4467 of 7000 )
h_ip:
 [[0.58612587 1.49137939 0.65607661]
 [0.55796901 1.11208293 0.4174118 ]
 [0.56893912 1.27060405 0.61511061]]
Output:
 [[8.19468647e-05]
 [1.02281246e-04]
 [9.89444538e-05]]

	( EPOCH 4468 of 7000 )
h_ip:
 [[0.58607341 1.4913616  0.6560474 ]
 [0.55794097 1.11207343 0.41739617]
 [0.56888756 1.27058655 0.61508204]]
Output:
 [[8.19256587e-05]
 [1.02256954e-04]
 [9.89184537e-05]]

	( EP


	( EPOCH 4592 of 7000 )
h_ip:
 [[0.57963644 1.48918469 0.65246452]
 [0.55450062 1.11091004 0.41548011]
 [0.56256022 1.26844516 0.61157701]]
Output:
 [[7.93688638e-05]
 [9.93277804e-05]
 [9.57843213e-05]]

	( EPOCH 4593 of 7000 )
h_ip:
 [[0.57958506 1.48916737 0.65243594]
 [0.55447316 1.11090078 0.41546483]
 [0.56250971 1.26842811 0.61154905]]
Output:
 [[7.93488153e-05]
 [9.93048097e-05]
 [9.57597511e-05]]

	( EPOCH 4594 of 7000 )
h_ip:
 [[0.5795337  1.48915004 0.65240736]
 [0.5544457  1.11089153 0.41544954]
 [0.56245922 1.26841107 0.6115211 ]]
Output:
 [[7.93287757e-05]
 [9.92818492e-05]
 [9.57351919e-05]]

	( EPOCH 4595 of 7000 )
h_ip:
 [[0.57948234 1.48913272 0.65237879]
 [0.55441825 1.11088227 0.41543426]
 [0.56240873 1.26839403 0.61149315]]
Output:
 [[7.93087450e-05]
 [9.92588988e-05]
 [9.57106436e-05]]

	( EPOCH 4596 of 7000 )
h_ip:
 [[0.57943098 1.48911541 0.65235022]
 [0.5543908  1.11087302 0.41541899]
 [0.56235825 1.268377   0.6114652 ]]
Output:
 [[7.92887231e-05]
 [9.92359585

 [0.56009526 1.26761412 0.61021255]]
Output:
 [[7.83968309e-05]
 [9.82140234e-05]
 [9.45931575e-05]]

	( EPOCH 4642 of 7000 )
h_ip:
 [[0.57707781 1.48832269 0.65104137]
 [0.55313311 1.11044937 0.41471904]
 [0.56004516 1.26759725 0.61018483]]
Output:
 [[7.83772111e-05]
 [9.81915420e-05]
 [9.45691167e-05]]

	( EPOCH 4643 of 7000 )
h_ip:
 [[0.57702685 1.48830554 0.65101303]
 [0.55310587 1.1104402  0.41470388]
 [0.55999506 1.26758038 0.6101571 ]]
Output:
 [[7.83575999e-05]
 [9.81690704e-05]
 [9.45450866e-05]]

	( EPOCH 4644 of 7000 )
h_ip:
 [[0.5769759  1.48828839 0.6509847 ]
 [0.55307864 1.11043104 0.41468873]
 [0.55994498 1.26756351 0.61012939]]
Output:
 [[7.83379973e-05]
 [9.81466087e-05]
 [9.45210671e-05]]

	( EPOCH 4645 of 7000 )
h_ip:
 [[0.57692496 1.48827125 0.65095637]
 [0.55305141 1.11042188 0.41467358]
 [0.5598949  1.26754665 0.61010167]]
Output:
 [[7.83184033e-05]
 [9.81241568e-05]
 [9.44970583e-05]]

	( EPOCH 4646 of 7000 )
h_ip:
 [[0.57687402 1.48825411 0.65092804]
 [0.5530241

	( EPOCH 4803 of 7000 )
h_ip:
 [[0.5689775  1.485606   0.64653981]
 [0.54880375 1.1089975  0.41231167]
 [0.55208278 1.26492511 0.60578133]]
Output:
 [[7.53269681e-05]
 [9.46958973e-05]
 [9.08325947e-05]]

	( EPOCH 4804 of 7000 )
h_ip:
 [[0.56892783 1.4855894  0.64651223]
 [0.5487772  1.10898863 0.41229692]
 [0.55203395 1.26490879 0.60575435]]
Output:
 [[7.53086739e-05]
 [9.46749285e-05]
 [9.08101908e-05]]

	( EPOCH 4805 of 7000 )
h_ip:
 [[0.56887817 1.4855728  0.64648465]
 [0.54875066 1.10897976 0.41228217]
 [0.55198514 1.26489246 0.60572737]]
Output:
 [[7.52903876e-05]
 [9.46539685e-05]
 [9.07877966e-05]]

	( EPOCH 4806 of 7000 )
h_ip:
 [[0.56882852 1.48555621 0.64645708]
 [0.54872412 1.10897089 0.41226742]
 [0.55193633 1.26487614 0.6057004 ]]
Output:
 [[7.52721090e-05]
 [9.46330174e-05]
 [9.07654119e-05]]

	( EPOCH 4807 of 7000 )
h_ip:
 [[0.56877887 1.48553962 0.64642951]
 [0.54869759 1.10896202 0.41225268]
 [0.55188753 1.26485982 0.60567343]]
Output:
 [[7.52538382e-05]
 [9.46120752e

 [8.99218421e-05]]

	( EPOCH 4845 of 7000 )
h_ip:
 [[0.5668981  1.48491163 0.64538523]
 [0.54769237 1.10862641 0.41169421]
 [0.55003878 1.26424216 0.60465194]]
Output:
 [[7.45652522e-05]
 [9.38227762e-05]
 [8.98998268e-05]]

	( EPOCH 4846 of 7000 )
h_ip:
 [[0.56684876 1.48489517 0.64535784]
 [0.547666   1.10861761 0.41167956]
 [0.54999028 1.26422597 0.60462514]]
Output:
 [[7.45472804e-05]
 [9.38021750e-05]
 [8.98778209e-05]]

	( EPOCH 4847 of 7000 )
h_ip:
 [[0.56679942 1.48487871 0.64533045]
 [0.54763963 1.10860881 0.41166492]
 [0.54994179 1.26420978 0.60459835]]
Output:
 [[7.45293162e-05]
 [9.37815824e-05]
 [8.98558243e-05]]

	( EPOCH 4848 of 7000 )
h_ip:
 [[0.56675009 1.48486225 0.64530307]
 [0.54761327 1.10860002 0.41165027]
 [0.5498933  1.26419359 0.60457157]]
Output:
 [[7.45113595e-05]
 [9.37609984e-05]
 [8.98338371e-05]]

	( EPOCH 4849 of 7000 )
h_ip:
 [[0.56670077 1.4848458  0.64527569]
 [0.54758691 1.10859122 0.41163563]
 [0.54984482 1.26417741 0.60454478]]
Output:
 [[7.4493410

 [8.71154255e-05]]

	( EPOCH 4976 of 7000 )
h_ip:
 [[0.56049859 1.48278236 0.64183459]
 [0.54427204 1.10748845 0.40979537]
 [0.54374825 1.26214799 0.60117883]]
Output:
 [[7.22737694e-05]
 [9.11956521e-05]
 [8.70945880e-05]]

	( EPOCH 4977 of 7000 )
h_ip:
 [[0.56045023 1.48276631 0.64180778]
 [0.54424619 1.10747988 0.40978103]
 [0.54370071 1.26213221 0.6011526 ]]
Output:
 [[7.22567513e-05]
 [9.11761383e-05]
 [8.70737592e-05]]

	( EPOCH 4978 of 7000 )
h_ip:
 [[0.56040188 1.48275027 0.64178097]
 [0.54422035 1.10747131 0.40976669]
 [0.54365318 1.26211643 0.60112638]]
Output:
 [[7.22397403e-05]
 [9.11566325e-05]
 [8.70529390e-05]]

	( EPOCH 4979 of 7000 )
h_ip:
 [[0.56035354 1.48273423 0.64175416]
 [0.54419451 1.10746273 0.40975235]
 [0.54360566 1.26210066 0.60110016]]
Output:
 [[7.22227362e-05]
 [9.11371347e-05]
 [8.70321274e-05]]

	( EPOCH 4980 of 7000 )
h_ip:
 [[0.5603052  1.48271819 0.64172736]
 [0.54416867 1.10745416 0.40973802]
 [0.54355815 1.26208489 0.60107394]]
Output:
 [[7.2205739

 [[0.55852188 1.48212701 0.64073868]
 [0.54321554 1.10713821 0.40920929]
 [0.5418052  1.26150347 0.60010688]]
Output:
 [[7.15817198e-05]
 [9.04020748e-05]
 [8.62476282e-05]]

	( EPOCH 5018 of 7000 )
h_ip:
 [[0.55847382 1.48211109 0.64071204]
 [0.54318986 1.10712971 0.40919504]
 [0.54175796 1.26148782 0.60008082]]
Output:
 [[7.15649851e-05]
 [9.03828840e-05]
 [8.62271490e-05]]

	( EPOCH 5019 of 7000 )
h_ip:
 [[0.55842577 1.48209517 0.64068541]
 [0.54316418 1.1071212  0.40918079]
 [0.54171072 1.26147216 0.60005477]]
Output:
 [[7.15482572e-05]
 [9.03637010e-05]
 [8.62066782e-05]]

	( EPOCH 5020 of 7000 )
h_ip:
 [[0.55837772 1.48207926 0.64065877]
 [0.5431385  1.10711269 0.40916655]
 [0.54166349 1.26145651 0.60002872]]
Output:
 [[7.15315362e-05]
 [9.03445258e-05]
 [8.61862159e-05]]

	( EPOCH 5021 of 7000 )
h_ip:
 [[0.55832968 1.48206335 0.64063215]
 [0.54311282 1.10710419 0.40915231]
 [0.54161628 1.26144086 0.60000268]]
Output:
 [[7.15148219e-05]
 [9.03253583e-05]
 [8.61657619e-05]]

	( EP

 [[6.96211670e-05]
 [8.81534436e-05]
 [8.38488682e-05]]

	( EPOCH 5138 of 7000 )
h_ip:
 [[0.5527586  1.48022261 0.63754576]
 [0.54013525 1.10612043 0.40750173]
 [0.53614007 1.25963061 0.59698384]]
Output:
 [[6.96052232e-05]
 [8.81351540e-05]
 [8.38293646e-05]]

	( EPOCH 5139 of 7000 )
h_ip:
 [[0.5527114  1.48020705 0.63751962]
 [0.54011003 1.10611212 0.40748776]
 [0.53609368 1.25961531 0.59695828]]
Output:
 [[6.95892856e-05]
 [8.81168717e-05]
 [8.38098690e-05]]

	( EPOCH 5140 of 7000 )
h_ip:
 [[0.55266421 1.4801915  0.63749349]
 [0.5400848  1.1061038  0.40747378]
 [0.53604729 1.25960002 0.59693272]]
Output:
 [[6.95733545e-05]
 [8.80985967e-05]
 [8.37903811e-05]]

	( EPOCH 5141 of 7000 )
h_ip:
 [[0.55261702 1.48017595 0.63746737]
 [0.54005959 1.10609549 0.40745981]
 [0.53600091 1.25958472 0.59690716]]
Output:
 [[6.95574296e-05]
 [8.80803288e-05]
 [8.37709011e-05]]

	( EPOCH 5142 of 7000 )
h_ip:
 [[0.55256985 1.4801604  0.63744124]
 [0.54003437 1.10608718 0.40744584]
 [0.53595453 1.25956

 [8.29406084e-05]]

	( EPOCH 5185 of 7000 )
h_ip:
 [[0.5505477  1.47949455 0.63632182]
 [0.5389536  1.10573132 0.40684718]
 [0.53396683 1.25891463 0.59578672]]
Output:
 [[6.88629705e-05]
 [8.72836456e-05]
 [8.29214687e-05]]

	( EPOCH 5186 of 7000 )
h_ip:
 [[0.55050083 1.47947913 0.63629588]
 [0.53892854 1.10572308 0.40683331]
 [0.53392075 1.25889947 0.59576134]]
Output:
 [[6.88473278e-05]
 [8.72656992e-05]
 [8.29023366e-05]]

	( EPOCH 5187 of 7000 )
h_ip:
 [[0.55045396 1.47946371 0.63626994]
 [0.53890349 1.10571484 0.40681943]
 [0.53387468 1.25888431 0.59573597]]
Output:
 [[6.88316912e-05]
 [8.72477597e-05]
 [8.28832121e-05]]

	( EPOCH 5188 of 7000 )
h_ip:
 [[0.5504071  1.47944829 0.636244  ]
 [0.53887845 1.1057066  0.40680556]
 [0.53382862 1.25886915 0.59571061]]
Output:
 [[6.88160608e-05]
 [8.72298273e-05]
 [8.28640953e-05]]

	( EPOCH 5189 of 7000 )
h_ip:
 [[0.55036024 1.47943288 0.63621807]
 [0.53885341 1.10569837 0.40679169]
 [0.53378256 1.25885399 0.59568524]]
Output:
 [[6.8800436

 [[6.69991767e-05]
 [8.51450055e-05]
 [8.06423849e-05]]

	( EPOCH 5308 of 7000 )
h_ip:
 [[0.54483288 1.47761901 0.63316058]
 [0.5358992  1.10472896 0.40515656]
 [0.52834935 1.25707031 0.59269482]]
Output:
 [[6.69842629e-05]
 [8.51278894e-05]
 [8.06241519e-05]]

	( EPOCH 5309 of 7000 )
h_ip:
 [[0.54478683 1.47760394 0.63313512]
 [0.53587459 1.1047209  0.40514295]
 [0.52830409 1.25705548 0.59266992]]
Output:
 [[6.69693550e-05]
 [8.51107799e-05]
 [8.06059259e-05]]

	( EPOCH 5310 of 7000 )
h_ip:
 [[0.54474079 1.47758887 0.63310967]
 [0.53584998 1.10471285 0.40512934]
 [0.52825883 1.25704066 0.59264503]]
Output:
 [[6.69544528e-05]
 [8.50936770e-05]
 [8.05877071e-05]]

	( EPOCH 5311 of 7000 )
h_ip:
 [[0.54469475 1.4775738  0.63308422]
 [0.53582538 1.10470479 0.40511572]
 [0.52821358 1.25702585 0.59262014]]
Output:
 [[6.69395564e-05]
 [8.50765806e-05]
 [8.05694955e-05]]

	( EPOCH 5312 of 7000 )
h_ip:
 [[0.54464872 1.47755873 0.63305877]
 [0.53580078 1.10469674 0.40510212]
 [0.52816834 1.25701

 [[6.62312427e-05]
 [8.42636013e-05]
 [7.97036128e-05]]

	( EPOCH 5360 of 7000 )
h_ip:
 [[0.54244709 1.47683875 0.63184191]
 [0.53462407 1.10431195 0.40445134]
 [0.52600421 1.25630307 0.59140511]]
Output:
 [[6.62166247e-05]
 [8.42468221e-05]
 [7.96857444e-05]]

	( EPOCH 5361 of 7000 )
h_ip:
 [[0.54240138 1.47682382 0.63181665]
 [0.53459964 1.10430397 0.40443783]
 [0.52595928 1.25628838 0.59138041]]
Output:
 [[6.62020124e-05]
 [8.42300492e-05]
 [7.96678829e-05]]

	( EPOCH 5362 of 7000 )
h_ip:
 [[0.54235568 1.47680889 0.6317914 ]
 [0.53457521 1.10429599 0.40442433]
 [0.52591436 1.2562737  0.59135571]]
Output:
 [[6.61874056e-05]
 [8.42132827e-05]
 [7.96500284e-05]]

	( EPOCH 5363 of 7000 )
h_ip:
 [[0.54230998 1.47679396 0.63176615]
 [0.53455079 1.10428802 0.40441082]
 [0.52586944 1.25625902 0.59133102]]
Output:
 [[6.61728045e-05]
 [8.41965226e-05]
 [7.96321807e-05]]

	( EPOCH 5364 of 7000 )
h_ip:
 [[0.5422643  1.47677904 0.6317409 ]
 [0.53452637 1.10428004 0.40439732]
 [0.52582453 1.25624

h_ip:
 [[0.53696297 1.47505129 0.62881316]
 [0.53169298 1.10335665 0.40283157]
 [0.52061354 1.25454549 0.58844296]]
Output:
 [[6.44883083e-05]
 [8.22625941e-05]
 [7.75735460e-05]]

	( EPOCH 5482 of 7000 )
h_ip:
 [[0.53691803 1.47503668 0.62878836]
 [0.53166896 1.10334884 0.4028183 ]
 [0.52056937 1.25453112 0.5884187 ]]
Output:
 [[6.44743516e-05]
 [8.22465677e-05]
 [7.75564927e-05]]

	( EPOCH 5483 of 7000 )
h_ip:
 [[0.5368731  1.47502207 0.62876356]
 [0.53164494 1.10334103 0.40280504]
 [0.5205252  1.25451675 0.58839445]]
Output:
 [[6.44604001e-05]
 [8.22305472e-05]
 [7.75394459e-05]]

	( EPOCH 5484 of 7000 )
h_ip:
 [[0.53682817 1.47500746 0.62873876]
 [0.53162093 1.10333322 0.40279178]
 [0.52048104 1.25450239 0.5883702 ]]
Output:
 [[6.44464538e-05]
 [8.22145327e-05]
 [7.75224055e-05]]

	( EPOCH 5485 of 7000 )
h_ip:
 [[0.53678326 1.47499286 0.62871397]
 [0.53159692 1.10332542 0.40277852]
 [0.52043689 1.25448803 0.58834595]]
Output:
 [[6.44325128e-05]
 [8.21985241e-05]
 [7.75053716e-05]]


	( EPOCH 5525 of 7000 )
h_ip:
 [[0.53499161 1.47441082 0.62772526]
 [0.53063934 1.10301435 0.40224976]
 [0.51867577 1.25391575 0.58737901]]
Output:
 [[6.38791295e-05]
 [8.15630282e-05]
 [7.68292631e-05]]

	( EPOCH 5526 of 7000 )
h_ip:
 [[0.53494694 1.47439632 0.62770062]
 [0.53061547 1.1030066  0.40223658]
 [0.51863187 1.2539015  0.58735491]]
Output:
 [[6.38654006e-05]
 [8.15472610e-05]
 [7.68124906e-05]]

	( EPOCH 5527 of 7000 )
h_ip:
 [[0.53490228 1.47438183 0.62767598]
 [0.5305916  1.10299885 0.4022234 ]
 [0.51858797 1.25388724 0.58733082]]
Output:
 [[6.38516767e-05]
 [8.15314997e-05]
 [7.67957244e-05]]

	( EPOCH 5528 of 7000 )
h_ip:
 [[0.53485763 1.47436733 0.62765135]
 [0.53056774 1.10299111 0.40221023]
 [0.51854408 1.25387299 0.58730672]]
Output:
 [[6.38379580e-05]
 [8.15157442e-05]
 [7.67789645e-05]]

	( EPOCH 5529 of 7000 )
h_ip:
 [[0.53481299 1.47435284 0.62762672]
 [0.53054388 1.10298336 0.40219706]
 [0.5185002  1.25385875 0.58728263]]
Output:
 [[6.38242444e-05]
 [8.14999945e

	( EPOCH 5651 of 7000 )
h_ip:
 [[0.52941183 1.47260395 0.62464854]
 [0.52765712 1.10204866 0.40060432]
 [0.51319112 1.25213924 0.58437009]]
Output:
 [[6.21886769e-05]
 [7.96212023e-05]
 [7.47644702e-05]]

	( EPOCH 5652 of 7000 )
h_ip:
 [[0.52936793 1.47258977 0.62462434]
 [0.52763366 1.10204108 0.40059138]
 [0.51314796 1.25212529 0.58434643]]
Output:
 [[6.21755712e-05]
 [7.96061444e-05]
 [7.47484656e-05]]

	( EPOCH 5653 of 7000 )
h_ip:
 [[0.52932404 1.47257559 0.62460015]
 [0.5276102  1.1020335  0.40057844]
 [0.51310482 1.25211135 0.58432278]]
Output:
 [[6.21624702e-05]
 [7.95910919e-05]
 [7.47324669e-05]]

	( EPOCH 5654 of 7000 )
h_ip:
 [[0.52928014 1.47256141 0.62457597]
 [0.52758674 1.10202592 0.40056551]
 [0.51306167 1.25209741 0.58429912]]
Output:
 [[6.21493741e-05]
 [7.95760449e-05]
 [7.47164741e-05]]

	( EPOCH 5655 of 7000 )
h_ip:
 [[0.52923626 1.47254724 0.62455178]
 [0.52756328 1.10201835 0.40055257]
 [0.51301854 1.25208348 0.58427547]]
Output:
 [[6.21362827e-05]
 [7.95610033e

h_ip:
 [[0.52748572 1.47198226 0.62358732]
 [0.52662768 1.10171639 0.40003678]
 [0.51129785 1.25152801 0.5833323 ]]
Output:
 [[6.16165139e-05]
 [7.89637629e-05]
 [7.40657988e-05]]

	( EPOCH 5696 of 7000 )
h_ip:
 [[0.52744208 1.47196818 0.62356328]
 [0.52660435 1.10170887 0.40002392]
 [0.51125495 1.25151417 0.58330879]]
Output:
 [[6.16036161e-05]
 [7.89489416e-05]
 [7.40500504e-05]]

	( EPOCH 5697 of 7000 )
h_ip:
 [[0.52739844 1.47195411 0.62353924]
 [0.52658103 1.10170135 0.40001106]
 [0.51121206 1.25150034 0.58328528]]
Output:
 [[6.15907230e-05]
 [7.89341257e-05]
 [7.40343078e-05]]

	( EPOCH 5698 of 7000 )
h_ip:
 [[0.52735481 1.47194004 0.62351521]
 [0.52655771 1.10169383 0.39999821]
 [0.51116917 1.2514865  0.58326178]]
Output:
 [[6.15778346e-05]
 [7.89193150e-05]
 [7.40185709e-05]]

	( EPOCH 5699 of 7000 )
h_ip:
 [[0.52731119 1.47192597 0.62349118]
 [0.52653439 1.10168631 0.39998536]
 [0.51112629 1.25147267 0.58323828]]
Output:
 [[6.15649508e-05]
 [7.89045097e-05]
 [7.40028398e-05]]


 [0.50589524 1.2497895  0.58037334]]
Output:
 [[6.00150615e-05]
 [7.71230613e-05]
 [7.21107922e-05]]

	( EPOCH 5823 of 7000 )
h_ip:
 [[0.52194646 1.47020013 0.62053791]
 [0.52366711 1.10076392 0.39840593]
 [0.50585306 1.24977596 0.58035025]]
Output:
 [[6.00027377e-05]
 [7.71088930e-05]
 [7.20957508e-05]]

	( EPOCH 5824 of 7000 )
h_ip:
 [[0.52190356 1.47018635 0.6205143 ]
 [0.52364417 1.10075656 0.3983933 ]
 [0.50581088 1.24976242 0.58032716]]
Output:
 [[5.99904183e-05]
 [7.70947297e-05]
 [7.20807148e-05]]

	( EPOCH 5825 of 7000 )
h_ip:
 [[0.52186066 1.47017259 0.6204907 ]
 [0.52362124 1.1007492  0.39838068]
 [0.50576871 1.24974889 0.58030408]]
Output:
 [[5.99781033e-05]
 [7.70805714e-05]
 [7.20656842e-05]]

	( EPOCH 5826 of 7000 )
h_ip:
 [[0.52181776 1.47015882 0.6204671 ]
 [0.52359832 1.10074184 0.39836806]
 [0.50572655 1.24973535 0.58028101]]
Output:
 [[5.99657926e-05]
 [7.70664181e-05]
 [7.20506590e-05]]

	( EPOCH 5827 of 7000 )
h_ip:
 [[0.52177487 1.47014506 0.6204435 ]
 [0.5235753

 [7.14540271e-05]]

	( EPOCH 5867 of 7000 )
h_ip:
 [[0.52006387 1.4695964  0.61950238]
 [0.52266092 1.10044125 0.39785212]
 [0.50400258 1.24918245 0.57933763]]
Output:
 [[5.94647877e-05]
 [7.64903763e-05]
 [7.14392199e-05]]

	( EPOCH 5868 of 7000 )
h_ip:
 [[0.52002121 1.46958273 0.61947892]
 [0.52263811 1.10043394 0.39783957]
 [0.50396065 1.24916901 0.57931469]]
Output:
 [[5.94526585e-05]
 [7.64764293e-05]
 [7.14244181e-05]]

	( EPOCH 5869 of 7000 )
h_ip:
 [[0.51997856 1.46956906 0.61945546]
 [0.52261532 1.10042664 0.39782703]
 [0.50391872 1.24915558 0.57929175]]
Output:
 [[5.94405335e-05]
 [7.64624871e-05]
 [7.14096214e-05]]

	( EPOCH 5870 of 7000 )
h_ip:
 [[0.51993591 1.4695554  0.61943201]
 [0.52259252 1.10041933 0.39781449]
 [0.5038768  1.24914214 0.57926881]]
Output:
 [[5.94284127e-05]
 [7.64485498e-05]
 [7.13948301e-05]]

	( EPOCH 5871 of 7000 )
h_ip:
 [[0.51989326 1.46954174 0.61940856]
 [0.52256973 1.10041203 0.39780194]
 [0.50383489 1.24912871 0.57924588]]
Output:
 [[5.9416296

h_ip:
 [[0.51473203 1.4678919  0.61657199]
 [0.5198112  1.09953026 0.39628492]
 [0.49876173 1.24750686 0.57647213]]
Output:
 [[5.79694389e-05]
 [7.47705142e-05]
 [6.96147402e-05]]

	( EPOCH 5994 of 7000 )
h_ip:
 [[0.51469006 1.46787852 0.61654894]
 [0.51978877 1.0995231  0.39627259]
 [0.49872047 1.24749371 0.57644959]]
Output:
 [[5.79578311e-05]
 [7.47571602e-05]
 [6.96005804e-05]]

	( EPOCH 5995 of 7000 )
h_ip:
 [[0.5146481  1.46786514 0.61652589]
 [0.51976634 1.09951595 0.39626026]
 [0.49867922 1.24748055 0.57642705]]
Output:
 [[5.79462273e-05]
 [7.47438108e-05]
 [6.95864254e-05]]

	( EPOCH 5996 of 7000 )
h_ip:
 [[0.51460614 1.46785175 0.61650284]
 [0.51974391 1.0995088  0.39624794]
 [0.49863798 1.2474674  0.57640452]]
Output:
 [[5.79346274e-05]
 [7.47304659e-05]
 [6.95722754e-05]]

	( EPOCH 5997 of 7000 )
h_ip:
 [[0.51456418 1.46783837 0.6164798 ]
 [0.51972149 1.09950165 0.39623561]
 [0.49859674 1.24745424 0.57638198]]
Output:
 [[5.79230316e-05]
 [7.47171256e-05]
 [6.95581303e-05]]



	( EPOCH 6038 of 7000 )
h_ip:
 [[0.51284865 1.46729171 0.61553774]
 [0.51880459 1.09920948 0.39573179]
 [0.49691049 1.24691688 0.57546082]]
Output:
 [[5.74510252e-05]
 [7.41740631e-05]
 [6.89823938e-05]]

	( EPOCH 6039 of 7000 )
h_ip:
 [[0.51280692 1.46727843 0.61551483]
 [0.51878228 1.09920237 0.39571954]
 [0.49686947 1.24690382 0.57543841]]
Output:
 [[5.74395957e-05]
 [7.41609119e-05]
 [6.89684535e-05]]

	( EPOCH 6040 of 7000 )
h_ip:
 [[0.51276519 1.46726514 0.61549192]
 [0.51875998 1.09919527 0.39570729]
 [0.49682846 1.24689076 0.57541601]]
Output:
 [[5.74281701e-05]
 [7.41477651e-05]
 [6.89545179e-05]]

	( EPOCH 6041 of 7000 )
h_ip:
 [[0.51272347 1.46725186 0.61546901]
 [0.51873768 1.09918817 0.39569504]
 [0.49678745 1.2468777  0.57539362]]
Output:
 [[5.74167485e-05]
 [7.41346228e-05]
 [6.89405872e-05]]

	( EPOCH 6042 of 7000 )
h_ip:
 [[0.51268176 1.46723858 0.61544611]
 [0.51871539 1.09918108 0.39568279]
 [0.49674645 1.24686465 0.57537122]]
Output:
 [[5.74053308e-05]
 [7.41214850


	( EPOCH 6171 of 7000 )
h_ip:
 [[0.50734453 1.46554334 0.61251781]
 [0.51586279 1.09827502 0.39411669]
 [0.49150035 1.2451983  0.57250793]]
Output:
 [[5.59645648e-05]
 [7.24632257e-05]
 [6.71697550e-05]]

	( EPOCH 6172 of 7000 )
h_ip:
 [[0.50730349 1.46553034 0.61249531]
 [0.51584086 1.09826807 0.39410466]
 [0.49146002 1.24518552 0.57248593]]
Output:
 [[5.59536398e-05]
 [7.24506480e-05]
 [6.71564355e-05]]

	( EPOCH 6173 of 7000 )
h_ip:
 [[0.50726246 1.46551733 0.61247281]
 [0.51581893 1.09826112 0.39409262]
 [0.49141969 1.24517274 0.57246393]]
Output:
 [[5.59427184e-05]
 [7.24380746e-05]
 [6.71431205e-05]]

	( EPOCH 6174 of 7000 )
h_ip:
 [[0.50722143 1.46550433 0.61245031]
 [0.515797   1.09825418 0.39408059]
 [0.49137936 1.24515996 0.57244194]]
Output:
 [[5.59318008e-05]
 [7.24255052e-05]
 [6.71298100e-05]]

	( EPOCH 6175 of 7000 )
h_ip:
 [[0.50718041 1.46549134 0.61242782]
 [0.51577507 1.09824723 0.39406856]
 [0.49133904 1.24514719 0.57241994]]
Output:
 [[5.59208867e-05]
 [7.24129401

 [[5.54442723e-05]
 [7.18641689e-05]
 [6.65354730e-05]]

	( EPOCH 6220 of 7000 )
h_ip:
 [[0.50533969 1.4649086  0.6114188 ]
 [0.51479126 1.09793577 0.39352892]
 [0.48952976 1.24457441 0.57143336]]
Output:
 [[5.54335214e-05]
 [7.18517892e-05]
 [6.65223678e-05]]

	( EPOCH 6221 of 7000 )
h_ip:
 [[0.5052989  1.4648957  0.61139645]
 [0.51476946 1.09792887 0.39351697]
 [0.48948967 1.24456172 0.5714115 ]]
Output:
 [[5.54227741e-05]
 [7.18394136e-05]
 [6.65092669e-05]]

	( EPOCH 6222 of 7000 )
h_ip:
 [[0.50525812 1.4648828  0.6113741 ]
 [0.51474766 1.09792198 0.39350502]
 [0.48944958 1.24454904 0.57138965]]
Output:
 [[5.54120304e-05]
 [7.18270421e-05]
 [6.64961705e-05]]

	( EPOCH 6223 of 7000 )
h_ip:
 [[0.50521734 1.4648699  0.61135175]
 [0.51472587 1.09791509 0.39349306]
 [0.4894095  1.24453637 0.57136779]]
Output:
 [[5.54012902e-05]
 [7.18146746e-05]
 [6.64830784e-05]]

	( EPOCH 6224 of 7000 )
h_ip:
 [[0.50517657 1.464857   0.6113294 ]
 [0.51470408 1.09790819 0.39348111]
 [0.48936943 1.24452


	( EPOCH 6348 of 7000 )
h_ip:
 [[0.50015936 1.46327364 0.60858153]
 [0.51202252 1.09706192 0.39201151]
 [0.48443795 1.24296745 0.56865924]]
Output:
 [[5.40864116e-05]
 [7.03001559e-05]
 [6.48805736e-05]]

	( EPOCH 6349 of 7000 )
h_ip:
 [[0.50011921 1.46326099 0.60855955]
 [0.51200106 1.09705517 0.39199975]
 [0.48439848 1.24295503 0.56863776]]
Output:
 [[5.40761093e-05]
 [7.02882860e-05]
 [6.48680201e-05]]

	( EPOCH 6350 of 7000 )
h_ip:
 [[0.50007906 1.46324835 0.60853758]
 [0.5119796  1.09704841 0.391988  ]
 [0.48435902 1.2429426  0.56861627]]
Output:
 [[5.40658103e-05]
 [7.02764199e-05]
 [6.48554707e-05]]

	( EPOCH 6351 of 7000 )
h_ip:
 [[0.50003891 1.46323571 0.60851561]
 [0.51195814 1.09704165 0.39197625]
 [0.48431956 1.24293018 0.56859479]]
Output:
 [[5.40555147e-05]
 [7.02645577e-05]
 [6.48429254e-05]]

	( EPOCH 6352 of 7000 )
h_ip:
 [[0.49999878 1.46322308 0.60849364]
 [0.51193669 1.0970349  0.3919645 ]
 [0.48428011 1.24291776 0.56857331]]
Output:
 [[5.40452224e-05]
 [7.02526993

	( EPOCH 6390 of 7000 )
h_ip:
 [[0.49847711 1.46274431 0.60766094]
 [0.5111234  1.09677901 0.39151916]
 [0.48278446 1.24244721 0.56775917]]
Output:
 [[5.36565957e-05]
 [6.98048977e-05]
 [6.43568717e-05]]

	( EPOCH 6391 of 7000 )
h_ip:
 [[0.49843716 1.46273174 0.60763909]
 [0.51110205 1.09677229 0.39150747]
 [0.48274519 1.24243486 0.5677378 ]]
Output:
 [[5.36464335e-05]
 [6.97931872e-05]
 [6.43444906e-05]]

	( EPOCH 6392 of 7000 )
h_ip:
 [[0.49839722 1.46271919 0.60761723]
 [0.5110807  1.09676558 0.39149578]
 [0.48270593 1.24242252 0.56771643]]
Output:
 [[5.36362747e-05]
 [6.97814803e-05]
 [6.43321135e-05]]

	( EPOCH 6393 of 7000 )
h_ip:
 [[0.49835728 1.46270663 0.60759538]
 [0.51105935 1.09675887 0.39148409]
 [0.48266667 1.24241018 0.56769507]]
Output:
 [[5.36261191e-05]
 [6.97697773e-05]
 [6.43197405e-05]]

	( EPOCH 6394 of 7000 )
h_ip:
 [[0.49831735 1.46269407 0.60757353]
 [0.51103801 1.09675216 0.39147241]
 [0.48262742 1.24239784 0.56767371]]
Output:
 [[5.36159668e-05]
 [6.97580780e

Output:
 [[5.24700725e-05]
 [6.84372243e-05]
 [6.29115263e-05]]

	( EPOCH 6510 of 7000 )
h_ip:
 [[0.49371728 1.46125082 0.60505826]
 [0.5085794  1.09598077 0.39012719]
 [0.47810601 1.24097942 0.56521457]]
Output:
 [[5.24602928e-05]
 [6.84259484e-05]
 [6.28996155e-05]]

	( EPOCH 6511 of 7000 )
h_ip:
 [[0.4936779  1.46123849 0.60503674]
 [0.50855835 1.09597418 0.39011568]
 [0.4780673  1.24096731 0.56519353]]
Output:
 [[5.24505162e-05]
 [6.84146760e-05]
 [6.28877085e-05]]

	( EPOCH 6512 of 7000 )
h_ip:
 [[0.49363852 1.46122616 0.60501523]
 [0.5085373  1.09596759 0.39010417]
 [0.4780286  1.24095519 0.56517249]]
Output:
 [[5.24407427e-05]
 [6.84034072e-05]
 [6.28758054e-05]]

	( EPOCH 6513 of 7000 )
h_ip:
 [[0.49359915 1.46121384 0.60499371]
 [0.50851626 1.095961   0.39009267]
 [0.47798991 1.24094308 0.56515146]]
Output:
 [[5.24309724e-05]
 [6.83921419e-05]
 [6.28639061e-05]]

	( EPOCH 6514 of 7000 )
h_ip:
 [[0.49355979 1.46120151 0.6049722 ]
 [0.50849522 1.09595441 0.39008116]
 [0.47795121


	( EPOCH 6564 of 7000 )
h_ip:
 [[0.49159744 1.4605877  0.60390014]
 [0.5074464  1.09562634 0.3895078 ]
 [0.47602244 1.24032774 0.56408232]]
Output:
 [[5.19367914e-05]
 [6.78222791e-05]
 [6.22620902e-05]]

	( EPOCH 6565 of 7000 )
h_ip:
 [[0.49155831 1.46057547 0.60387877]
 [0.50742549 1.09561981 0.38949637]
 [0.47598398 1.24031572 0.56406142]]
Output:
 [[5.19271815e-05]
 [6.78111961e-05]
 [6.22503880e-05]]

	( EPOCH 6566 of 7000 )
h_ip:
 [[0.49151919 1.46056324 0.6038574 ]
 [0.50740458 1.09561327 0.38948494]
 [0.47594552 1.24030371 0.56404053]]
Output:
 [[5.19175746e-05]
 [6.78001165e-05]
 [6.22386896e-05]]

	( EPOCH 6567 of 7000 )
h_ip:
 [[0.49148007 1.46055102 0.60383604]
 [0.50738367 1.09560674 0.38947351]
 [0.47590707 1.24029169 0.56401965]]
Output:
 [[5.19079707e-05]
 [6.77890404e-05]
 [6.22269950e-05]]

	( EPOCH 6568 of 7000 )
h_ip:
 [[0.49144095 1.46053879 0.60381467]
 [0.50736276 1.0956002  0.38946209]
 [0.47586863 1.24027968 0.56399876]]
Output:
 [[5.18983699e-05]
 [6.77779677

 [[0.4868574  1.45910941 0.6013128 ]
 [0.50491297 1.09483621 0.38812403]
 [0.47136351 1.23887501 0.56155286]]
Output:
 [[5.07864588e-05]
 [6.64952396e-05]
 [6.08615729e-05]]

	( EPOCH 6687 of 7000 )
h_ip:
 [[0.48681882 1.4590974  0.60129176]
 [0.50489235 1.0948298  0.38811277]
 [0.4713256  1.23886322 0.56153229]]
Output:
 [[5.07772104e-05]
 [6.64845674e-05]
 [6.08503153e-05]]

	( EPOCH 6688 of 7000 )
h_ip:
 [[0.48678025 1.4590854  0.60127072]
 [0.50487174 1.09482338 0.38810152]
 [0.47128769 1.23885142 0.56151172]]
Output:
 [[5.07679650e-05]
 [6.64738985e-05]
 [6.08390612e-05]]

	( EPOCH 6689 of 7000 )
h_ip:
 [[0.48674169 1.4590734  0.60124968]
 [0.50485112 1.09481697 0.38809027]
 [0.47124978 1.23883963 0.56149115]]
Output:
 [[5.07587224e-05]
 [6.64632329e-05]
 [6.08278106e-05]]

	( EPOCH 6690 of 7000 )
h_ip:
 [[0.48670312 1.4590614  0.60122865]
 [0.50483051 1.09481055 0.38807902]
 [0.47121188 1.23882784 0.56147059]]
Output:
 [[5.07494827e-05]
 [6.64525706e-05]
 [6.08165635e-05]]

	( EP

 [6.03806721e-05]]

	( EPOCH 6730 of 7000 )
h_ip:
 [[0.4851643  1.45858287 0.6003894 ]
 [0.50400805 1.09455479 0.38763017]
 [0.46969941 1.23835761 0.56065014]]
Output:
 [[5.03822412e-05]
 [6.60287427e-05]
 [6.03695653e-05]]

	( EPOCH 6731 of 7000 )
h_ip:
 [[0.48512593 1.45857095 0.60036847]
 [0.50398754 1.09454841 0.38761897]
 [0.46966168 1.23834589 0.56062968]]
Output:
 [[5.03731185e-05]
 [6.60182132e-05]
 [6.03584620e-05]]

	( EPOCH 6732 of 7000 )
h_ip:
 [[0.48508755 1.45855902 0.60034755]
 [0.50396703 1.09454204 0.38760778]
 [0.46962397 1.23833417 0.56060922]]
Output:
 [[5.03639985e-05]
 [6.60076870e-05]
 [6.03473622e-05]]

	( EPOCH 6733 of 7000 )
h_ip:
 [[0.48504918 1.4585471  0.60032663]
 [0.50394652 1.09453567 0.38759659]
 [0.46958625 1.23832245 0.56058877]]
Output:
 [[5.03548814e-05]
 [6.59971639e-05]
 [6.03362658e-05]]

	( EPOCH 6734 of 7000 )
h_ip:
 [[0.48501081 1.45853518 0.60030571]
 [0.50392602 1.0945293  0.38758541]
 [0.46954854 1.23831074 0.56056832]]
Output:
 [[5.0345767

 [5.88056877e-05]]

	( EPOCH 6875 of 7000 )
h_ip:
 [[0.47964485 1.45687186 0.59738197]
 [0.50105804 1.09364027 0.38602171]
 [0.4642745  1.23667633 0.55771016]]
Output:
 [[4.90883245e-05]
 [6.45347801e-05]
 [5.87950687e-05]]

	( EPOCH 6876 of 7000 )
h_ip:
 [[0.4796071  1.45686019 0.59736142]
 [0.50103787 1.09363403 0.38601071]
 [0.46423739 1.23666486 0.55769007]]
Output:
 [[4.90795986e-05]
 [6.45247014e-05]
 [5.87844529e-05]]

	( EPOCH 6877 of 7000 )
h_ip:
 [[0.47956936 1.45684851 0.59734087]
 [0.50101769 1.09362779 0.38599972]
 [0.46420029 1.23665339 0.55766998]]
Output:
 [[4.90708754e-05]
 [6.45146258e-05]
 [5.87738404e-05]]

	( EPOCH 6878 of 7000 )
h_ip:
 [[0.47953161 1.45683684 0.59732032]
 [0.50099752 1.09362155 0.38598873]
 [0.4641632  1.23664192 0.55764989]]
Output:
 [[4.90621548e-05]
 [6.45045532e-05]
 [5.87632311e-05]]

	( EPOCH 6879 of 7000 )
h_ip:
 [[0.47949388 1.45682518 0.59729977]
 [0.50097735 1.09361531 0.38597774]
 [0.46412611 1.23663046 0.5576298 ]]
Output:
 [[4.9053436

 [0.46271975 1.23619602 0.55686839]]
Output:
 [[4.87241045e-05]
 [6.41140532e-05]
 [5.83519921e-05]]

	( EPOCH 6918 of 7000 )
h_ip:
 [[0.47802543 1.45637143 0.59650042]
 [0.5001925  1.09337279 0.38555022]
 [0.46268282 1.23618462 0.5568484 ]]
Output:
 [[4.87154889e-05]
 [6.41040998e-05]
 [5.83415118e-05]]

	( EPOCH 6919 of 7000 )
h_ip:
 [[0.47798786 1.45635983 0.59647997]
 [0.50017242 1.09336659 0.38553929]
 [0.4626459  1.23617322 0.55682842]]
Output:
 [[4.87068759e-05]
 [6.40941494e-05]
 [5.83310347e-05]]

	( EPOCH 6920 of 7000 )
h_ip:
 [[0.4779503  1.45634823 0.59645953]
 [0.50015234 1.09336039 0.38552836]
 [0.46260898 1.23616182 0.55680843]]
Output:
 [[4.86982654e-05]
 [6.40842019e-05]
 [5.83205607e-05]]

	( EPOCH 6921 of 7000 )
h_ip:
 [[0.47791274 1.45633663 0.59643909]
 [0.50013227 1.09335419 0.38551742]
 [0.46257206 1.23615043 0.55678845]]
Output:
 [[4.86896576e-05]
 [6.40742574e-05]
 [5.83100900e-05]]

	( EPOCH 6922 of 7000 )
h_ip:
 [[0.47787518 1.45632504 0.59641865]
 [0.5001122

In [15]:
print("Actual output: \n", y)
print("\nPredicted output: \n", output)


Actual output: 
 [[0.92]
 [0.86]
 [0.89]]

Predicted output: 
 [[1.00059543]
 [1.00045047]
 [1.00051993]]
