In [1]:
import pandas as pd
import numpy as np

In [2]:
# x is input
# y is output
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x

array([[2., 9.],
       [1., 5.],
       [3., 6.]])

In [4]:
y

array([[92.],
       [86.],
       [89.]])

In [6]:
# normalize value means value should be between o and 1
c=np.max(x,axis=0)# to check maximum value column wise
c

array([3., 9.])

In [8]:
x=x/c
x

array([[0.22222222, 0.11111111],
       [0.11111111, 0.0617284 ],
       [0.33333333, 0.07407407]])

In [10]:
y=y/100 # normalize the output value by 100 beacuse maximum marks is 100
y

array([[0.0092],
       [0.0086],
       [0.0089]])

In [11]:
def sigmoid(x): # finding activation function
    return 1/1+np.exp(-x)
def sigmoid_grad(x):# think it has diffrenciation during back propagation
    return x*(1-x)

In [20]:
epoch=7000 # number of iteration 
eta=0.1# learning rate
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

In [14]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))# wight at hidden is the size between input and hidden
wh

array([[0.54923597, 0.75484849, 0.83385038],
       [0.07515447, 0.30850947, 0.4431128 ]])

In [16]:
wh.shape

(2, 3)

In [18]:
bh=np.random.uniform(size=(1,hidden_neurons))# bias at hidden
bh

array([[0.97116601, 0.67757731, 0.03521903]])

In [21]:
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
print("Weights from hidden to Output Layer:\n",wout)

Weights from hidden to Output Layer:
 [[0.24136229]
 [0.68967786]
 [0.9916053 ]]


In [23]:
bout = np.random.uniform(size = (1, output_neurons))
print("Output Bias:\n",bout)

Output Bias:
 [[0.39607037]]


In [24]:
for i in range(epoch):
    #forward pass
    print("\n\t( EPOCH {} of {} )".format(i+1, epoch))
    h_ip = np.dot(x, wh) + bh # to find hidden input value=dot product of input * weight at hidden + bais at hidden
    print("h_ip:\n", h_ip)
    h_act = sigmoid(h_ip)# activation for hidden value
    o_ip = np.dot(h_act, wout) + bout 
    output = sigmoid(o_ip)
    ###########################################
    eo = y - output # finding error at output layer where y is actual output 
    out_grad = sigmoid_grad(output) # diffrenctiating the output 
    d_output = eo * out_grad# getting delta out put = error * gradient output 
    print("Output:\n", d_output)
    eh = d_output.dot(wout.T) # finding error at hidden layer 
    hidden_grad = sigmoid_grad(h_act)
    d_hidden = eh * hidden_grad # same as above 
    wout += h_act.T.dot(d_output) * eta #
    wh += x.T.dot(d_hidden) * eta


	( EPOCH 1 of 7000 )
h_ip:
 [[1.10156895 0.87960025 0.26975388]
 [1.0368314  0.78049316 0.15522172]
 [1.15981167 0.95204602 0.34599233]]
Output:
 [[0.03376793]
 [0.02953555]
 [0.0367857 ]]

	( EPOCH 2 of 7000 )
h_ip:
 [[1.10150577 0.87936121 0.26896598]
 [1.03679926 0.78037156 0.15482089]
 [1.15972508 0.95171862 0.34491371]]
Output:
 [[0.03136047]
 [0.0273782 ]
 [0.03420498]]

	( EPOCH 3 of 7000 )
h_ip:
 [[1.10144383 0.87913452 0.26822013]
 [1.03676776 0.78025625 0.15444145]
 [1.15964019 0.95140812 0.3438926 ]]
Output:
 [[0.0292847 ]
 [0.02552137]
 [0.03197724]]

	( EPOCH 4 of 7000 )
h_ip:
 [[1.10138317 0.87891876 0.26751133]
 [1.0367369  0.78014649 0.15408087]
 [1.15955704 0.95111258 0.34292218]]
Output:
 [[0.02747514]
 [0.02390536]
 [0.03003309]]

	( EPOCH 5 of 7000 )
h_ip:
 [[1.10132377 0.87871275 0.2668355 ]
 [1.03670669 0.7800417  0.15373706]
 [1.15947562 0.9508304  0.34199686]]
Output:
 [[0.02588271]
 [0.02248547]
 [0.02832048]]

	( EPOCH 6 of 7000 )
h_ip:
 [[1.10126562 0.878515

 [1.15322346 0.9349493  0.29043206]]
Output:
 [[0.00226643]
 [0.0018618 ]
 [0.00257139]]

	( EPOCH 193 of 7000 )
h_ip:
 [[1.09675203 0.86709728 0.22910965]
 [1.03438166 0.77413382 0.13454787]
 [1.15320538 0.9349094  0.29030202]]
Output:
 [[0.00225541]
 [0.0018526 ]
 [0.00255904]]

	( EPOCH 194 of 7000 )
h_ip:
 [[1.0967389  0.8670683  0.22901518]
 [1.03437499 0.77411908 0.13449983]
 [1.15318737 0.93486966 0.29017248]]
Output:
 [[0.0022445 ]
 [0.00184348]
 [0.0025468 ]]

	( EPOCH 195 of 7000 )
h_ip:
 [[1.09672582 0.86703944 0.22892109]
 [1.03436834 0.7741044  0.13445197]
 [1.15316942 0.93483007 0.29004346]]
Output:
 [[0.0022337 ]
 [0.00183445]
 [0.00253468]]

	( EPOCH 196 of 7000 )
h_ip:
 [[1.09671278 0.86701069 0.22882736]
 [1.03436171 0.77408978 0.1344043 ]
 [1.15315154 0.93479065 0.28991495]]
Output:
 [[0.002223  ]
 [0.0018255 ]
 [0.00252267]]

	( EPOCH 197 of 7000 )
h_ip:
 [[1.0966998  0.86698205 0.22873401]
 [1.0343551  0.77407522 0.13435682]
 [1.15313372 0.93475138 0.28978694]]
Out


	( EPOCH 355 of 7000 )
h_ip:
 [[1.09506602 0.8634584  0.21720304]
 [1.03352429 0.77228319 0.12849247]
 [1.15089187 0.92991883 0.27397351]]
Output:
 [[0.00125941]
 [0.00102499]
 [0.00143736]]

	( EPOCH 356 of 7000 )
h_ip:
 [[1.0950576  0.8634406  0.21714455]
 [1.03352001 0.77227414 0.12846273]
 [1.15088032 0.92989441 0.27389328]]
Output:
 [[0.00125597]
 [0.00102216]
 [0.00143347]]

	( EPOCH 357 of 7000 )
h_ip:
 [[1.09504921 0.86342284 0.21708619]
 [1.03351574 0.77226511 0.12843305]
 [1.15086879 0.92987005 0.27381323]]
Output:
 [[0.00125255]
 [0.00101933]
 [0.00142961]]

	( EPOCH 358 of 7000 )
h_ip:
 [[1.09504082 0.86340512 0.21702796]
 [1.03351148 0.7722561  0.12840343]
 [1.15085729 0.92984575 0.27373337]]
Output:
 [[0.00124915]
 [0.00101653]
 [0.00142576]]

	( EPOCH 359 of 7000 )
h_ip:
 [[1.09503246 0.86338744 0.21696986]
 [1.03350723 0.77224711 0.12837389]
 [1.15084581 0.9298215  0.27365368]]
Output:
 [[0.00124577]
 [0.00101374]
 [0.00142193]]

	( EPOCH 360 of 7000 )
h_ip:
 [[1.09502

 [1.14957217 0.92715517 0.26486945]]
Output:
 [[0.00093007]
 [0.00075405]
 [0.00106402]]

	( EPOCH 485 of 7000 )
h_ip:
 [[1.09409775 0.86142978 0.21052043]
 [1.03303192 0.77125153 0.12509401]
 [1.14956307 0.92713628 0.26480705]]
Output:
 [[0.00092818]
 [0.0007525 ]
 [0.00106188]]

	( EPOCH 486 of 7000 )
h_ip:
 [[1.09409113 0.86141603 0.21047503]
 [1.03302855 0.77124453 0.12507091]
 [1.14955398 0.92711742 0.26474476]]
Output:
 [[0.0009263 ]
 [0.00075096]
 [0.00105975]]

	( EPOCH 487 of 7000 )
h_ip:
 [[1.09408452 0.86140231 0.21042969]
 [1.03302519 0.77123755 0.12504786]
 [1.14954491 0.9270986  0.26468258]]
Output:
 [[0.00092443]
 [0.00074943]
 [0.00105762]]

	( EPOCH 488 of 7000 )
h_ip:
 [[1.09407792 0.86138861 0.21038444]
 [1.03302184 0.77123059 0.12502485]
 [1.14953585 0.92707981 0.2646205 ]]
Output:
 [[0.00092256]
 [0.0007479 ]
 [0.0010555 ]]

	( EPOCH 489 of 7000 )
h_ip:
 [[1.09407133 0.86137493 0.21033926]
 [1.03301848 0.77122363 0.12500187]
 [1.14952681 0.92706105 0.26455853]]
Out

 [0.00077981]]

	( EPOCH 665 of 7000 )
h_ip:
 [[1.09304869 0.85927031 0.20336628]
 [1.03249847 0.77015333 0.12145583]
 [1.1481233  0.92417401 0.25499237]]
Output:
 [[0.0006793 ]
 [0.00054898]
 [0.00077865]]

	( EPOCH 666 of 7000 )
h_ip:
 [[1.09304354 0.85925978 0.20333129]
 [1.03249585 0.77014797 0.12143803]
 [1.14811622 0.92415956 0.25494435]]
Output:
 [[0.00067829]
 [0.00054815]
 [0.0007775 ]]

	( EPOCH 667 of 7000 )
h_ip:
 [[1.09303838 0.85924926 0.20329633]
 [1.03249323 0.77014262 0.12142026]
 [1.14810915 0.92414514 0.2548964 ]]
Output:
 [[0.00067728]
 [0.00054733]
 [0.00077635]]

	( EPOCH 668 of 7000 )
h_ip:
 [[1.09303324 0.85923875 0.20326142]
 [1.03249061 0.77013728 0.1214025 ]
 [1.14810209 0.92413073 0.2548485 ]]
Output:
 [[0.00067627]
 [0.00054651]
 [0.0007752 ]]

	( EPOCH 669 of 7000 )
h_ip:
 [[1.0930281  0.85922826 0.20322656]
 [1.032488   0.77013195 0.12138477]
 [1.14809503 0.92411634 0.25480066]]
Output:
 [[0.00067526]
 [0.00054569]
 [0.00077405]]

	( EPOCH 670 of 7000 )
h

 [[0.00054598]
 [0.00044047]
 [0.00062647]]

	( EPOCH 829 of 7000 )
h_ip:
 [[1.09227578 0.8577007  0.19813801]
 [1.03210544 0.76935511 0.1187971 ]
 [1.14706247 0.92202077 0.24781892]]
Output:
 [[0.00054533]
 [0.00043994]
 [0.00062572]]

	( EPOCH 830 of 7000 )
h_ip:
 [[1.09227147 0.85769198 0.1981089 ]
 [1.03210325 0.76935068 0.11878229]
 [1.14705655 0.92200881 0.24777898]]
Output:
 [[0.00054467]
 [0.0004394 ]
 [0.00062497]]

	( EPOCH 831 of 7000 )
h_ip:
 [[1.09226715 0.85768327 0.19807981]
 [1.03210106 0.76934625 0.1187675 ]
 [1.14705063 0.92199686 0.24773907]]
Output:
 [[0.00054401]
 [0.00043887]
 [0.00062422]]

	( EPOCH 832 of 7000 )
h_ip:
 [[1.09226285 0.85767457 0.19805076]
 [1.03209887 0.76934183 0.11875272]
 [1.14704472 0.92198492 0.2476992 ]]
Output:
 [[0.00054336]
 [0.00043834]
 [0.00062347]]

	( EPOCH 833 of 7000 )
h_ip:
 [[1.09225854 0.85766588 0.19802173]
 [1.03209668 0.7693374  0.11873796]
 [1.14703881 0.921973   0.24765938]]
Output:
 [[0.00054271]
 [0.00043781]
 [0.0006227

	( EPOCH 962 of 7000 )
h_ip:
 [[1.09173581 0.85661356 0.19450201]
 [1.03183087 0.76880225 0.1169481 ]
 [1.14632135 0.92052933 0.24282977]]
Output:
 [[0.00046986]
 [0.0003787 ]
 [0.00053941]]

	( EPOCH 963 of 7000 )
h_ip:
 [[1.09173199 0.85660589 0.19447632]
 [1.03182893 0.76879835 0.11693504]
 [1.1463161  0.92051881 0.24279452]]
Output:
 [[0.00046937]
 [0.0003783 ]
 [0.00053885]]

	( EPOCH 964 of 7000 )
h_ip:
 [[1.09172818 0.85659823 0.19445065]
 [1.03182699 0.76879446 0.11692199]
 [1.14631086 0.9205083  0.2427593 ]]
Output:
 [[0.00046888]
 [0.0003779 ]
 [0.00053829]]

	( EPOCH 965 of 7000 )
h_ip:
 [[1.09172436 0.85659057 0.19442501]
 [1.03182505 0.76879057 0.11690895]
 [1.14630562 0.9204978  0.24272411]]
Output:
 [[0.0004684 ]
 [0.00037751]
 [0.00053773]]

	( EPOCH 966 of 7000 )
h_ip:
 [[1.09172055 0.85658292 0.19439939]
 [1.03182311 0.76878668 0.11689592]
 [1.14630039 0.9204873  0.24268895]]
Output:
 [[0.00046791]
 [0.00037712]
 [0.00053717]]

	( EPOCH 967 of 7000 )
h_ip:
 [[1.091716

 [1.14561326 0.91911333 0.23807694]]
Output:
 [[0.00040882]
 [0.00032927]
 [0.0004695 ]]

	( EPOCH 1106 of 7000 )
h_ip:
 [[1.09121652 0.85557463 0.19101559]
 [1.03156681 0.76827392 0.1151752 ]
 [1.14560858 0.91910401 0.23804559]]
Output:
 [[0.00040845]
 [0.00032897]
 [0.00046907]]

	( EPOCH 1107 of 7000 )
h_ip:
 [[1.09121312 0.85556784 0.19099276]
 [1.03156508 0.76827047 0.11516359]
 [1.14560391 0.91909469 0.23801425]]
Output:
 [[0.00040808]
 [0.00032867]
 [0.00046865]]

	( EPOCH 1108 of 7000 )
h_ip:
 [[1.09120971 0.85556105 0.19096994]
 [1.03156335 0.76826702 0.11515198]
 [1.14559924 0.91908538 0.23798295]]
Output:
 [[0.00040771]
 [0.00032837]
 [0.00046822]]

	( EPOCH 1109 of 7000 )
h_ip:
 [[1.09120631 0.85555427 0.19094714]
 [1.03156162 0.76826357 0.11514039]
 [1.14559457 0.91907607 0.23795166]]
Output:
 [[0.00040734]
 [0.00032807]
 [0.0004678 ]]

	( EPOCH 1110 of 7000 )
h_ip:
 [[1.09120291 0.85554749 0.19092436]
 [1.03155989 0.76826012 0.11512881]
 [1.1455899  0.91906678 0.2379204 ]

 [1.14506696 0.91802643 0.2344178 ]]
Output:
 [[0.00036792]
 [0.00029621]
 [0.0004226 ]]

	( EPOCH 1228 of 7000 )
h_ip:
 [[1.0908188  0.85478299 0.1883511 ]
 [1.03136457 0.76787134 0.11382027]
 [1.14506267 0.91801792 0.23438911]]
Output:
 [[0.00036762]
 [0.00029596]
 [0.00042226]]

	( EPOCH 1229 of 7000 )
h_ip:
 [[1.09081568 0.85477679 0.1883302 ]
 [1.03136299 0.76786819 0.11380964]
 [1.14505839 0.91800942 0.23436044]]
Output:
 [[0.00036732]
 [0.00029572]
 [0.00042191]]

	( EPOCH 1230 of 7000 )
h_ip:
 [[1.09081256 0.8547706  0.18830932]
 [1.0313614  0.76786504 0.11379902]
 [1.14505411 0.91800092 0.23433179]]
Output:
 [[0.00036702]
 [0.00029548]
 [0.00042157]]

	( EPOCH 1231 of 7000 )
h_ip:
 [[1.09080944 0.85476441 0.18828846]
 [1.03135982 0.76786189 0.11378842]
 [1.14504983 0.91799242 0.23430316]]
Output:
 [[0.00036672]
 [0.00029523]
 [0.00042122]]

	( EPOCH 1232 of 7000 )
h_ip:
 [[1.09080633 0.85475822 0.18826761]
 [1.03135823 0.76785875 0.11377781]
 [1.14504555 0.91798394 0.23427454]

 [1.14458412 0.91706957 0.23118844]]
Output:
 [[0.00033564]
 [0.00027014]
 [0.00038556]]

	( EPOCH 1345 of 7000 )
h_ip:
 [[1.09046726 0.85408603 0.18599948]
 [1.03118582 0.76751691 0.11262445]
 [1.14458015 0.91706171 0.23116189]]
Output:
 [[0.00033539]
 [0.00026994]
 [0.00038527]]

	( EPOCH 1346 of 7000 )
h_ip:
 [[1.09046437 0.8540803  0.18598015]
 [1.03118435 0.767514   0.11261462]
 [1.14457618 0.91705386 0.23113535]]
Output:
 [[0.00033514]
 [0.00026974]
 [0.00038498]]

	( EPOCH 1347 of 7000 )
h_ip:
 [[1.09046147 0.85407458 0.18596083]
 [1.03118288 0.76751109 0.11260479]
 [1.14457221 0.91704601 0.23110883]]
Output:
 [[0.00033489]
 [0.00026954]
 [0.0003847 ]]

	( EPOCH 1348 of 7000 )
h_ip:
 [[1.09045859 0.85406887 0.18594152]
 [1.03118141 0.76750819 0.11259497]
 [1.14456825 0.91703817 0.23108233]]
Output:
 [[0.00033464]
 [0.00026933]
 [0.00038441]]

	( EPOCH 1349 of 7000 )
h_ip:
 [[1.0904557  0.85406316 0.18592222]
 [1.03117994 0.76750528 0.11258516]
 [1.14456429 0.91703033 0.23105585]


	( EPOCH 1489 of 7000 )
h_ip:
 [[1.09006826 0.85329794 0.18333375]
 [1.03098293 0.76711614 0.1112689 ]
 [1.14403248 0.91598047 0.22750345]]
Output:
 [[0.00030265]
 [0.00024354]
 [0.00034767]]

	( EPOCH 1490 of 7000 )
h_ip:
 [[1.0900656  0.8532927  0.18331602]
 [1.03098158 0.76711348 0.11125989]
 [1.14402884 0.91597329 0.22747912]]
Output:
 [[0.00030244]
 [0.00024337]
 [0.00034744]]

	( EPOCH 1491 of 7000 )
h_ip:
 [[1.09006295 0.85328747 0.18329831]
 [1.03098023 0.76711082 0.11125088]
 [1.1440252  0.91596611 0.2274548 ]]
Output:
 [[0.00030224]
 [0.00024321]
 [0.0003472 ]]

	( EPOCH 1492 of 7000 )
h_ip:
 [[1.0900603  0.85328224 0.1832806 ]
 [1.03097888 0.76710816 0.11124188]
 [1.14402156 0.91595894 0.2274305 ]]
Output:
 [[0.00030203]
 [0.00024304]
 [0.00034697]]

	( EPOCH 1493 of 7000 )
h_ip:
 [[1.09005765 0.85327702 0.1832629 ]
 [1.03097753 0.7671055  0.11123288]
 [1.14401792 0.91595177 0.22740621]]
Output:
 [[0.00030183]
 [0.00024288]
 [0.00034673]]

	( EPOCH 1494 of 7000 )
h_ip:
 [[1


	( EPOCH 1627 of 7000 )
h_ip:
 [[1.08971537 0.8526034  0.18097853]
 [1.03080349 0.76676295 0.11007126]
 [1.1435481  0.91502758 0.22427104]]
Output:
 [[0.0002767 ]
 [0.00022263]
 [0.00031785]]

	( EPOCH 1628 of 7000 )
h_ip:
 [[1.0897129  0.85259856 0.18096209]
 [1.03080223 0.76676048 0.11006291]
 [1.14354472 0.91502094 0.22424849]]
Output:
 [[0.00027652]
 [0.0002225 ]
 [0.00031765]]

	( EPOCH 1629 of 7000 )
h_ip:
 [[1.08971044 0.85259372 0.18094567]
 [1.03080098 0.76675802 0.11005455]
 [1.14354134 0.9150143  0.22422595]]
Output:
 [[0.00027635]
 [0.00022236]
 [0.00031746]]

	( EPOCH 1630 of 7000 )
h_ip:
 [[1.08970798 0.85258889 0.18092925]
 [1.03079973 0.76675557 0.11004621]
 [1.14353796 0.91500767 0.22420342]]
Output:
 [[0.00027618]
 [0.00022222]
 [0.00031726]]

	( EPOCH 1631 of 7000 )
h_ip:
 [[1.08970552 0.85258406 0.18091285]
 [1.03079848 0.76675311 0.11003787]
 [1.14353459 0.91500104 0.2241809 ]]
Output:
 [[0.00027601]
 [0.00022208]
 [0.00031706]]

	( EPOCH 1632 of 7000 )
h_ip:
 [[1


	( EPOCH 1713 of 7000 )
h_ip:
 [[1.08950809 0.85219649 0.17959603]
 [1.03069809 0.76655602 0.10936826]
 [1.14326358 0.9144693  0.22237361]]
Output:
 [[0.00026264]
 [0.00021132]
 [0.00030169]]

	( EPOCH 1714 of 7000 )
h_ip:
 [[1.08950573 0.85219187 0.17958031]
 [1.03069689 0.76655367 0.10936027]
 [1.14326035 0.91446295 0.22235203]]
Output:
 [[0.00026248]
 [0.00021119]
 [0.00030151]]

	( EPOCH 1715 of 7000 )
h_ip:
 [[1.08950337 0.85218725 0.1795646 ]
 [1.03069569 0.76655132 0.10935228]
 [1.14325711 0.91445661 0.22233046]]
Output:
 [[0.00026233]
 [0.00021107]
 [0.00030133]]

	( EPOCH 1716 of 7000 )
h_ip:
 [[1.08950102 0.85218263 0.17954889]
 [1.03069449 0.76654897 0.10934429]
 [1.14325388 0.91445028 0.22230891]]
Output:
 [[0.00026217]
 [0.00021094]
 [0.00030115]]

	( EPOCH 1717 of 7000 )
h_ip:
 [[1.08949866 0.85217801 0.17953319]
 [1.03069329 0.76654662 0.10933631]
 [1.14325065 0.91444394 0.22228736]]
Output:
 [[0.00026202]
 [0.00021082]
 [0.00030097]]

	( EPOCH 1718 of 7000 )
h_ip:
 [[1

	( EPOCH 1851 of 7000 )
h_ip:
 [[1.08919327 0.85157991 0.17749743]
 [1.03053801 0.76624247 0.10830112]
 [1.14283147 0.91362335 0.21949327]]
Output:
 [[0.0002428 ]
 [0.00019536]
 [0.00027887]]

	( EPOCH 1852 of 7000 )
h_ip:
 [[1.08919107 0.8515756  0.17748272]
 [1.03053688 0.76624027 0.10829364]
 [1.14282844 0.91361743 0.21947308]]
Output:
 [[0.00024267]
 [0.00019526]
 [0.00027872]]

	( EPOCH 1853 of 7000 )
h_ip:
 [[1.08918886 0.85157128 0.17746801]
 [1.03053576 0.76623808 0.10828616]
 [1.14282541 0.91361151 0.2194529 ]]
Output:
 [[0.00024254]
 [0.00019515]
 [0.00027857]]

	( EPOCH 1854 of 7000 )
h_ip:
 [[1.08918666 0.85156697 0.17745332]
 [1.03053464 0.76623588 0.10827869]
 [1.14282238 0.91360559 0.21943273]]
Output:
 [[0.0002424 ]
 [0.00019504]
 [0.00027841]]

	( EPOCH 1855 of 7000 )
h_ip:
 [[1.08918445 0.85156266 0.17743863]
 [1.03053352 0.76623369 0.10827122]
 [1.14281936 0.91359967 0.21941257]]
Output:
 [[0.00024227]
 [0.00019494]
 [0.00027826]]

	( EPOCH 1856 of 7000 )
h_ip:
 [[1.


	( EPOCH 2010 of 7000 )
h_ip:
 [[1.0888545  0.85091824 0.17524025]
 [1.03036574 0.76590598 0.10715335]
 [1.14236646 0.91271553 0.21639521]]
Output:
 [[0.00022333]
 [0.00017971]
 [0.00025646]]

	( EPOCH 2011 of 7000 )
h_ip:
 [[1.08885244 0.85091423 0.17522654]
 [1.0303647  0.76590394 0.10714638]
 [1.14236363 0.91271002 0.2163764 ]]
Output:
 [[0.00022321]
 [0.00017962]
 [0.00025633]]

	( EPOCH 2012 of 7000 )
h_ip:
 [[1.08885038 0.85091022 0.17521285]
 [1.03036365 0.76590191 0.10713942]
 [1.14236081 0.91270452 0.2163576 ]]
Output:
 [[0.0002231 ]
 [0.00017953]
 [0.0002562 ]]

	( EPOCH 2013 of 7000 )
h_ip:
 [[1.08884833 0.85090621 0.17519916]
 [1.0303626  0.76589987 0.10713246]
 [1.14235799 0.91269902 0.21633881]]
Output:
 [[0.00022299]
 [0.00017944]
 [0.00025607]]

	( EPOCH 2014 of 7000 )
h_ip:
 [[1.08884628 0.8509022  0.17518547]
 [1.03036156 0.76589783 0.1071255 ]
 [1.14235517 0.91269352 0.21632003]]
Output:
 [[0.00022288]
 [0.00017935]
 [0.00025594]]

	( EPOCH 2015 of 7000 )
h_ip:
 [[1

 [1.14190557 0.91181822 0.21332579]]
Output:
 [[0.00020574]
 [0.00016559]
 [0.00023622]]

	( EPOCH 2180 of 7000 )
h_ip:
 [[1.08851681 0.8502605  0.17299121]
 [1.03019403 0.76557151 0.10600973]
 [1.14190293 0.9118131  0.21330825]]
Output:
 [[0.00020565]
 [0.00016551]
 [0.00023611]]

	( EPOCH 2181 of 7000 )
h_ip:
 [[1.08851489 0.85025677 0.17297843]
 [1.03019305 0.76556961 0.10600323]
 [1.1419003  0.91180798 0.21329071]]
Output:
 [[0.00020555]
 [0.00016543]
 [0.000236  ]]

	( EPOCH 2182 of 7000 )
h_ip:
 [[1.08851297 0.85025304 0.17296566]
 [1.03019208 0.76556771 0.10599674]
 [1.14189767 0.91180286 0.21327318]]
Output:
 [[0.00020546]
 [0.00016536]
 [0.00023589]]

	( EPOCH 2183 of 7000 )
h_ip:
 [[1.08851105 0.85024931 0.1729529 ]
 [1.0301911  0.76556581 0.10599024]
 [1.14189504 0.91179775 0.21325566]]
Output:
 [[0.00020536]
 [0.00016528]
 [0.00023578]]

	( EPOCH 2184 of 7000 )
h_ip:
 [[1.08850914 0.85024559 0.17294014]
 [1.03019013 0.76556392 0.10598376]
 [1.14189241 0.91179264 0.21323815]


	( EPOCH 2363 of 7000 )
h_ip:
 [[1.08817773 0.84960182 0.17073358]
 [1.03002161 0.76523654 0.10486174]
 [1.14143751 0.91090938 0.21020942]]
Output:
 [[0.00018947]
 [0.00015252]
 [0.00021747]]

	( EPOCH 2364 of 7000 )
h_ip:
 [[1.08817594 0.84959835 0.17072166]
 [1.0300207  0.76523478 0.10485568]
 [1.14143505 0.91090462 0.21019306]]
Output:
 [[0.00018938]
 [0.00015246]
 [0.00021738]]

	( EPOCH 2365 of 7000 )
h_ip:
 [[1.08817415 0.84959488 0.17070975]
 [1.03001979 0.76523301 0.10484962]
 [1.1414326  0.91089985 0.21017671]]
Output:
 [[0.0001893 ]
 [0.00015239]
 [0.00021729]]

	( EPOCH 2366 of 7000 )
h_ip:
 [[1.08817236 0.84959141 0.17069785]
 [1.03001888 0.76523125 0.10484357]
 [1.14143014 0.91089509 0.21016037]]
Output:
 [[0.00018922]
 [0.00015233]
 [0.00021719]]

	( EPOCH 2367 of 7000 )
h_ip:
 [[1.08817057 0.84958794 0.17068594]
 [1.03001797 0.76522949 0.10483751]
 [1.14142769 0.91089034 0.21014403]]
Output:
 [[0.00018914]
 [0.00015226]
 [0.0002171 ]]

	( EPOCH 2368 of 7000 )
h_ip:
 [[1


	( EPOCH 2544 of 7000 )
h_ip:
 [[1.08786397 0.84899383 0.16864485]
 [1.02986206 0.76492736 0.10379963]
 [1.14100684 0.9100752  0.20734236]]
Output:
 [[0.00017576]
 [0.00014153]
 [0.00020168]]

	( EPOCH 2545 of 7000 )
h_ip:
 [[1.08786229 0.84899058 0.16863367]
 [1.02986121 0.76492571 0.10379395]
 [1.14100453 0.91007074 0.20732701]]
Output:
 [[0.00017569]
 [0.00014147]
 [0.0002016 ]]

	( EPOCH 2546 of 7000 )
h_ip:
 [[1.08786061 0.84898733 0.1686225 ]
 [1.02986036 0.76492405 0.10378827]
 [1.14100223 0.91006628 0.20731168]]
Output:
 [[0.00017562]
 [0.00014141]
 [0.00020152]]

	( EPOCH 2547 of 7000 )
h_ip:
 [[1.08785893 0.84898408 0.16861133]
 [1.0298595  0.7649224  0.10378259]
 [1.14099993 0.91006182 0.20729634]]
Output:
 [[0.00017555]
 [0.00014136]
 [0.00020144]]

	( EPOCH 2548 of 7000 )
h_ip:
 [[1.08785725 0.84898083 0.16860016]
 [1.02985865 0.76492075 0.10377691]
 [1.14099762 0.91005737 0.20728102]]
Output:
 [[0.00017548]
 [0.0001413 ]
 [0.00020136]]

	( EPOCH 2549 of 7000 )
h_ip:
 [[1


	( EPOCH 2722 of 7000 )
h_ip:
 [[1.08757373 0.84843265 0.16671281]
 [1.02971448 0.76464198 0.10281721]
 [1.14060846 0.90930525 0.20469032]]
Output:
 [[0.00016406]
 [0.00013215]
 [0.0001882 ]]

	( EPOCH 2723 of 7000 )
h_ip:
 [[1.08757215 0.84842959 0.16670227]
 [1.02971368 0.76464043 0.10281185]
 [1.14060628 0.90930106 0.20467585]]
Output:
 [[0.000164  ]
 [0.0001321 ]
 [0.00018813]]

	( EPOCH 2724 of 7000 )
h_ip:
 [[1.08757056 0.84842653 0.16669173]
 [1.02971287 0.76463887 0.1028065 ]
 [1.14060411 0.90929686 0.20466139]]
Output:
 [[0.00016393]
 [0.00013205]
 [0.00018806]]

	( EPOCH 2725 of 7000 )
h_ip:
 [[1.08756898 0.84842348 0.1666812 ]
 [1.02971207 0.76463732 0.10280114]
 [1.14060194 0.90929267 0.20464693]]
Output:
 [[0.00016387]
 [0.000132  ]
 [0.00018799]]

	( EPOCH 2726 of 7000 )
h_ip:
 [[1.0875674  0.84842042 0.16667067]
 [1.02971126 0.76463577 0.10279578]
 [1.14059977 0.90928847 0.20463248]]
Output:
 [[0.00016381]
 [0.00013195]
 [0.00018792]]

	( EPOCH 2727 of 7000 )
h_ip:
 [[1

	( EPOCH 2871 of 7000 )
h_ip:
 [[1.08734319 0.84798772 0.16517813]
 [1.02959725 0.76441572 0.10203685]
 [1.14029202 0.9086948  0.2025837 ]]
Output:
 [[0.00015538]
 [0.0001252 ]
 [0.0001782 ]]

	( EPOCH 2872 of 7000 )
h_ip:
 [[1.08734168 0.84798481 0.16516806]
 [1.02959649 0.76441424 0.10203173]
 [1.14028995 0.9086908  0.20256988]]
Output:
 [[0.00015533]
 [0.00012515]
 [0.00017814]]

	( EPOCH 2873 of 7000 )
h_ip:
 [[1.08734017 0.84798189 0.165158  ]
 [1.02959572 0.76441276 0.10202661]
 [1.14028787 0.9086868  0.20255607]]
Output:
 [[0.00015527]
 [0.00012511]
 [0.00017807]]

	( EPOCH 2874 of 7000 )
h_ip:
 [[1.08733866 0.84797898 0.16514795]
 [1.02959495 0.76441128 0.1020215 ]
 [1.1402858  0.90868281 0.20254226]]
Output:
 [[0.00015522]
 [0.00012506]
 [0.00017801]]

	( EPOCH 2875 of 7000 )
h_ip:
 [[1.08733715 0.84797607 0.16513789]
 [1.02959418 0.7644098  0.10201639]
 [1.14028372 0.90867881 0.20252846]]
Output:
 [[0.00015516]
 [0.00012502]
 [0.00017795]]

	( EPOCH 2876 of 7000 )
h_ip:
 [[1.

 [1.13994997 0.90803603 0.20030634]]
Output:
 [[0.00014658]
 [0.00011814]
 [0.00016805]]

	( EPOCH 3041 of 7000 )
h_ip:
 [[1.08709256 0.84750481 0.16350952]
 [1.02946981 0.76417015 0.10118838]
 [1.139948   0.90803223 0.20029319]]
Output:
 [[0.00014653]
 [0.0001181 ]
 [0.00016799]]

	( EPOCH 3042 of 7000 )
h_ip:
 [[1.08709112 0.84750204 0.16349995]
 [1.02946908 0.76416874 0.10118351]
 [1.13994603 0.90802844 0.20028005]]
Output:
 [[0.00014648]
 [0.00011806]
 [0.00016794]]

	( EPOCH 3043 of 7000 )
h_ip:
 [[1.08708968 0.84749927 0.16349038]
 [1.02946835 0.76416733 0.10117865]
 [1.13994405 0.90802464 0.20026692]]
Output:
 [[0.00014643]
 [0.00011802]
 [0.00016788]]

	( EPOCH 3044 of 7000 )
h_ip:
 [[1.08708825 0.84749651 0.16348081]
 [1.02946762 0.76416592 0.10117378]
 [1.13994208 0.90802084 0.20025378]]
Output:
 [[0.00014638]
 [0.00011798]
 [0.00016782]]

	( EPOCH 3045 of 7000 )
h_ip:
 [[1.08708681 0.84749374 0.16347124]
 [1.02946689 0.76416452 0.10116892]
 [1.13994011 0.90801705 0.20024065]


	( EPOCH 3203 of 7000 )
h_ip:
 [[1.08686485 0.84706677 0.16199333]
 [1.02935402 0.76394739 0.10041742]
 [1.13963545 0.90743123 0.1982119 ]]
Output:
 [[0.00013897]
 [0.00011205]
 [0.00015928]]

	( EPOCH 3204 of 7000 )
h_ip:
 [[1.08686348 0.84706412 0.16198418]
 [1.02935332 0.76394604 0.10041277]
 [1.13963356 0.90742761 0.19819934]]
Output:
 [[0.00013893]
 [0.00011201]
 [0.00015923]]

	( EPOCH 3205 of 7000 )
h_ip:
 [[1.0868621  0.84706148 0.16197503]
 [1.02935262 0.7639447  0.10040812]
 [1.13963168 0.90742399 0.19818678]]
Output:
 [[0.00013888]
 [0.00011198]
 [0.00015918]]

	( EPOCH 3206 of 7000 )
h_ip:
 [[1.08686073 0.84705884 0.16196589]
 [1.02935192 0.76394336 0.10040347]
 [1.13962979 0.90742036 0.19817423]]
Output:
 [[0.00013884]
 [0.00011194]
 [0.00015913]]

	( EPOCH 3207 of 7000 )
h_ip:
 [[1.08685936 0.84705621 0.16195675]
 [1.02935123 0.76394202 0.10039882]
 [1.13962791 0.90741674 0.19816168]]
Output:
 [[0.00013879]
 [0.00011191]
 [0.00015908]]

	( EPOCH 3208 of 7000 )
h_ip:
 [[1


	( EPOCH 3392 of 7000 )
h_ip:
 [[1.08661159 0.84658033 0.16030669]
 [1.02922524 0.76370002 0.09955979]
 [1.13928783 0.90676384 0.19589659]]
Output:
 [[0.00013107]
 [0.00010572]
 [0.00015017]]

	( EPOCH 3393 of 7000 )
h_ip:
 [[1.08661028 0.84657782 0.16029799]
 [1.02922457 0.76369874 0.09955537]
 [1.13928603 0.9067604  0.19588464]]
Output:
 [[0.00013103]
 [0.00010569]
 [0.00015012]]

	( EPOCH 3394 of 7000 )
h_ip:
 [[1.08660898 0.84657532 0.16028929]
 [1.02922391 0.76369747 0.09955094]
 [1.13928424 0.90675696 0.19587269]]
Output:
 [[0.00013099]
 [0.00010566]
 [0.00015008]]

	( EPOCH 3395 of 7000 )
h_ip:
 [[1.08660767 0.84657281 0.16028059]
 [1.02922325 0.76369619 0.09954652]
 [1.13928245 0.90675352 0.19586075]]
Output:
 [[0.00013095]
 [0.00010563]
 [0.00015003]]

	( EPOCH 3396 of 7000 )
h_ip:
 [[1.08660637 0.84657031 0.16027189]
 [1.02922258 0.76369492 0.0995421 ]
 [1.13928066 0.90675008 0.19584881]]
Output:
 [[0.00013091]
 [0.0001056 ]
 [0.00014999]]

	( EPOCH 3397 of 7000 )
h_ip:
 [[1

 [1.13896706 0.90614896 0.1937596 ]]
Output:
 [[0.00012422]
 [0.00010024]
 [0.00014227]]

	( EPOCH 3576 of 7000 )
h_ip:
 [[1.08637665 0.84612978 0.15874166]
 [1.02910577 0.7634709  0.098764  ]
 [1.13896535 0.90614568 0.19374819]]
Output:
 [[0.00012418]
 [0.00010021]
 [0.00014223]]

	( EPOCH 3577 of 7000 )
h_ip:
 [[1.0863754  0.84612739 0.15873335]
 [1.02910514 0.76346968 0.09875978]
 [1.13896364 0.9061424  0.19373678]]
Output:
 [[0.00012415]
 [0.00010018]
 [0.00014219]]

	( EPOCH 3578 of 7000 )
h_ip:
 [[1.08637415 0.846125   0.15872504]
 [1.0291045  0.76346847 0.09875555]
 [1.13896192 0.90613912 0.19372537]]
Output:
 [[0.00012411]
 [0.00010015]
 [0.00014215]]

	( EPOCH 3579 of 7000 )
h_ip:
 [[1.08637291 0.84612261 0.15871673]
 [1.02910387 0.76346725 0.09875133]
 [1.13896021 0.90613584 0.19371397]]
Output:
 [[0.00012408]
 [0.00010012]
 [0.0001421 ]]

	( EPOCH 3580 of 7000 )
h_ip:
 [[1.08637166 0.84612022 0.15870843]
 [1.02910323 0.76346604 0.0987471 ]
 [1.1389585  0.90613256 0.19370256]

 [1.35886202e-04]]

	( EPOCH 3739 of 7000 )
h_ip:
 [[1.08617723 0.84574786 0.15741293]
 [1.02900437 0.76327668 0.09808836]
 [1.13869163 0.90562169 0.19192414]]
Output:
 [[1.18654256e-04]
 [9.57821092e-05]
 [1.35848775e-04]]

	( EPOCH 3740 of 7000 )
h_ip:
 [[1.08617603 0.84574557 0.15740493]
 [1.02900376 0.76327551 0.0980843 ]
 [1.13868998 0.90561854 0.19191317]]
Output:
 [[1.18621824e-04]
 [9.57561515e-05]
 [1.35811368e-04]]

	( EPOCH 3741 of 7000 )
h_ip:
 [[1.08617483 0.84574327 0.15739694]
 [1.02900315 0.76327435 0.09808023]
 [1.13868834 0.90561539 0.19190219]]
Output:
 [[1.18589409e-04]
 [9.57302077e-05]
 [1.35773981e-04]]

	( EPOCH 3742 of 7000 )
h_ip:
 [[1.08617363 0.84574098 0.15738895]
 [1.02900254 0.76327318 0.09807617]
 [1.13868669 0.90561224 0.19189122]]
Output:
 [[1.18557012e-04]
 [9.57042779e-05]
 [1.35736614e-04]]

	( EPOCH 3743 of 7000 )
h_ip:
 [[1.08617243 0.84573868 0.15738096]
 [1.02900193 0.76327201 0.09807211]
 [1.13868505 0.90560909 0.19188026]]
Output:
 [[1.1852463

h_ip:
 [[1.08600152 0.84541174 0.15624189]
 [1.02891502 0.76310575 0.09749291]
 [1.13845046 0.90516053 0.19031656]]
Output:
 [[1.14006956e-04]
 [9.20627696e-05]
 [1.30488524e-04]]

	( EPOCH 3889 of 7000 )
h_ip:
 [[1.08600036 0.84540952 0.15623416]
 [1.02891443 0.76310463 0.09748898]
 [1.13844887 0.90515749 0.19030596]]
Output:
 [[1.13976977e-04]
 [9.20387779e-05]
 [1.30453945e-04]]

	( EPOCH 3890 of 7000 )
h_ip:
 [[1.0859992  0.84540731 0.15622644]
 [1.02891384 0.7631035  0.09748506]
 [1.13844728 0.90515445 0.19029535]]
Output:
 [[1.13947014e-04]
 [9.20147987e-05]
 [1.30419384e-04]]

	( EPOCH 3891 of 7000 )
h_ip:
 [[1.08599804 0.84540509 0.15621872]
 [1.02891325 0.76310237 0.09748113]
 [1.13844569 0.90515141 0.19028475]]
Output:
 [[1.13917065e-04]
 [9.19908320e-05]
 [1.30384840e-04]]

	( EPOCH 3892 of 7000 )
h_ip:
 [[1.08599688 0.84540288 0.156211  ]
 [1.02891266 0.76310125 0.0974772 ]
 [1.1384441  0.90514837 0.19027415]]
Output:
 [[1.13887133e-04]
 [9.19668776e-05]
 [1.30350315e-04]]


 [1.13815753 0.90460104 0.18836338]]
Output:
 [[1.08631125e-04]
 [8.77608820e-05]
 [1.24287738e-04]]

	( EPOCH 4077 of 7000 )
h_ip:
 [[1.08578699 0.84500183 0.1548117 ]
 [1.02880593 0.7628973  0.09676569]
 [1.138156   0.90459813 0.1883532 ]]
Output:
 [[1.08603864e-04]
 [8.77390688e-05]
 [1.24256294e-04]]

	( EPOCH 4078 of 7000 )
h_ip:
 [[1.08578587 0.8449997  0.15480428]
 [1.02880537 0.76289622 0.09676192]
 [1.13815448 0.90459522 0.18834303]]
Output:
 [[1.08576617e-04]
 [8.77172664e-05]
 [1.24224865e-04]]

	( EPOCH 4079 of 7000 )
h_ip:
 [[1.08578476 0.84499758 0.15479687]
 [1.0288048  0.76289514 0.09675815]
 [1.13815295 0.90459231 0.18833286]]
Output:
 [[1.08549384e-04]
 [8.76954748e-05]
 [1.24193452e-04]]

	( EPOCH 4080 of 7000 )
h_ip:
 [[1.08578365 0.84499546 0.15478947]
 [1.02880424 0.76289406 0.09675438]
 [1.13815143 0.9045894  0.18832269]]
Output:
 [[1.08522164e-04]
 [8.76736939e-05]
 [1.24162055e-04]]

	( EPOCH 4081 of 7000 )
h_ip:
 [[1.08578254 0.84499334 0.15478206]
 [1.0288036

h_ip:
 [[1.0856175  0.84467835 0.15368147]
 [1.02871975 0.7627328  0.09619099]
 [1.13792338 0.90415433 0.18680163]]
Output:
 [[1.04535327e-04]
 [8.44836400e-05]
 [1.19563300e-04]]

	( EPOCH 4233 of 7000 )
h_ip:
 [[1.08561643 0.8446763  0.1536743 ]
 [1.0287192  0.76273176 0.09618734]
 [1.1379219  0.90415151 0.18679178]]
Output:
 [[1.04510053e-04]
 [8.44634175e-05]
 [1.19534146e-04]]

	( EPOCH 4234 of 7000 )
h_ip:
 [[1.08561535 0.84467425 0.15366713]
 [1.02871866 0.76273071 0.0961837 ]
 [1.13792043 0.9041487  0.18678194]]
Output:
 [[1.04484790e-04]
 [8.44432046e-05]
 [1.19505006e-04]]

	( EPOCH 4235 of 7000 )
h_ip:
 [[1.08561428 0.8446722  0.15365996]
 [1.02871811 0.76272967 0.09618005]
 [1.13791895 0.90414588 0.18677209]]
Output:
 [[1.04459540e-04]
 [8.44230013e-05]
 [1.19475880e-04]]

	( EPOCH 4236 of 7000 )
h_ip:
 [[1.0856132  0.84467015 0.15365279]
 [1.02871756 0.76272863 0.09617641]
 [1.13791748 0.90414307 0.18676225]]
Output:
 [[1.04434301e-04]
 [8.44028076e-05]
 [1.19446767e-04]]


 [1.13766393 0.90365986 0.18507058]]
Output:
 [[1.00195046e-04]
 [8.10110384e-05]
 [1.14556802e-04]]

	( EPOCH 4412 of 7000 )
h_ip:
 [[1.08542744 0.84431597 0.1524136 ]
 [1.0286231  0.76254852 0.09554631]
 [1.13766251 0.90365714 0.18506108]]
Output:
 [[1.00171795e-04]
 [8.09924363e-05]
 [1.14529982e-04]]

	( EPOCH 4413 of 7000 )
h_ip:
 [[1.0854264  0.84431399 0.15240669]
 [1.02862258 0.76254751 0.09554279]
 [1.13766109 0.90365443 0.18505159]]
Output:
 [[1.00148555e-04]
 [8.09738426e-05]
 [1.14503175e-04]]

	( EPOCH 4414 of 7000 )
h_ip:
 [[1.08542537 0.84431202 0.15239977]
 [1.02862205 0.76254651 0.09553927]
 [1.13765966 0.90365172 0.18504209]]
Output:
 [[1.00125325e-04]
 [8.09552575e-05]
 [1.14476379e-04]]

	( EPOCH 4415 of 7000 )
h_ip:
 [[1.08542433 0.84431004 0.15239286]
 [1.02862152 0.7625455  0.09553576]
 [1.13765824 0.90364902 0.1850326 ]]
Output:
 [[1.00102106e-04]
 [8.09366808e-05]
 [1.14449596e-04]]

	( EPOCH 4416 of 7000 )
h_ip:
 [[1.08542329 0.84430807 0.15238595]
 [1.028621 

 [1.09968350e-04]]

	( EPOCH 4590 of 7000 )
h_ip:
 [[1.08524612 0.84397063 0.15120366]
 [1.0285309  0.7623729  0.09493108]
 [1.13741365 0.90318334 0.18340004]]
Output:
 [[9.61957054e-05]
 [7.78114149e-05]
 [1.09943586e-04]]

	( EPOCH 4591 of 7000 )
h_ip:
 [[1.08524512 0.84396872 0.15119698]
 [1.0285304  0.76237193 0.09492768]
 [1.13741228 0.90318073 0.18339087]]
Output:
 [[9.61742453e-05]
 [7.77942464e-05]
 [1.09918832e-04]]

	( EPOCH 4592 of 7000 )
h_ip:
 [[1.08524412 0.84396682 0.1511903 ]
 [1.02852989 0.76237096 0.09492428]
 [1.1374109  0.90317811 0.1833817 ]]
Output:
 [[9.61527946e-05]
 [7.77770855e-05]
 [1.09894088e-04]]

	( EPOCH 4593 of 7000 )
h_ip:
 [[1.08524312 0.84396491 0.15118362]
 [1.02852938 0.76236999 0.09492089]
 [1.13740953 0.9031755  0.18337254]]
Output:
 [[9.61313533e-05]
 [7.77599321e-05]
 [1.09869356e-04]]

	( EPOCH 4594 of 7000 )
h_ip:
 [[1.08524212 0.84396301 0.15117695]
 [1.02852887 0.76236902 0.09491749]
 [1.13740816 0.90317289 0.18336337]]
Output:
 [[9.6109921

 [1.13719849 0.90277408 0.18196342]]
Output:
 [[9.28979314e-05]
 [7.51731801e-05]
 [1.06139670e-04]]

	( EPOCH 4750 of 7000 )
h_ip:
 [[1.08508839 0.84367047 0.15015071]
 [1.0284507  0.76222026 0.09439568]
 [1.13719715 0.90277154 0.18195452]]
Output:
 [[9.28778948e-05]
 [7.51571509e-05]
 [1.06116558e-04]]

	( EPOCH 4751 of 7000 )
h_ip:
 [[1.08508742 0.84366863 0.15014423]
 [1.0284502  0.76221932 0.09439238]
 [1.13719582 0.90276901 0.18194562]]
Output:
 [[9.28578666e-05]
 [7.51411285e-05]
 [1.06093456e-04]]

	( EPOCH 4752 of 7000 )
h_ip:
 [[1.08508645 0.84366678 0.15013775]
 [1.02844971 0.76221838 0.09438908]
 [1.13719449 0.90276648 0.18193672]]
Output:
 [[9.28378469e-05]
 [7.51251129e-05]
 [1.06070364e-04]]

	( EPOCH 4753 of 7000 )
h_ip:
 [[1.08508548 0.84366494 0.15013127]
 [1.02844922 0.76221744 0.09438579]
 [1.13719316 0.90276394 0.18192783]]
Output:
 [[9.28178357e-05]
 [7.51091041e-05]
 [1.06047282e-04]]

	( EPOCH 4754 of 7000 )
h_ip:
 [[1.08508451 0.84366309 0.15012479]
 [1.0284487

 [1.13703508 0.90246349 0.18087205]]
Output:
 [[9.04765874e-05]
 [7.32361379e-05]
 [1.03346749e-04]]

	( EPOCH 4874 of 7000 )
h_ip:
 [[1.08496936 0.84344414 0.14935589]
 [1.02839017 0.76210516 0.09399152]
 [1.13703378 0.90246102 0.18086335]]
Output:
 [[9.04575652e-05]
 [7.32209205e-05]
 [1.03324808e-04]]

	( EPOCH 4875 of 7000 )
h_ip:
 [[1.08496841 0.84344234 0.14934955]
 [1.02838969 0.76210424 0.0939883 ]
 [1.13703248 0.90245854 0.18085465]]
Output:
 [[9.04385509e-05]
 [7.32057094e-05]
 [1.03302876e-04]]

	( EPOCH 4876 of 7000 )
h_ip:
 [[1.08496746 0.84344053 0.14934321]
 [1.0283892  0.76210332 0.09398508]
 [1.13703117 0.90245607 0.18084595]]
Output:
 [[9.04195444e-05]
 [7.31905046e-05]
 [1.03280953e-04]]

	( EPOCH 4877 of 7000 )
h_ip:
 [[1.08496651 0.84343873 0.14933688]
 [1.02838872 0.76210241 0.09398186]
 [1.13702987 0.9024536  0.18083726]]
Output:
 [[9.04005458e-05]
 [7.31753061e-05]
 [1.03259039e-04]]

	( EPOCH 4878 of 7000 )
h_ip:
 [[1.08496556 0.84343693 0.14933054]
 [1.0283882

	( EPOCH 5022 of 7000 )
h_ip:
 [[1.08483076 0.84318078 0.14843015]
 [1.02831969 0.76197123 0.09352081]
 [1.13684355 0.90209971 0.17959246]]
Output:
 [[8.77264729e-05]
 [7.10361115e-05]
 [1.00174678e-04]]

	( EPOCH 5023 of 7000 )
h_ip:
 [[1.08482983 0.84317903 0.14842398]
 [1.02831922 0.76197034 0.09351767]
 [1.13684228 0.9020973  0.17958399]]
Output:
 [[8.77085714e-05]
 [7.10217907e-05]
 [1.00154030e-04]]

	( EPOCH 5024 of 7000 )
h_ip:
 [[1.08482891 0.84317727 0.14841781]
 [1.02831875 0.76196945 0.09351453]
 [1.13684102 0.90209489 0.17957551]]
Output:
 [[8.76906771e-05]
 [7.10074758e-05]
 [1.00133390e-04]]

	( EPOCH 5025 of 7000 )
h_ip:
 [[1.08482799 0.84317552 0.14841164]
 [1.02831828 0.76196856 0.0935114 ]
 [1.13683975 0.90209248 0.17956704]]
Output:
 [[8.76727899e-05]
 [7.09931665e-05]
 [1.00112759e-04]]

	( EPOCH 5026 of 7000 )
h_ip:
 [[1.08482706 0.84317377 0.14840547]
 [1.02831781 0.76196766 0.09350826]
 [1.13683848 0.90209008 0.17955857]]
Output:
 [[8.76549100e-05]
 [7.09788631e

	( EPOCH 5177 of 7000 )
h_ip:
 [[1.08468945 0.84291247 0.14748599]
 [1.02824783 0.76183479 0.09304073]
 [1.1366496  0.90173159 0.17829627]]
Output:
 [[8.50349515e-05]
 [6.88829678e-05]
 [9.70702897e-05]]

	( EPOCH 5178 of 7000 )
h_ip:
 [[1.08468855 0.84291077 0.14747998]
 [1.02824738 0.76183392 0.09303767]
 [1.13664837 0.90172925 0.17828802]]
Output:
 [[8.50181143e-05]
 [6.88694985e-05]
 [9.70508702e-05]]

	( EPOCH 5179 of 7000 )
h_ip:
 [[1.08468765 0.84290906 0.14747398]
 [1.02824692 0.76183305 0.09303462]
 [1.13664713 0.90172691 0.17827977]]
Output:
 [[8.50012837e-05]
 [6.88560344e-05]
 [9.70314582e-05]]

	( EPOCH 5180 of 7000 )
h_ip:
 [[1.08468675 0.84290735 0.14746797]
 [1.02824646 0.76183218 0.09303156]
 [1.1366459  0.90172457 0.17827152]]
Output:
 [[8.49844596e-05]
 [6.88425756e-05]
 [9.70120538e-05]]

	( EPOCH 5181 of 7000 )
h_ip:
 [[1.08468585 0.84290565 0.14746196]
 [1.02824601 0.76183132 0.09302851]
 [1.13664467 0.90172223 0.17826328]]
Output:
 [[8.49676421e-05]
 [6.88291221e

 [1.13644514 0.90134383 0.17692935]]
Output:
 [[8.22954192e-05]
 [6.66914044e-05]
 [9.39106547e-05]]

	( EPOCH 5346 of 7000 )
h_ip:
 [[1.0845396  0.84262817 0.14648448]
 [1.02817164 0.76169021 0.09253148]
 [1.13644394 0.90134155 0.17692133]]
Output:
 [[8.22796323e-05]
 [6.66787752e-05]
 [9.38924473e-05]]

	( EPOCH 5347 of 7000 )
h_ip:
 [[1.08453873 0.84262652 0.14647863]
 [1.02817119 0.76168937 0.09252851]
 [1.13644275 0.90133928 0.17691331]]
Output:
 [[8.22638513e-05]
 [6.66661507e-05]
 [9.38742469e-05]]

	( EPOCH 5348 of 7000 )
h_ip:
 [[1.08453786 0.84262486 0.14647279]
 [1.02817075 0.76168853 0.09252554]
 [1.13644155 0.90133701 0.17690529]]
Output:
 [[8.22480764e-05]
 [6.66535310e-05]
 [9.38560533e-05]]

	( EPOCH 5349 of 7000 )
h_ip:
 [[1.08453698 0.8426232  0.14646695]
 [1.02817031 0.76168768 0.09252257]
 [1.13644035 0.90133473 0.17689727]]
Output:
 [[8.22323073e-05]
 [6.66409160e-05]
 [9.38378665e-05]]

	( EPOCH 5350 of 7000 )
h_ip:
 [[1.08453611 0.84262155 0.14646111]
 [1.0281698


	( EPOCH 5497 of 7000 )
h_ip:
 [[1.08440925 0.84238103 0.14561292]
 [1.02810535 0.76156453 0.09208832]
 [1.13626504 0.90100249 0.1757248 ]]
Output:
 [[7.99622887e-05]
 [6.48249251e-05]
 [9.12198675e-05]]

	( EPOCH 5498 of 7000 )
h_ip:
 [[1.0844084  0.84237942 0.14560722]
 [1.02810492 0.76156371 0.09208542]
 [1.13626387 0.90100027 0.17571697]]
Output:
 [[7.99473700e-05]
 [6.48129902e-05]
 [9.12026622e-05]]

	( EPOCH 5499 of 7000 )
h_ip:
 [[1.08440755 0.8423778  0.14560152]
 [1.02810449 0.76156289 0.09208252]
 [1.1362627  0.90099806 0.17570915]]
Output:
 [[7.99324568e-05]
 [6.48010596e-05]
 [9.11854633e-05]]

	( EPOCH 5500 of 7000 )
h_ip:
 [[1.08440669 0.84237619 0.14559582]
 [1.02810405 0.76156207 0.09207962]
 [1.13626153 0.90099584 0.17570132]]
Output:
 [[7.99175490e-05]
 [6.47891335e-05]
 [9.11682707e-05]]

	( EPOCH 5501 of 7000 )
h_ip:
 [[1.08440584 0.84237457 0.14559012]
 [1.02810362 0.76156124 0.09207672]
 [1.13626036 0.90099363 0.1756935 ]]
Output:
 [[7.99026467e-05]
 [6.47772117

 [8.84964490e-05]]

	( EPOCH 5661 of 7000 )
h_ip:
 [[1.08427125 0.84211957 0.14468989]
 [1.02803518 0.76143156 0.09161898]
 [1.13607563 0.90064377 0.1744576 ]]
Output:
 [[7.75866789e-05]
 [6.29244178e-05]
 [8.84802296e-05]]

	( EPOCH 5662 of 7000 )
h_ip:
 [[1.08427042 0.84211799 0.14468434]
 [1.02803476 0.76143076 0.09161615]
 [1.13607449 0.90064162 0.17444998]]
Output:
 [[7.75726193e-05]
 [6.29131699e-05]
 [8.84640161e-05]]

	( EPOCH 5663 of 7000 )
h_ip:
 [[1.08426959 0.84211642 0.14467878]
 [1.02803433 0.76142996 0.09161333]
 [1.13607335 0.90063946 0.17444235]]
Output:
 [[7.75585647e-05]
 [6.29019259e-05]
 [8.84478083e-05]]

	( EPOCH 5664 of 7000 )
h_ip:
 [[1.08426876 0.84211485 0.14467323]
 [1.02803391 0.76142916 0.09161051]
 [1.13607221 0.9006373  0.17443473]]
Output:
 [[7.75445151e-05]
 [6.28906860e-05]
 [8.84316063e-05]]

	( EPOCH 5665 of 7000 )
h_ip:
 [[1.08426793 0.84211328 0.14466768]
 [1.02803349 0.76142837 0.09160768]
 [1.13607107 0.90063514 0.1744271 ]]
Output:
 [[7.7530470

 [8.62652592e-05]]

	( EPOCH 5802 of 7000 )
h_ip:
 [[1.08415542 0.84190026 0.14391496]
 [1.02797628 0.76132004 0.09122494]
 [1.13591667 0.9003429  0.17339371]]
Output:
 [[7.56525342e-05]
 [6.13770395e-05]
 [8.62498263e-05]]

	( EPOCH 5803 of 7000 )
h_ip:
 [[1.08415461 0.84189872 0.14390952]
 [1.02797587 0.76131926 0.09122218]
 [1.13591555 0.90034079 0.17338625]]
Output:
 [[7.56391556e-05]
 [6.13663360e-05]
 [8.62343988e-05]]

	( EPOCH 5804 of 7000 )
h_ip:
 [[1.0841538  0.84189718 0.14390409]
 [1.02797546 0.76131847 0.09121941]
 [1.13591444 0.90033868 0.17337879]]
Output:
 [[7.56257815e-05]
 [6.13556362e-05]
 [8.62189767e-05]]

	( EPOCH 5805 of 7000 )
h_ip:
 [[1.08415299 0.84189565 0.14389865]
 [1.02797504 0.76131769 0.09121665]
 [1.13591332 0.90033657 0.17337132]]
Output:
 [[7.56124122e-05]
 [6.13449401e-05]
 [8.62035599e-05]]

	( EPOCH 5806 of 7000 )
h_ip:
 [[1.08415217 0.84189411 0.14389322]
 [1.02797463 0.76131691 0.09121389]
 [1.13591221 0.90033446 0.17336386]]
Output:
 [[7.5599047

 [1.13573389 0.89999717 0.17217   ]]
Output:
 [[7.34936258e-05]
 [5.96497783e-05]
 [8.37603783e-05]]

	( EPOCH 5969 of 7000 )
h_ip:
 [[1.08402145 0.84164675 0.14301831]
 [1.02790816 0.76119112 0.09076902]
 [1.1357328  0.89999511 0.17216272]]
Output:
 [[7.34809875e-05]
 [5.96396667e-05]
 [8.37458055e-05]]

	( EPOCH 5970 of 7000 )
h_ip:
 [[1.08402066 0.84164526 0.14301301]
 [1.02790776 0.76119036 0.09076632]
 [1.13573171 0.89999306 0.17215544]]
Output:
 [[7.34683535e-05]
 [5.96295584e-05]
 [8.37312377e-05]]

	( EPOCH 5971 of 7000 )
h_ip:
 [[1.08401987 0.84164376 0.1430077 ]
 [1.02790735 0.7611896  0.09076363]
 [1.13573063 0.899991   0.17214816]]
Output:
 [[7.34557237e-05]
 [5.96194536e-05]
 [8.37166747e-05]]

	( EPOCH 5972 of 7000 )
h_ip:
 [[1.08401908 0.84164226 0.1430024 ]
 [1.02790695 0.76118884 0.09076093]
 [1.13572954 0.89998895 0.17214088]]
Output:
 [[7.34430982e-05]
 [5.96093522e-05]
 [8.37021167e-05]]

	( EPOCH 5973 of 7000 )
h_ip:
 [[1.08401829 0.84164076 0.1429971 ]
 [1.0279065

 [1.13557366 0.89969428 0.1710969 ]]
Output:
 [[7.16564959e-05]
 [5.81798939e-05]
 [8.16421117e-05]]

	( EPOCH 6118 of 7000 )
h_ip:
 [[1.08390473 0.84142601 0.14223678]
 [1.0278488  0.76107886 0.09037163]
 [1.1355726  0.89969227 0.17108977]]
Output:
 [[7.16444712e-05]
 [5.81702728e-05]
 [8.16282474e-05]]

	( EPOCH 6119 of 7000 )
h_ip:
 [[1.08390395 0.84142454 0.14223159]
 [1.02784841 0.76107812 0.090369  ]
 [1.13557153 0.89969026 0.17108265]]
Output:
 [[7.16324506e-05]
 [5.81606548e-05]
 [8.16143877e-05]]

	( EPOCH 6120 of 7000 )
h_ip:
 [[1.08390318 0.84142308 0.14222641]
 [1.02784801 0.76107737 0.09036636]
 [1.13557047 0.89968825 0.17107553]]
Output:
 [[7.16204338e-05]
 [5.81510400e-05]
 [8.16005325e-05]]

	( EPOCH 6121 of 7000 )
h_ip:
 [[1.0839024  0.84142162 0.14222122]
 [1.02784762 0.76107663 0.09036372]
 [1.13556941 0.89968624 0.17106841]]
Output:
 [[7.16084211e-05]
 [5.81414284e-05]
 [8.15866819e-05]]

	( EPOCH 6122 of 7000 )
h_ip:
 [[1.08390163 0.84142015 0.14221603]
 [1.0278472

 [1.13540857 0.89938237 0.16999084]]
Output:
 [[6.98160021e-05]
 [5.67072449e-05]
 [7.95201078e-05]]

	( EPOCH 6275 of 7000 )
h_ip:
 [[1.08378445 0.84119869 0.14143125]
 [1.02778764 0.76096326 0.08996204]
 [1.13540753 0.89938041 0.16998387]]
Output:
 [[6.98045771e-05]
 [5.66981032e-05]
 [7.95069359e-05]]

	( EPOCH 6276 of 7000 )
h_ip:
 [[1.0837837  0.84119726 0.14142618]
 [1.02778726 0.76096254 0.08995946]
 [1.13540649 0.89937845 0.16997691]]
Output:
 [[6.97931559e-05]
 [5.66889643e-05]
 [7.94937681e-05]]

	( EPOCH 6277 of 7000 )
h_ip:
 [[1.08378294 0.84119583 0.14142111]
 [1.02778687 0.76096181 0.08995688]
 [1.13540545 0.89937648 0.16996994]]
Output:
 [[6.97817383e-05]
 [5.66798284e-05]
 [7.94806046e-05]]

	( EPOCH 6278 of 7000 )
h_ip:
 [[1.08378218 0.8411944  0.14141604]
 [1.02778649 0.76096108 0.08995431]
 [1.13540441 0.89937452 0.16996298]]
Output:
 [[6.97703243e-05]
 [5.66706954e-05]
 [7.94674454e-05]]

	( EPOCH 6279 of 7000 )
h_ip:
 [[1.08378143 0.84119297 0.14141096]
 [1.0277861


	( EPOCH 6464 of 7000 )
h_ip:
 [[1.0836432  0.84093188 0.1404848 ]
 [1.02771581 0.76082758 0.0894808 ]
 [1.13521367 0.89901437 0.1686845 ]]
Output:
 [[6.77093251e-05]
 [5.50215068e-05]
 [7.70914002e-05]]

	( EPOCH 6465 of 7000 )
h_ip:
 [[1.08364246 0.84093048 0.14047986]
 [1.02771544 0.76082687 0.08947829]
 [1.13521265 0.89901246 0.16867771]]
Output:
 [[6.76985681e-05]
 [5.50128988e-05]
 [7.70789993e-05]]

	( EPOCH 6466 of 7000 )
h_ip:
 [[1.08364172 0.84092909 0.14047492]
 [1.02771506 0.76082616 0.08947577]
 [1.13521164 0.89901055 0.16867093]]
Output:
 [[6.76878143e-05]
 [5.50042934e-05]
 [7.70666023e-05]]

	( EPOCH 6467 of 7000 )
h_ip:
 [[1.08364099 0.8409277  0.14046998]
 [1.02771469 0.76082545 0.08947326]
 [1.13521063 0.89900864 0.16866414]]
Output:
 [[6.76770640e-05]
 [5.49956908e-05]
 [7.70542092e-05]]

	( EPOCH 6468 of 7000 )
h_ip:
 [[1.08364025 0.84092631 0.14046504]
 [1.02771431 0.76082475 0.08947075]
 [1.13520962 0.89900673 0.16865736]]
Output:
 [[6.76663169e-05]
 [5.49870908


	( EPOCH 6639 of 7000 )
h_ip:
 [[1.08351567 0.84069115 0.13963   ]
 [1.02765097 0.76070516 0.08904615]
 [1.13503865 0.89868411 0.16751094]]
Output:
 [[6.58766425e-05]
 [5.35549085e-05]
 [7.49787562e-05]]

	( EPOCH 6640 of 7000 )
h_ip:
 [[1.08351495 0.84068979 0.13962517]
 [1.0276506  0.76070447 0.0890437 ]
 [1.13503766 0.89868225 0.16750431]]
Output:
 [[6.58664503e-05]
 [5.35467519e-05]
 [7.49670076e-05]]

	( EPOCH 6641 of 7000 )
h_ip:
 [[1.08351423 0.84068843 0.13962035]
 [1.02765023 0.76070378 0.08904124]
 [1.13503667 0.89868039 0.16749768]]
Output:
 [[6.58562612e-05]
 [5.35385978e-05]
 [7.49552625e-05]]

	( EPOCH 6642 of 7000 )
h_ip:
 [[1.08351351 0.84068707 0.13961552]
 [1.02764987 0.76070309 0.08903879]
 [1.13503568 0.89867852 0.16749106]]
Output:
 [[6.58460752e-05]
 [5.35304462e-05]
 [7.49435210e-05]]

	( EPOCH 6643 of 7000 )
h_ip:
 [[1.08351279 0.84068572 0.1396107 ]
 [1.0276495  0.76070239 0.08903634]
 [1.13503469 0.89867666 0.16748443]]
Output:
 [[6.58358923e-05]
 [5.35222970


	( EPOCH 6780 of 7000 )
h_ip:
 [[1.0834151  0.8405014  0.13895563]
 [1.02759982 0.76060866 0.08870325]
 [1.13490062 0.8984238  0.16658509]]
Output:
 [[6.44695032e-05]
 [5.24287727e-05]
 [7.33567909e-05]]

	( EPOCH 6781 of 7000 )
h_ip:
 [[1.08341439 0.84050007 0.13895089]
 [1.02759946 0.76060799 0.08870084]
 [1.13489965 0.89842197 0.16657859]]
Output:
 [[6.44597346e-05]
 [5.24209546e-05]
 [7.33455313e-05]]

	( EPOCH 6782 of 7000 )
h_ip:
 [[1.08341369 0.84049874 0.13894615]
 [1.02759911 0.76060731 0.08869844]
 [1.13489868 0.89842015 0.16657208]]
Output:
 [[6.44499688e-05]
 [5.24131387e-05]
 [7.33342750e-05]]

	( EPOCH 6783 of 7000 )
h_ip:
 [[1.08341298 0.8404974  0.13894142]
 [1.02759875 0.76060663 0.08869603]
 [1.13489771 0.89841832 0.16656558]]
Output:
 [[6.44402059e-05]
 [5.24053252e-05]
 [7.33230221e-05]]

	( EPOCH 6784 of 7000 )
h_ip:
 [[1.08341227 0.84049607 0.13893668]
 [1.02759839 0.76060595 0.08869362]
 [1.13489674 0.89841649 0.16655908]]
Output:
 [[6.44304460e-05]
 [5.23975141


	( EPOCH 6979 of 7000 )
h_ip:
 [[1.08327631 0.8402397  0.13802464]
 [1.02752925 0.76047558 0.08822987]
 [1.13471014 0.89806477 0.16530694]]
Output:
 [[6.25812256e-05]
 [5.09174621e-05]
 [7.11804251e-05]]

	( EPOCH 6980 of 7000 )
h_ip:
 [[1.08327562 0.8402384  0.13802002]
 [1.0275289  0.76047492 0.08822752]
 [1.1347092  0.89806299 0.1653006 ]]
Output:
 [[6.25720114e-05]
 [5.09100870e-05]
 [7.11698056e-05]]

	( EPOCH 6981 of 7000 )
h_ip:
 [[1.08327493 0.8402371  0.13801541]
 [1.02752855 0.76047426 0.08822518]
 [1.13470825 0.89806121 0.16529425]]
Output:
 [[6.25627998e-05]
 [5.09027140e-05]
 [7.11591892e-05]]

	( EPOCH 6982 of 7000 )
h_ip:
 [[1.08327424 0.8402358  0.13801079]
 [1.0275282  0.7604736  0.08822283]
 [1.13470731 0.89805943 0.16528792]]
Output:
 [[6.25535908e-05]
 [5.08953431e-05]
 [7.11485759e-05]]

	( EPOCH 6983 of 7000 )
h_ip:
 [[1.08327355 0.84023451 0.13800617]
 [1.02752785 0.76047294 0.08822048]
 [1.13470636 0.89805765 0.16528158]]
Output:
 [[6.25443846e-05]
 [5.08879744

In [25]:
print("Actual output: \n", y)
print("\nPredicted output: \n", output)


Actual output: 
 [[0.0092]
 [0.0086]
 [0.0089]]

Predicted output: 
 [[1.00006296]
 [1.0000512 ]
 [1.00007158]]
