In [1]:
import pandas as pd
import numpy as np

In [2]:
# x is input
# y is output
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x

array([[2., 9.],
       [1., 5.],
       [3., 6.]])

In [4]:
y

array([[92.],
       [86.],
       [89.]])

In [6]:
# normalize value means value should be between o and 1
c=np.max(x,axis=0)# to check maximum value column wise
c

array([3., 9.])

In [8]:
x=x/c
x

array([[0.22222222, 0.11111111],
       [0.11111111, 0.0617284 ],
       [0.33333333, 0.07407407]])

In [10]:
y=y/100 # normalize the output value by 100 beacuse maximum marks is 100
y

array([[0.0092],
       [0.0086],
       [0.0089]])

In [11]:
def sigmoid(x): # finding activation function
    return 1/1+np.exp(-x)
def sigmoid_grad(x):# think it has diffrenciation during back propagation
    return x*(1-x)

In [20]:
epoch=7000 # number of iteration 
eta=0.1# learning rate
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

In [14]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))# wight at hidden is the size between input and hidden
wh

array([[0.54923597, 0.75484849, 0.83385038],
       [0.07515447, 0.30850947, 0.4431128 ]])

In [16]:
wh.shape

(2, 3)

In [18]:
bh=np.random.uniform(size=(1,hidden_neurons))# bias at hidden
bh

array([[0.97116601, 0.67757731, 0.03521903]])

In [21]:
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
print("Weights from hidden to Output Layer:\n",wout)

Weights from hidden to Output Layer:
 [[0.24136229]
 [0.68967786]
 [0.9916053 ]]


In [23]:
bout = np.random.uniform(size = (1, output_neurons))
print("Output Bias:\n",bout)

Output Bias:
 [[0.39607037]]


In [ ]:
for i in range(epoch):
    #forward pass
    print("\n\t( EPOCH {} of {} )".format(i+1, epoch))
    h_ip = np.dot(x, wh) + bh # to find hidden input value=dot product of input * weight at hidden + bais at hidden
    print("h_ip:\n", h_ip)
    h_act = sigmoid(h_ip)# activation for hidden value
    o_ip = np.dot(h_act, wout) + bout 
    output = sigmoid(o_ip)
    ###########################################
    eo = y - output # finding error at output layer where y is actual output 
    out_grad = sigmoid_grad(output) # diffrenctiating the output 
    d_output = eo * out_grad# getting delta out put = error * gradient output 
    print("Output:\n", d_output)
    eh = d_output.dot(wout.T) # finding error at hidden layer 
    hidden_grad = sigmoid_grad(h_act)
    d_hidden = eh * hidden_grad # same as above 
    wout += h_act.T.dot(d_output) * eta #
    wh += x.T.dot(d_hidden) * eta