In [1]:
import pandas as pd
import numpy as np

In [2]:
x=np.array(([2,9],[1,5],[3,7]),dtype=float)
x

array([[2., 9.],
       [1., 5.],
       [3., 7.]])

In [3]:
y=np.array(([98],[86],[80]),dtype=float)
y

array([[98.],
       [86.],
       [80.]])

In [4]:
c=np.max(x,axis=0)
c


array([3., 9.])

In [5]:
x=x/c
y=y/100

In [6]:
x

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.77777778]])

In [7]:
y

array([[0.98],
       [0.86],
       [0.8 ]])

In [8]:
def sigmoid(x): # finding activation function
    return 1/1+np.exp(-x)
def sig_grad(x):
    return x*(1-x)

In [9]:
epoch=1000
eta=0.1
input_neurons=2
hidden_neurons=3
output_neurons=1

In [10]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
wh

array([[0.71387646, 0.02904185, 0.40399803],
       [0.91269687, 0.99904249, 0.01723349]])

In [11]:
bh=np.random.uniform(size=(1,hidden_neurons))
bh

array([[0.35479675, 0.94768799, 0.93523644]])

In [12]:
wout=np.random.uniform(size=(hidden_neurons,output_neurons))
wout


array([[0.87846546],
       [0.89774198],
       [0.47689339]])

In [13]:
bh=np.random.uniform(size=(1,output_neurons))
bh

array([[0.31513473]])

In [14]:
for i in range(epoch):
    #forword pass
    h_input=np.dot(x,wh)
    h_act=sigmoid(h_input)
    w_out=np.dot(h_act,wout)
    output=sigmoid(w_out)
#############################
    e=y-output
    ouptut_grad=sig_grad(output)
    delta_output=e*output
    ########################
#     error at hidden layer
    eh=delta_output.dot(wout.T)
    hidden_grad=sig_grad(h_act)
    delta_hidden=eh*hidden_grad
    wout+=h_act.T.dot(delta_output)*eta
    wh+=x.T.dot(delta_hidden)*eta
    

<ipython-input-8-5e7670b9bf84>:2: RuntimeWarning: overflow encountered in exp
  return 1/1+np.exp(-x)


In [15]:
print(output)

[[inf]
 [inf]
 [inf]]
