In [1]:
import pandas as pd
import numpy as np

In [2]:
x=np.array(([2,9],[1,5],[3,7]),dtype=float)
x

array([[2., 9.],
       [1., 5.],
       [3., 7.]])

In [3]:
y=np.array(([98],[86],[80]),dtype=float)
y

array([[98.],
       [86.],
       [80.]])

In [4]:
c=np.max(x,axis=0)
c


array([3., 9.])

In [5]:
x=x/c
y=y/100

In [6]:
x

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.77777778]])

In [7]:
y

array([[0.98],
       [0.86],
       [0.8 ]])

In [8]:
def sigmoid(x): # finding activation function
    return 1/1+np.exp(-x)
def sigmoid_grad(x):# think it has diffrenciation during back propagation
    return x*(1-x)

In [9]:
epoch=1000
eta=0.1
input_neurons=2
hidden_neurons=3
output_neurons=1

In [10]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
wh

array([[0.01323433, 0.31308689, 0.94743723],
       [0.84699396, 0.35762798, 0.33055924]])

In [11]:
bh=np.random.uniform(size=(1,hidden_neurons))
bh

array([[0.88597266, 0.37132015, 0.84635128]])

In [12]:
wout=np.random.uniform(size=(hidden_neurons,output_neurons))
wout


array([[0.66159589],
       [0.58869788],
       [0.33983178]])

In [13]:
bout=np.random.uniform(size=(1,output_neurons))
bh

array([[0.88597266, 0.37132015, 0.84635128]])

In [14]:
for i in range(epoch):
    #forword pass
    print("\n\t( EPOCH {} of {} )".format(i+1, epoch))
    h_ip = np.dot(x, wh) + bh # to find hidden input value=dot product of input * weight at hidden + bais at hidden
    print("h_ip:\n", h_ip)
    h_act = sigmoid(h_ip)# activation for hidden value
    o_ip = np.dot(h_act, wout) + bout 
    output = sigmoid(o_ip)
    ###########################################
    eo = y - output # finding error at output layer where y is actual output 
    out_grad = sigmoid_grad(output) # diffrenctiating the output 
    d_output = eo * out_grad# getting delta out put = error * gradient output 
    print("Output:\n", d_output)
    eh = d_output.dot(wout.T) # finding error at hidden layer 
    hidden_grad = sigmoid_grad(h_act)
    d_hidden = eh * hidden_grad # same as above 
    wout += h_act.T.dot(d_output) * eta #
    wh += x.T.dot(d_hidden) * eta


	( EPOCH 1 of 1000 )
h_ip:
 [[1.7417895  0.93767272 1.80853534]
 [1.3609363  0.67436466 1.34580771]
 [1.55798007 0.96256214 2.05089014]]
Output:
 [[0.00592731]
 [0.01154583]
 [0.01830314]]

	( EPOCH 2 of 1000 )
h_ip:
 [[1.74103562 0.93617013 1.80824929]
 [1.36053394 0.67356209 1.34565468]
 [1.55717968 0.96097473 2.05059119]]
Output:
 [[0.00574025]
 [0.01125941]
 [0.01788879]]

	( EPOCH 3 of 1000 )
h_ip:
 [[1.7402948  0.93468961 1.80796689]
 [1.36013856 0.67277134 1.3455036 ]
 [1.55639307 0.95941041 2.05029602]]
Output:
 [[0.00556376]
 [0.0109877 ]
 [0.01749463]]

	( EPOCH 4 of 1000 )
h_ip:
 [[1.7395665  0.93323028 1.80768804]
 [1.35974987 0.67199191 1.34535442]
 [1.55561964 0.95786825 2.05000451]]
Output:
 [[0.00539699]
 [0.01072958]
 [0.01711916]]

	( EPOCH 5 of 1000 )
h_ip:
 [[1.73885017 0.93179131 1.80741261]
 [1.35936757 0.67122338 1.34520708]
 [1.55485883 0.95634739 2.04971656]]
Output:
 [[0.00523916]
 [0.01048403]
 [0.01676102]]

	( EPOCH 6 of 1000 )
h_ip:
 [[1.73814533 0.930371

 [1.4882439  0.81022295 2.02187771]]
Output:
 [[0.00074304]
 [0.0023551 ]
 [0.00415428]]

	( EPOCH 171 of 1000 )
h_ip:
 [[1.67614033 0.79363562 1.78078064]
 [1.32592099 0.59749206 1.33096835]
 [1.48798581 0.80960904 2.02176419]]
Output:
 [[0.00073867]
 [0.00234445]
 [0.00413627]]

	( EPOCH 172 of 1000 )
h_ip:
 [[1.67589981 0.79306126 1.7806731 ]
 [1.32579276 0.5971857  1.33091088]
 [1.48772856 0.8089968  2.02165103]]
Output:
 [[0.00073436]
 [0.0023339 ]
 [0.00411841]]

	( EPOCH 173 of 1000 )
h_ip:
 [[1.67566008 0.79248845 1.78056591]
 [1.32566496 0.59688018 1.33085359]
 [1.48747217 0.8083862  2.02153821]]
Output:
 [[0.00073009]
 [0.00232344]
 [0.00410071]]

	( EPOCH 174 of 1000 )
h_ip:
 [[1.67542115 0.7919172  1.78045904]
 [1.32553758 0.59657548 1.33079648]
 [1.48721662 0.80777724 2.02142574]]
Output:
 [[0.00072586]
 [0.00231308]
 [0.00408316]]

	( EPOCH 175 of 1000 )
h_ip:
 [[1.675183   0.79134748 1.78035251]
 [1.32541062 0.59627161 1.33073955]
 [1.4869619  0.80716991 2.02131362]]
Out

 [1.45261318 0.72175487 2.00603423]]
Output:
 [[0.00035439]
 [0.00132106]
 [0.00236886]]

	( EPOCH 344 of 1000 )
h_ip:
 [[1.64294139 0.71092588 1.76577545]
 [1.30822475 0.55338528 1.32295018]
 [1.45244526 0.72131934 2.00595895]]
Output:
 [[0.00035326]
 [0.00131771]
 [0.00236295]]

	( EPOCH 345 of 1000 )
h_ip:
 [[1.64278496 0.71051899 1.76570416]
 [1.30814138 0.55316834 1.32291209]
 [1.45227766 0.72088446 2.0058838 ]]
Output:
 [[0.00035214]
 [0.00131438]
 [0.00235706]]

	( EPOCH 346 of 1000 )
h_ip:
 [[1.64262883 0.71011272 1.765633  ]
 [1.30805817 0.55295172 1.32287407]
 [1.45211038 0.72045022 2.0058088 ]]
Output:
 [[0.00035102]
 [0.00131107]
 [0.0023512 ]]

	( EPOCH 347 of 1000 )
h_ip:
 [[1.642473   0.70970705 1.76556198]
 [1.30797512 0.55273544 1.32283612]
 [1.45194343 0.72001663 2.00573394]]
Output:
 [[0.00034991]
 [0.00130777]
 [0.00234537]]

	( EPOCH 348 of 1000 )
h_ip:
 [[1.64231747 0.70930199 1.76549109]
 [1.30789223 0.55251947 1.32279824]
 [1.45177679 0.71958369 2.00565921]]
Out

 [[0.00022881]
 [0.00092987]
 [0.00166962]]

	( EPOCH 509 of 1000 )
h_ip:
 [[1.6204509  0.65060655 1.75549239]
 [1.29623879 0.52122854 1.31745621]
 [1.42833882 0.65680226 1.99511612]]
Output:
 [[0.0002283 ]
 [0.00092819]
 [0.00166659]]

	( EPOCH 510 of 1000 )
h_ip:
 [[1.62033135 0.6502757  1.75543759]
 [1.29617508 0.52105218 1.31742693]
 [1.42821063 0.65644814 1.99505832]]
Output:
 [[0.0002278 ]
 [0.00092652]
 [0.00166358]]

	( EPOCH 511 of 1000 )
h_ip:
 [[1.62021196 0.6499452  1.75538286]
 [1.29611146 0.52087601 1.31739769]
 [1.42808263 0.6560944  1.9950006 ]]
Output:
 [[0.00022729]
 [0.00092486]
 [0.00166057]]

	( EPOCH 512 of 1000 )
h_ip:
 [[1.62009275 0.64961504 1.75532821]
 [1.29604793 0.52070002 1.31736849]
 [1.4279548  0.65574102 1.99494295]]
Output:
 [[0.00022679]
 [0.0009232 ]
 [0.00165757]]

	( EPOCH 513 of 1000 )
h_ip:
 [[1.6199737  0.64928524 1.75527363]
 [1.29598449 0.52052421 1.31733933]
 [1.42782715 0.65538801 1.99488539]]
Output:
 [[0.00022629]
 [0.00092155]
 [0.0016545

 [[1.60346044 0.60240906 1.74769409]
 [1.2871848  0.49553864 1.31329004]
 [1.41011715 0.60519104 1.9868898 ]]
Output:
 [[0.00016805]
 [0.00072275]
 [0.00129226]]

	( EPOCH 667 of 1000 )
h_ip:
 [[1.60336222 0.60212328 1.74764896]
 [1.28713246 0.49538633 1.31326594]
 [1.41001179 0.60488488 1.98684219]]
Output:
 [[0.00016776]
 [0.00072173]
 [0.00129038]]

	( EPOCH 668 of 1000 )
h_ip:
 [[1.60326411 0.60183774 1.74760389]
 [1.28708018 0.49523414 1.31324186]
 [1.40990655 0.60457898 1.98679463]]
Output:
 [[0.00016748]
 [0.00072071]
 [0.00128851]]

	( EPOCH 669 of 1000 )
h_ip:
 [[1.60316611 0.60155243 1.74755886]
 [1.28702796 0.49508208 1.3132178 ]
 [1.40980142 0.60427332 1.98674713]]
Output:
 [[0.00016719]
 [0.00071969]
 [0.00128664]]

	( EPOCH 670 of 1000 )
h_ip:
 [[1.60306822 0.60126736 1.74751388]
 [1.28697579 0.49493014 1.31319377]
 [1.40969642 0.60396791 1.98669968]]
Output:
 [[0.0001669 ]
 [0.00071867]
 [0.00128477]]

	( EPOCH 671 of 1000 )
h_ip:
 [[1.60297044 0.60098252 1.74746896]
 [1


	( EPOCH 838 of 1000 )
h_ip:
 [[1.58800546 0.55635205 1.74058972]
 [1.27894943 0.47099276 1.30949471]
 [1.39353706 0.55583139 1.97939423]]
Output:
 [[0.00012881]
 [0.00058034]
 [0.00102937]]

	( EPOCH 839 of 1000 )
h_ip:
 [[1.58792311 0.55610054 1.74055185]
 [1.27890555 0.47085873 1.30947448]
 [1.39344871 0.55556176 1.97935427]]
Output:
 [[0.00012863]
 [0.00057967]
 [0.00102813]]

	( EPOCH 840 of 1000 )
h_ip:
 [[1.58784084 0.55584921 1.74051402]
 [1.27886171 0.47072479 1.30945427]
 [1.39336044 0.55529231 1.97931436]]
Output:
 [[0.00012846]
 [0.000579  ]
 [0.00102689]]

	( EPOCH 841 of 1000 )
h_ip:
 [[1.58775864 0.55559805 1.74047622]
 [1.27881791 0.47059094 1.30943407]
 [1.39327226 0.55502303 1.97927448]]
Output:
 [[0.00012828]
 [0.00057834]
 [0.00102566]]

	( EPOCH 842 of 1000 )
h_ip:
 [[1.58767653 0.55534705 1.74043846]
 [1.27877415 0.47045718 1.3094139 ]
 [1.39318415 0.55475394 1.97923463]]
Output:
 [[0.0001281 ]
 [0.00057767]
 [0.00102442]]

	( EPOCH 843 of 1000 )
h_ip:
 [[1.58759

In [15]:
print(output)

[[1.00429142]
 [1.0033956 ]
 [1.0041862 ]]
