In [1]:
import pandas as pd 
import numpy as np 

In [3]:
x=np.array(([2,9],[1,5],[3,7]),dtype=float)
y=np.array(([90],[89],[97]),dtype=float)

In [4]:
x

array([[2., 9.],
       [1., 5.],
       [3., 7.]])

In [5]:
y

array([[90.],
       [89.],
       [97.]])

In [7]:
c=np.max(x,axis=0)
c

array([3., 9.])

In [8]:
x=x/c
y=y/100

In [9]:
x

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.77777778]])

In [10]:
y

array([[0.9 ],
       [0.89],
       [0.97]])

In [12]:
def sigmoid(x):
    return (1/1+np.exp(-x))
def sigmoid_grad(x):
    return x*(1-x)

In [13]:
epoch=1000
eta=0.1
input_neurons=2
hidden_neurons=3
output_neurons=1

In [15]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wout=np.random.uniform(size=(hidden_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))


In [16]:
for i in range(epoch):
    h_ip=np.dot(x,wh)+bh
    h_act=sigmoid(h_ip)
    o_ip=np.dot(h_act,wout)+bout
    output=sigmoid(o_ip)
    e=y-output
    output_grad=sigmoid_grad(output)
    d_output=e*output_grad
    eh=d_output.dot(wout.T)
    hidden_grad=sigmoid_grad(h_act)
    d_hidden=eh*hidden_grad
    wout+=h_act.T.dot(d_output)*eta
    wh+=x.T.dot
    